### PR TITLE
feat: ignore vim *.swp files in hot-reload example

### PR DESCRIPTION
**Pull request by davidxia**
It is not obvious that `skaffold dev` will rebuild the image
even when a file that is not mapped in `skaffold.yaml`'s
manual sync config is added or changed. `skaffold dev` instead
respects `.dockerignore` as I discovered
[in this issue](https://github.com/GoogleContainerTools/skaffold/issues/3124).

Add `**/*.swp` to both node and python directories in the hot-reload
example so that this example is more likely to work out-of-the-box
for new users.

### CODE REVIEW

**Review by briandealwis — APPROVED** [review]
Thanks!

**Comment by davidxia** [comment]
looks like kokoro is stuck preventing the auto-merge?

**Comment by MarlonGamez** [comment]
hey @davidxia , sorry for the delay on this! I've triggered the kokoro build. I'll merge this when done assuming it goes green

**Comment by davidxia** [comment]
@MarlonGamez thank you!

**Pull request merged**
