### PR TITLE
Expand home directory for setFiles in helm deployment

### PR DESCRIPTION
**Pull request by kri5**
This allows to pass values coming from files located under
the home directory, such as configuration or credentials.

Feel free to comment.

### CODE REVIEW

**Comment by kri5** [comment]
@googlebot I signed it!

**Comment by MarlonGamez** [comment]
Hi @kri5, thanks for the PR! If you get the chance, would you be able to add 1 or 2 tests for that functionality?

**Comment by kri5** [comment]
@MarlonGamez I'm not very familiar with golang and the project. I attempted to add tests for this feature, with no much success nor clue on how to do it. :/

**Comment by tejal29** [comment]
@MarlonGamez  Can you pease give @kri5 some pointers. If not @kri5 is it ok we add commits to your branch?

**Comment by MarlonGamez** [comment]
Hey @kri5 , I'm adding a test in PR #4735 that should give a bit of a base to work off :) You should be able to just add to the SetFiles field in the var testDeployConfigSetFiles, then update the actual test "deploy with setFiles" by changing the line 
`AndRun("helm --kube-context kubecontext upgrade skaffold-helm examples/test -f skaffold-overrides.yaml --set-string image=docker.io:5000/skaffold-helm:3605e7bc17cf46e53f4d81c4cbc24e5b4c495184 --set-file value=/some/file.yaml --kubeconfig kubeconfig").`
to reflect what the filename you added should expand to

I hope that helps! If you don't feel comfortable doing that, we can always make edits on your branch too

**Comment by kri5** [comment]
@MarlonGamez I updated the PR with tests. Thanks for the hints.

Feel free to comment.

**Comment by kri5** [comment]
@MarlonGamez If you have any ideas on why the ci build is not passing, i'll happily takes advices :)

**Comment by MarlonGamez** [comment]
Looks like it was just a bit of flakiness on windows unit tests. I reran it and it passed :) Just need to wait on the kokoro build now

**Review by MarlonGamez — APPROVED** [review]
This looks good to me! Thanks for being patient with us and including our requests :)

**Pull request merged**
