### PR TITLE
Move context validation to build phase so as to not interfere with deploy

### PR DESCRIPTION
**Pull request by briandealwis**
**Related**: #4491
Reverts: #4492
Fixes:  #4616

**Description**

Revert the validation for artifact contexts (workspaces) from introduced by #4492 for the reasons outlined in #4616.  Instead perform artifact context checks before undertaking a build.  

Since this error is unexpected, we just report the first artifact with an error rather than collect all errors.

```console
$ skaffold build
image "leeroy-web" context "foo-leeroy-web" does not exist
```

### CODE REVIEW

**Comment by gsquared94** [comment]
#4616 seems to be a very fundamental scenario for deploy; didn't we have any integration test for that? Can we add one?

**Comment by briandealwis** [comment]
Funnily enough it takes a bit of work to create an IT around this as you still need the kubernetes manifests to be deployed.

**Comment by briandealwis** [comment]
PTAL @gsquared94

**Review by gsquared94 — APPROVED** [review]
LGTM!

**Pull request merged**
