### PR TITLE
feat: Add Sprig template functions

### PR DESCRIPTION
**Pull request by briantopping**
**Description**

Add Sprig template functions. This allows parameterizing with functions such as [`date`](http://masterminds.github.io/sprig/date.html)

**User facing changes (remove if N/A)**

Additional functions are available to templated fields. No other changes are made to existing APIs or UX.

Tests for the functions are comprehensively provided upstream.

### CODE REVIEW

**Comment by briantopping** [comment]
cc: @aaron-prindle @ericzzzzzzz

**Comment by briantopping** [comment]
Hi @ericzzzzzzz, I missed the test failure before, should be fixed. Apologies for the noise.

**Comment by ericzzzzzzz** [comment]
> Hi @ericzzzzzzz, I missed the test failure before, should be fixed. Apologies for the noise.

no worries, I just re-triggered the build.

**Comment by briantopping** [comment]
@ericzzzzzzz I guess I am learning what has to happen the hard way on my first PR. Doesn't seem I can add that label to kick off a build.

**Review by ericzzzzzzz — APPROVED** [review]

**Pull request merged**
