### PR TITLE
chore: Skipping `TestBuildKanikoInsecureRegistry` pending investigation

### LINKED ISSUE #7121: [Test Failure] TestBuildKanikoInsecureRegistry is timing our consistently
The latest version of kaniko is broken due to auth issues. 

1) Pinning our test to older version to see if it fixes the Test. 
   - It did not fix the test. 

`TestBuildKanikoInsecureRegistry` needs more investigation. Skipping it for now.

### PR DESCRIPTION
**Pull request by tejal29**
Related to #7121 

I tried downgrading the kaniko version to older v1.6.0, however it did not work. 

Skipping this test pending investigation.

### CODE REVIEW

**Review by gsquared94 — APPROVED** [review]

**Comment by tejal29** [comment]
The kaniko job still timed out. I am thinking we need to increase the timeout.

**Comment by tejal29** [comment]
increasing timeout to 90 mins.

**Comment by MarlonGamez** [comment]
@tejal29 looks like the kokoro status was "canceled"? But seems like the tests are working properly

**Comment by MarlonGamez** [comment]
@tejal29 any idea as to why this might still be timing out ?

**Pull request closed without merging**
