### PR TITLE
Handle broken symlink when watch files

### PR DESCRIPTION
**Pull request by jsturtevant**
This is a fix for  #970.  `dep ensure` does some clean up on files which leaves behind a broken symlink in the vendor folder.  By using `os.Lstat()`  the watcher code doesn't die on the broken symlink.  Added a test case for a broken symlink.

### CODE REVIEW

**Comment by dgageot** [comment]
lgtm (once the CLA is signed)

**Comment by mikekamornikov** [comment]
I have a similar issue: 
`listing files: unable to stat file ../../../source file @go_image_base/image/000.tar.gz: lstat ../../../source file @go_image_base/image/000.tar.gz: no such file or directory`

And it turns out it works just fine on the latest master.

**Comment by mikekamornikov** [comment]
probably this one fixes it for me - https://github.com/GoogleContainerTools/skaffold/commit/a237ee7beb465fa9f7eea49b9dabc556ff4db852

**Comment by jsturtevant** [comment]
Closing.  The approval took some time and this has been fixed by a separate fix before it came back.

**Comment by dgageot** [comment]
@jsturtevant Sorry it took so long. I'm happy the issue is fixed though!

**Pull request closed without merging**
