### PR TITLE
Add option to not tail logs in dev mode

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by dgageot** [comment]
@MrTrustor Can you TAL and see if this solved your issue?

**Comment by MrTrustor** [comment]
It does solve my issue, but the "true" default value is not taken into account. I have to do `skaffold dev --tail=true` to see the logs.

**Comment by dgageot** [comment]
I’ll how to fix that tomorrow

**Comment by dgageot** [comment]
Ok, so different default values for the same flag is not possible with cobra. See https://github.com/spf13/viper/issues/233

**Comment by MrTrustor** [comment]
@dgageot My (ugly) patch in #1029 did work. What do you want to do?

**Comment by dgageot** [comment]
@MrTrustor I'm LGTMing your PR (#1029). Closing this one!

**Pull request closed without merging**
