### PR TITLE
docs: add missing ref to BuildpackVolume (WIP)

### PR DESCRIPTION
**Pull request by tomas-mota**
Fixes:  #7020

### CODE REVIEW

**Review by briandealwis — CHANGES_REQUESTED** [review]
These JSON Schema files are generated by a script and so these changes will be overwritten.  Can you take a look at the script in https://github.com/GoogleContainerTools/skaffold/tree/main/hack/schemas?

**Comment by MarlonGamez** [comment]
> These JSON Schema files are generated by a script and so these changes will be overwritten. Can you take a look at the script in [https://github.com/GoogleContainerTools/skaffold/tree/main/hack/schemas](https://github.com/GoogleContainerTools/skaffold/tree/main/hack/schemas?rgh-link-date=2022-03-23T15%3A54%3A55Z)?

@briandealwis My first guess is that this is happening because the underlying type of `volume` is `*[]BuildpackVolume`, with this being the only pointer to an array in our config. Do you know if there's a reason that this needs to be a `*[]`

**Comment by MarlonGamez** [comment]
@tomas-mota I investigated the idea above and changing the type seemed to work. After making the necessary changes and running `make generate-schemas`, it properly adds the necessary json. 

Here's a link to a commit with the changes:
https://github.com/MarlonGamez/skaffold/commit/6753f838b7cb01b67b86726c0be75356aa76d508

**Review by tejal29 — APPROVED** [review]

**Comment by tomas-mota** [comment]
Realized I need to make a v2beta29, right? Will get to that tomorrow

**Pull request closed without merging**
