### PR TITLE
fix: add v2 to module path

### PR DESCRIPTION
**Pull request by sethrylan**
Fixes: #8161 

**Description**

This PR updates the module path to include `v2`.

Go modules treat v0 and v1 with relaxed versioning requirements. Incrementing to v2 asks [for a new module path](https://go.dev/doc/modules/version-numbers#major-version):

> A major version update to a number higher than v1 will also have a new module path. That’s because the module path will have the major version number appended

In skaffold's case, we need `module github.com/GoogleContainerTools/skaffold/v2 v2.0.2` so that `go get github.com/GoogleContainerTools/skaffold/v2@v2.0.2` will work.

Go intends for the module path to prevent unintentionally upgrading to a new major version. By adding the version to the module path, developers must deliberately import breaking changes.

I realize that few projects have this issue, because few import the skaffold packages. We do have such a project, and we're looking forward to importing the v2 packages.

### CODE REVIEW

**Comment by sethrylan** [comment]
> Merging [#8169](https://codecov.io/gh/GoogleContainerTools/skaffold/pull/8169?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GoogleContainerTools) (https://github.com/GoogleContainerTools/skaffold/commit/1db43b192caabf976f5165b2d8cac53e071a90c9) into [main](https://codecov.io/gh/GoogleContainerTools/skaffold/commit/290280e8c6c19231e9ed5b5c027f2c01d22f75be?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GoogleContainerTools) (https://github.com/GoogleContainerTools/skaffold/commit/290280e8c6c19231e9ed5b5c027f2c01d22f75be) will decrease coverage by 4.24%.

Codecov seems to be comparing to an old commit (290280e was [merged](https://github.com/GoogleContainerTools/skaffold/pull/6534) over a year ago). Other PRs show the same coverage decrease, so I think this is not related to my module path change.

@aaron-prindle, is there anything else I need to do for this PR?

**Comment by aaron-prindle** [comment]
@sethrylan thanks for flagging and submitting this.  I think the PR is good as is w/ no changes, I am holding off merging until after our next minor release - `v2.1.0` ~Dec 7th.   As this touches so many files and I want extra time to make sure that no one downstream somehow was relying on our incorrect convention prior

**Comment by sethrylan** [comment]
> I plan on merging this right after Dec 7th, will that work for your team?

Yes, that works great. Thank you for the quick review, and let me know if there's anything else for this PR.

**Comment by sethrylan** [comment]
@aaron-prindle, I've merged the latest commits from main to this branch, and updated the `.bat` file I missed. It might be good to re-run CI to validate.

**Comment by aaron-prindle** [comment]
Sorry for the delay, our next release was pushed until tomorrow - 12/14/2022.  Will get to this by end of this week, sorry for any inconvenience

**Review by aaron-prindle — APPROVED** [review]
Our release is still waiting on some high priority fixes, I've been manually testing this locally and reviewed all of the files touched and things look good. It should be safe to merge now from my testing.  Merging now

**Comment by aaron-prindle** [comment]
Thanks for the PR @sethrylan, out of curiosity how is your team using the skaffold go module currently?  Any insights there might help us to better support the use case, thanks!

**Comment by sethrylan** [comment]
Thanks so much @aaron-prindle!

There are two ways we use the module:
* We import the schema packages to auto-generate a SkaffoldConfig and output the yaml file. Our projects have many kustomize overlays, so this is a convenience command to auto-generate those sections of the `skaffold.yaml`.
* I also want to use the module to solve another issue. Today, we use a skaffold shim; it installs the version that each project needs and updates the path. This allows us to pin skaffold versions in shared environments, but relies on scripts that run in local, remote and CI. Over the last few months, we've added more features to this shim to support our dev workflow. For example, checking if a k8s cluster exists, and starting/creating it if needed, or setting `SKAFFOLD_TRIGGER` based on context. Our next steps are to use the skaffold module to create a more opinionated tool, optimized for our workflows. I would appreciate any ideas you have about this.

**Pull request merged**
