### PR TITLE
Make it possible to disable auto-sync 

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes: #4806 

**Description**
Turn the `sync.auto` to a boolean.

**User facing changes (remove if N/A)**
- auto-sync can now be disabled with `sync.auto = false` on the respective artifacts

### CODE REVIEW

**Comment by loosebazooka** [comment]
There's some docs and code in examples that use auto:{}
for jib specifically: (/integration)/examples/jib-syc

**Comment by briandealwis** [comment]
@loosebazooka 5f29e27 fixed the `auto:{}` in `integration/examples/jib-sync`, so they'll come through on the next release.

**Comment by loosebazooka** [comment]
oh weird, I must have clicked on the commit or something

**Comment by loosebazooka** [comment]
Looks fine to me, what happens when we need to configure auto in the future? should buildpacks not automatically enable sync?

**Review by loosebazooka — APPROVED** [review]

**Comment by briandealwis** [comment]
Auto sync is now enabled by default for buildpacks (#4656). Disabling requiring specifying a manual sync rule. Oops, I didn't update the docs!

**Comment by loosebazooka** [comment]
How does that interact with the "one of" parsing of yaml? I'm not sure I remember what happens if the user injects some manual sync into the buildpacks artifact configuration?

**Comment by briandealwis** [comment]
The `oneOf` is [only checked at parse time](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/yamltags/tags.go#L167): it has no effect on the underlying Go structs.

The auto-sync enablement happens as port-processing step, and only happens when there are no manual or inferred rules.

**Review by gsquared94 — APPROVED** [review]

**Pull request merged**
