### PR TITLE
Support for replacing image names in env vars

### PR DESCRIPTION
**Pull request by ajbouh**
Specifically env vars that end with _IMAGE

### CODE REVIEW

**Comment by mattfysh** [comment]
This will be very handy for kicking off jobs needing the skaffold-tagged image names. For now, a workaround is to annotate the pod that needs the image name, using key "image". It will match and get picked up by the replacer

**Comment by ajbouh** [comment]
I don't know how bad the rebase will be so I'm reluctant to invest further in this PR. Also unclear what the appetite for merging this is. Thoughts on these points?

**Comment by tejal29** [comment]
I think we are thinking of Adding Env Based tagger as part of #922 for `skaffold build` images.
See https://github.com/GoogleContainerTools/skaffold/issues/922#issuecomment-474710200 for more details.

I agree, lets close this PR for now and revisit if this is needed once #922 is resolved.

**Comment by ajbouh** [comment]
What is env based tagger? That sounds like a way to use environment variables to decide on the docker image tag?

If so, that's unrelated to what this PR does

**Comment by tejal29** [comment]
Yes it is. Since you mentioned you don't want to invest further at this time, I suggesting revisiting this once build changes are in. 
Feel free to re-open this if you want to get this in before that.

**Pull request closed without merging**
