### PR TITLE
add flag --survey to set to set/unset disable survey prompt

### PR DESCRIPTION
**Pull request by tejal29**
Relates to #3011 
Shd merge before #3733

In this PR, add a hidden flag `--survey` to set `disable-prompt` field in upcoming PRs

Changes:
1. Use `FieldByIndex` instead of `FieldByName` to set, unset values

Testing Done:

```
mv ~/.skaffold/config ~/.skaffold/config_old

make && ./out/skaffold config set  --survey --global disable-prompt true
set global value disable-prompt to true
tejaldesai@@skaffold (add_survey_set)$ cat ~/.skaffold/config 
global:
  survey:
    disable-prompt: true
kubeContexts: []
tejaldesai@@skaffold (add_survey_set)$ 
```

```
 ./out/skaffold config set  --survey  disable-prompt true
set value disable-prompt to true for context gke_tejal-test_us-central1-a_dump
tejaldesai@@skaffold (add_survey_set)$ cat ~/.skaffold/config 
global:
  survey:
    disable-prompt: true
kubeContexts:
- kube-context: gke_tejal-test_us-central1-a_dump
  survey:
    disable-prompt: true
tejaldesai@@skaffold (add_survey_set)$ 
```

```
./out/skaffold config unset  --survey  disable-prompt
unset value disable-prompt for context gke_tejal-test_us-central1-a_dump
tejaldesai@@skaffold (add_survey_set)$ cat ~/.skaffold/config 
global:
  survey:
    disable-prompt: true
kubeContexts:
- kube-context: gke_tejal-test_us-central1-a_dump
  survey: {}
```

```
./out/skaffold config unset  --survey  --global disable-prompt
unset global value disable-prompt
tejaldesai@@skaffold (add_survey_set)$ cat ~/.skaffold/config 
global:
  survey: {}
kubeContexts:
- kube-context: gke_tejal-test_us-central1-a_dump
  survey: {}
tejaldesai@@skaffold (add_survey_set)$ 


```

### CODE REVIEW

**Comment by nkubala** [comment]
just trying this out, I think this would be a lot more intuitive if we handled the global config `git` style, e.g. `git config set user.name nick`

so for the survey this would be `skaffold config set survey.disablePrompt true`. how doable do you think that would be?

**Comment by tejal29** [comment]
> just trying this out, I think this would be a lot more intuitive if we handled the global config `git` style, e.g. `git config set user.name nick`
> 
> so for the survey this would be `skaffold config set survey.disablePrompt true`. how doable do you think that would be?

Sorry, `survey.disablePrompt` was my first choice but it was a very uninfeasible and messy due to recursive parsing of all ['survey', 'disable-Prompt`]  


I looked into what `kubectl` does and it has separate commands to set specific structs and went with that approach
```
kubectl config set --help
 set-cluster     Sets a cluster entry in kubeconfig
  set-context     Sets a context entry in kubeconfig
  set-credentials Sets a user entry in kubeconfig
```
It supports both,
```
  # Set only the server field on the e2e cluster entry without touching other values.
  kubectl config set-cluster e2e --server=https://1.2.3.4

``` 
```
kubectl config set clusters.e2e.server https://1.2.3.4
```
and we can add support for this later.

WDYT?

**Comment by tejal29** [comment]
@nkubala can you take a look again after our discussion?

**Comment by nkubala** [comment]
@tejal29 sounds good. I opened https://github.com/GoogleContainerTools/skaffold/issues/3810 to track

**Pull request merged**
