### PR TITLE
alternative fix for #481

### PR DESCRIPTION
**Pull request by jstrachan**
which uses 2 separate environment variables

adds a test to show it working

### CODE REVIEW

**Comment by jstrachan** [comment]
@dlorenc agreed - I've raised a separate issue to track the docs stuff as there's a number of env vars / expressions around that need docs: https://github.com/GoogleContainerTools/skaffold/issues/498

**Comment by dlorenc** [comment]
LGTM.

**Comment by dlorenc** [comment]
@r2d4 do you want to merge this now or after Kubecon?

**Comment by afrittoli** [comment]
Thanks! This is really useful.

**Pull request merged**
