### PR TITLE
Fix issue with 100% CPU usage in logs.go.

### PR DESCRIPTION
**Pull request by d11wtq**
Resolves: https://github.com/GoogleContainerTools/skaffold/issues/531
See also: https://github.com/kubernetes/client-go/issues/12

There is an issue in which the Pods watcher gets into a infinite tight
loop and begins consuming 100% of the CPU. This happens after skaffold
dev has been running for a while (~30 mins) and once it starts, it
doesn't stop.

The issue was narrowed down by @ajbouh to the event polling loop in
`logs.go`, which was not checking if the `ResultChan()` is closed or not.
Kubernetes actually closes the connection after a timeout (default is in
the range of 30-60 mins according to the related issue linked to above).
In this case, the intended solution is to start the watcher again.

This refactors the polling into two nested loops. One to start (and
restart) the Pods watcher itself and another to receive and process the
events from the watcher. If the `ResultChan()` is closed, the entire
watcher loop is restarted and log tailing continues.

There is a subtle difference in error handling as a result of this
change. Previously any error returned from `client.Pods("").Watch()`
would be immediately returned from the `Start()` func in `logs.go`. This
is no longer possible since the watcher is initialized in the goroutine
started by that func. As such, in the case the watcher cannot be
initialized, we simply log the error and stop tailing logs. Open to
suggestions as to be a better way to handle this error. Retrying in a
tight loop seems potentially problematic in the error scenario.

### CODE REVIEW

**Comment by d11wtq** [comment]
I signed it!

**Comment by d11wtq** [comment]
Is that failing integration test correct? It looks like some kind of CI environment config issue https://ci.appveyor.com/project/r2d4/skaffold/build/1.0.6

> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

**Comment by dgageot** [comment]
@d11wtq Can you try to rebase? that should fix the appveyor bug. You should also sign the CLA with the email you've used for the commits.

**Comment by d11wtq** [comment]
Thanks @dgageot. I'm pretty sure I logged into Google with my @w3style.co.uk address used in the commits. Will try again.

**Comment by d11wtq** [comment]
ff945bc9-a49a-4815-b6e2-e8676b89b570
a2164d16-747c-441a-95ac-1e71c2ed48ab

Not sure what else I need to do here.

**Comment by dgageot** [comment]
@d11wtq I had to update the branch. Can you just confirm that you are ok with that?

**Comment by d11wtq** [comment]
I am cool with that 👍

**Pull request merged**
