### PR TITLE
pass --insecure-registry flag(s) to kaniko

### PR DESCRIPTION
**Pull request by tjk**
TODO
- [ ] run to see if this even solves the issue
- [x] add test

### CODE REVIEW

**Comment by nkubala** [comment]
@tjk have you tested this out to see if it fixes your issue?

**Comment by tjk** [comment]
@nkubala I'm still working on testing this... got stuck setting up helm in my k8s cluster to try to set up kaniko. Will continue when I have time.

@jimanvlad tested my patch (and it didn't work) fyi. (see https://github.com/GoogleContainerTools/skaffold/issues/1961).

**Comment by dgageot** [comment]
@tjk  Is this PR still active? I'd like to close stalled PRs so that we have a better idea of which PR needs a review. Feel free to reopen the discussion if you need help!

**Comment by dgageot** [comment]
I'm going to close this PR because of the lack of activity. I'm sorry we couldn't get this merged in. Please feel free to reopen, we'll be more that happy to help get this done!

**Pull request closed without merging**
