### PR TITLE
Skaffold helm deploy, add support for optional --timemout flag and --force flags

### PR DESCRIPTION
**Pull request by tjerkw**
This combines two pull requests for adding helm flags.

-- timeout flag for helm
Since we support --wait we should add --timeout too
https://github.com/GoogleContainerTools/skaffold/pull/1506

And the --force flag for helm.
https://github.com/GoogleContainerTools/skaffold/pull/1499

Updated docs.

### CODE REVIEW

**Comment by tjerkw** [comment]
@moustafab  can you sign the SLA?

**Comment by moustafab** [comment]
I signed it! The bot seems to be having an issue.

**Comment by moustafab** [comment]
@dgageot My org contact signed the agreement on 1/18, and I'm part of the google group. Let me know if I need to do anything

**Comment by tjerkw** [comment]
@moustafab  click this link to see if you signed it: https://cla.developers.google.com/

**Comment by moustafab** [comment]
confirmed @googlebot I hereby consent, as long as you merge sooner rather than later. 
@tjerkw Thanks for putting these together!

I need these for my team to be able to easily use this tool, and I'd rather not have to get everyone pulling from somewhere other than the main repository!

**Comment by tjerkw** [comment]
I signed it

**Comment by tjerkw** [comment]
I'm confused about the Google not. We both signed but it's still complaining.

**Comment by nkubala** [comment]
@tjerkw hmm, did you both sign the commit with the same email you have the CLA signed with? I've had this issue before where I accidentally signed the commit with my personal email.

**Comment by nkubala** [comment]
also, unfortunately you'll need a rebase now :(

**Comment by tjerkw** [comment]
As agreed here, lets use the Flags based approach:
https://github.com/GoogleContainerTools/skaffold/pull/1506

**Pull request closed without merging**
