### PR TITLE
Added local and s3 context support to kaniko build feature.

### PR DESCRIPTION
**Pull request by atugade**
Something I threw together to test our local and s3 build context when using kaniko as the build tool:

s3 example of skaffold.yaml
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: yourdockerhub/example-app
  kaniko:
    s3:
      bucket: yourbucket
    pullSecretName: docker-hub-creds
    env:
    - name: DOCKER_CONFIG
      value: /secret/
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_CONFIG_FILE
      value: /root/.aws/config
    volumes:
    - name: mycode
      hostPath: /path/to/your/build/context/
    - name: aws-creds
      secret: aws-creds
    volumeMounts:
    - name: mycode
      mountPath: /build/
    - name: aws-creds
      mountPath: /root/.aws
deploy:
  kubectl:
    manifests:
      - k8s-*
```

local dir example of skaffold.yml
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: yourdockerhub/example-app
    workspace: /path/to/your/build/context
  kaniko:
    localDir:
      path: /build/
    pullSecretName: docker-hub-creds
    env:
    - name: DOCKER_CONFIG
      value: /secret/
    volumes:
    - name: mycode
      hostPath: /path/to/your/build/context/
    volumeMounts:
    - name: mycode
      mountPath: /build/
deploy:
  kubectl:
    manifests:
      - k8s-*
```
I created two secrets:
```
kubectl create secret generic docker-hub-creds --from-file=/path/to/your/.docker/config.json
kubectl create secret generic aws-creds --from-file=/path/to/your/.aws/credentials
```

### CODE REVIEW

**Comment by vkartik97** [comment]
Hi @atugade 
Travis is failing at [`pkg/skaffold/docker/context.go:30:2: cannot find package "github.com/aws/aws-sdk-go/service/s3/s3manager" in any of:`](https://travis-ci.org/GoogleContainerTools/skaffold/jobs/427595362#L480).
Try adding Dependencies using [Dep](https://github.com/golang/dep).

**Comment by atugade** [comment]
I'll fix the unit tests.

**Comment by r2d4** [comment]
@priyawadhwa can you see how you can merge your changes with this?

**Comment by balopat** [comment]
@atugade friendly ping, are you planning to work on this or we can close it?

**Comment by balopat** [comment]
Closing for now due to lack of activity, @atugade we would still love to see the scoped down version for S3!

**Pull request closed without merging**
