### PR TITLE
Avoid aliasing in image configuration

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes: #5704

**Description**
In examining a debug trace, we discovered that the retrieved image configuration for the unchanged image was actually different:
- round 1:
  >    DEBU[0015] Retrieved local image configuration for gcr.io/gcloud-powershell-testing/nodejs-guestbook-frontend:latest@sha256:fdf561285af541e5db2483694966368287c1baced16f2c6180bcf06cfd328c06: {false false false [] <nil>  [node app.js] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_VERSION=12.22.1 YARN_VERSION=1.22.5 WRAPPER_VERBOSE=debug]  sha256:ce9a93883c04ba2b41e72a472b955dbaa171a00d7defe5c5b98ed280bd9d22cd map[] [] false false false  map[] /frontend map[] false false   []} 

- round 2 (notice the entrypoint now has an `--inspect=0.0.0.0:9229`)
  > DEBU[0131] Retrieved local image configuration for gcr.io/gcloud-powershell-testing/nodejs-guestbook-frontend:latest@sha256:fdf561285af541e5db2483694966368287c1baced16f2c6180bcf06cfd328c06: {false false false [] <nil>  [node --inspect=0.0.0.0:9229] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_VERSION=12.22.1 YARN_VERSION=1.22.5 WRAPPER_VERBOSE=debug]  sha256:ce9a93883c04ba2b41e72a472b955dbaa171a00d7defe5c5b98ed280bd9d22cd map[] [] false false false  map[] /frontend map[] false false   []} 

The problem is due to aliasing of underlying arrays when copying slices.  We retrieve the image manifest and configuration for the image from the local docker daemon:
https://github.com/GoogleContainerTools/skaffold/blob/01feff8c4dccaa6d76072abac1fe9ed6494da866/pkg/skaffold/debug/debug.go#L114

and then copy the values, but the slices and maps retain pointers to their underlying arrays:
https://github.com/GoogleContainerTools/skaffold/blob/01feff8c4dccaa6d76072abac1fe9ed6494da866/pkg/skaffold/debug/debug.go#L120-L129

This struct is then changed with new arguments values copied into the array:
https://github.com/GoogleContainerTools/skaffold/blob/01feff8c4dccaa6d76072abac1fe9ed6494da866/pkg/skaffold/debug/transform_nodejs.go#L196-L203

The solution here is to duplicate the arrays and maps taken from the image configuration.

### CODE REVIEW

**Comment by briandealwis** [comment]
Verified by hand with `skaffold debug --auto-build --auto-sync` in `examples/nodejs`.  Opened #5806 to make a test to verify this situation.

**Comment by tejal29** [comment]
If I  understand correctly, 
In round 2, the entry point should be `node app.js`  and then in the debug workflow round 2, the `--inspect 0.0.0.0:XXXX` should be added where `XXXX` is the right port. In this case the port is `9230` because `9229` was taken by backend in round 2?

**Comment by briandealwis** [comment]
That correct: on the second round, the image configuration appeared to already have an `--inspect` argument, and so the debug transforms didn't make a change.

An alternative solution would be to change the code, like `rewriteNodeCommandLine()`, to use `util.StrSliceInsert()` which does make a new copy of the provided slice.

**Review by nkubala — APPROVED** [review]
seems good to me, restarting a few CI jobs to see if we can get around the pesky rate limit

**Review by tejal29 — APPROVED** [review]

**Pull request merged**
