### PR TITLE
fix: dont update last-prompted if check-update is false

### PR DESCRIPTION
**Pull request by tomas-mota**
Fixes: #7051

**Description**
When check-update is set to false, the config property last-prompted was being updated even though the user is not prompted. This has been fixed.

**Notes**
Also removed a test regarding the survey prompt that was being ran as part of the update message unit tests (coverage not affected)

### CODE REVIEW

**Comment by briandealwis** [comment]
I think this looks reasonable — wdyt @tejal29?

**Comment by tejal29** [comment]
> I think this looks reasonable — wdyt @tejal29?

Agree. We did discuss on the issue opened for the same.

**Review by tejal29 — APPROVED** [review]

**Comment by tomas-mota** [comment]
The windows unit test falure looks like a flake, should we just re-run it @tejal29?

**Comment by tomas-mota** [comment]
Just ran 'go test -short -timeout 60s  ./pkg/skaffold/... ./cmd/... ./hack/... ./pkg/webhook/...' on a windows machine and all tests passed fine :/

**Pull request merged**
