### PR TITLE
Skaffold master -> main

### PR DESCRIPTION
**Pull request by briandealwis**
Update references to master to now point to main.

### CODE REVIEW

**Comment by tejal29** [comment]
Verification notes
```
hub pr checkout 6263

rm -rf docs/static/swaggerr

git grep master

Binary file hack/release-notes matches

```

**Review by tejal29 — COMMENTED** [review]
Can you verify if hack/release_notes binary needs to be rebuilt. 
See https://github.com/GoogleContainerTools/skaffold/pull/6263#issuecomment-884342852

**Comment by briandealwis** [comment]
`hack/release-notes` is a binary executable and shouldn't be committed! 😱

**Comment by tejal29** [comment]
> `hack/release-notes` is a binary executable and shouldn't be committed! 😱

Maybe it was mistake during v1.9.0?
https://github.com/GoogleContainerTools/skaffold/blob/main/hack/release-notes

**Comment by briandealwis** [comment]
I don't find any references to `master` in `hack/tools/vendor/github.com/corneliusweig/release-notes`.

**Review by tejal29 — CHANGES_REQUESTED** [review]
Please change examples/remote-multi-config-microservices to include `branch: main`
```
- git:
    repo: https://github.com/GoogleContainerTools/skaffold
    path: examples/multi-config-microservices/leeroy-app
    sync: false
- git:
    repo: https://github.com/GoogleContainerTools/skaffold
    path: examples/multi-config-microservices/leeroy-web
    sync: false
``

**Comment by briandealwis** [comment]
We don't need to do that @tejal29: the git repo code already uses main if master is not found.
https://github.com/GoogleContainerTools/skaffold/blob/8c34f1e734a962b988529cc6e6d3a662b001001a/pkg/skaffold/git/gitutil.go#L41-L43

**Comment by aaron-prindle** [comment]
Do we have any build/release webhooks (eg: cloudbuild, etc) that need to be changed on GCP (code/infra not directly in this repo)

**Review by aaron-prindle — COMMENTED** [review]
Do we have any build/release webhooks (eg: cloudbuild, etc) which target `master` that need to be changed on GCP (code/infra not directly in this repo)?  I don't believe so, just wanted to put this here in case something was there that watched `master`

**Review by tejal29 — APPROVED** [review]

**Comment by briandealwis** [comment]
@aaron-prindle I updated the GCB triggers already to support `master|main`
https://console.cloud.google.com/cloud-build/triggers?project=k8s-skaffold

**Review by aaron-prindle — APPROVED** [review]

**Comment by briandealwis** [comment]
Kokoro is being temperamental.  Committing since everything is green.

**Pull request merged**
