### PR TITLE
Revert helm 3.0 and 3.1 deployer changes.

### LINKED ISSUE #7582: skaffold debug error:  debug requires at least Helm 3.1
### Actual behavior
skaffold debug error: debug requires at least Helm 3.1 (current: 3.9.0)

### Information
I found the location of the code that reported the error 

deploy30.go

image

i can't understand what is the meaning of this if condition
 
- Skaffold version:  1.39

### PR DESCRIPTION
**Pull request by tejal29**
fixes #7582

### CODE REVIEW

**Comment by tejal29** [comment]
TODO: 
Verify, helm applications can be debugged.

**Review by aaron-prindle — APPROVED** [review]
LGTM

**Comment by tejal29** [comment]
Manual verification
```

LOCAL=true make
mkdir -p ./out
GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
	    go build -gcflags="all=-N -l" -tags "release " -ldflags "-X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.version=v1.39.0-2-g59c5b8972 -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.buildDate=2022-06-24T12:43:49Z -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitCommit=59c5b8972622512c128e4bd13efe76fad7eb66de -s -w " -o out/skaffold github.com/GoogleContainerTools/skaffold/cmd/skaffold
codesign --force --deep --sign - out/skaffold
```

```
➜  skaffold git:(fix/v1.39.1) ✗  helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```
```
➜  skaffold git:(fix/v1.39.1) ✗ cd examples/helm-deployment
➜  helm-deployment git:(fix/v1.39.1) ✗ ls
Dockerfile    README.md     charts        main.go       skaffold.yaml
```
```
➜  helm-deployment git:(fix/v1.39.1) ✗ ../../out/skaffold debug -d gcr.io/tejal-gke1
Listing files to watch...
...

Waiting for deployments to stabilize...
 - deployment/skaffold-helm is ready.
Deployments stabilized in 3.541 seconds
Press Ctrl+C to exit
Not watching for changes...
[skaffold-helm] API server listening at: [::]:56268
...
```

**Comment by tejal29** [comment]
Before this change: 

`helm debug fails1


```
➜  helm-deployment git:(main) ✗ git checkout v1  
Switched to branch 'v1'
Your branch is up to date with 'origin/v1'.
```
```
➜  skaffold git:(v1) ✗ LOCAL=true make
GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
	    go build -gcflags="all=-N -l" -tags "release " -ldflags "-X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.version=v1.39.0 -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.buildDate=2022-06-24T12:51:19Z -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitCommit=73c46de08489140e8c034407a136c7491dd073d8 -s -w " -o out/skaffold github.com/GoogleContainerTools/skaffold/cmd/skaffold
codesign --force --deep --sign - out/skaffold
```

```
➜  skaffold git:(v1) ✗ cd examples/helm-deployment
➜  helm-deployment git:(v1) ✗ ../../out/skaffold debug -d gcr.io/tejal-gke1
Listing files to watch...
 - skaffold-helm
Generating tags...
 - skaffold-helm -> gcr.io/tejal-gke1/skaffold-helm:v1.39.0
Checking cache...
 - skaffold-helm: Found. Tagging
Tags used in deployment:
 - skaffold-helm -> gcr.io/tejal-gke1/skaffold-helm:v1.39.0@sha256:2d089ef0cb251709a1b155f289d2648ef32f7735dc7bb2ea67fd2769b45e0335
Starting deploy...
Cleaning up...
Error: uninstall: Release not loaded: skaffold-helm: release: not found
WARN[0008] deployer cleanup:exit status 1                subtask=-1 task=DevLoop
deploying "skaffold-helm": debug requires at least Helm 3.1 (current: 3.5.4)
➜  helm-deployment git:(v1) ✗ 

```

**Pull request merged**
