### PR TITLE
Support ko image references

### PR DESCRIPTION
**Pull request by halvards**
**Description**
[`ko`](https://github.com/google/ko) supports replacing `image` manifest fields with the image names
and digests of the built images. For this to work, the `image` field
must contain the import path of the Go binary, [prefixed by `ko://`](https://github.com/google/ko/tree/v0.6.0#what-gets-built).
The prefix was optional prior to ko v0.6.0. Starting from v0.6.0,
[the prefix is mandatory](https://github.com/google/ko/releases/tag/v0.6.0).

This change allows Skaffold to use manifests containing `ko` image
references, including those that use the prefix. Skaffold replaces the
image name as expected when using `ko` via a custom `buildCommand`.

It also handles Go import paths containing uppercase characters, e.g.
`github.com/GoogleContainerTools/skaffold/cmd/skaffold`, by lowercasing them.

This means `ko` users can start using Skaffold without making changes
to their manifests, and it allows these users to use both `ko` via
Skaffold custom builder, and `ko` standalone (without Skaffold),
side-by-side.

**Related**: #1958, #4098

**User facing changes**
Updates the custom builder `ko` example to v0.6.0, and to use a `ko` image reference.

**Follow-up Work**
First-class support for `ko` would be great 😄

### CODE REVIEW

**Comment by MarlonGamez** [comment]
Hi @halvards , thanks for opening this PR! Things look good to me :) Thanks for updating the example to match the changes.
I'll run kokoro for this and if everything is good I think this should be good to go in

**Comment by briandealwis** [comment]
@MarlonGamez I think we should hold off until @nkubala is back.  It seems odd to embed specific tool strings that we don't directly support.

**Comment by MarlonGamez** [comment]
@briandealwis yeah, that makes sense. I'll label it as do-not-merge for now then

**Comment by tejal29** [comment]
@nkubala would you be able to take a look at this.

**Review by nkubala — APPROVED** [review]
sorry for the late reply on this one, talked with @jonjohnsonjr just to understand more of what's going on here and this seems fine. obviously it's not ideal to be hardcoding strings in like this, but because of the way we parse image references in skaffold our hands are sort of tied. `ko` treats github paths as image references, and even though they're technically not, they parse correctly with `docker.ParseReference`. the `ko://` prefix unfortunately causes this to choke, so short of reworking our image reference parsing this is the best option.

because of the way `ko`'s watcher works, first class support in skaffold is a whole different problem entirely :) it's an awesome way to build go apps though, so even though we don't "natively" support it in skaffold i think it's fine to merge this fix in the interim.

**Comment by halvards** [comment]
Thanks all, and yes sorry for not providing more context up front on the import path/image reference parsing issue!

On the topic of watching, I was thinking that any further integration of ko into skaffold could use skaffold's watch implementation, rather than the one in ko? Maybe a discussion for another thread.

**Comment by nkubala** [comment]
@halvards definitely a discussion worth having, but this thread is probably too low visibility to get it any traction :) feel free to open another issue here or on the ko repo to further discuss

**Pull request merged**
