### PR TITLE
Update jib to 2.7.1

### PR DESCRIPTION
**Pull request by loosebazooka**
Update examples and testdata for latest jib release.

### CODE REVIEW

**Comment by chanseokoh** [comment]
FYI https://github.com/GoogleContainerTools/skaffold/pull/5119#issuecomment-741950663

But should be OK.

**Review by chanseokoh — APPROVED** [review]

**Comment by loosebazooka** [comment]
I vaguely recall some comment to the contrary, but I'll just follow the latest comment just to be sure... I'll undo the changes in examples.

**Review by briandealwis — APPROVED** [review]
Thanks!

**Review by briandealwis — COMMENTED** [review]
We can change the `examples` too since they shouldn't cause break the latest version of Skaffold.

**Comment by briandealwis** [comment]
Just read @tejal29's comment.  Will bring it up for discussion.

**Pull request merged**
