### PR TITLE
Automated fuzzing on Fuzzit

### PR DESCRIPTION
**Pull request by bookmoons**
Integrates with [Fuzzit](https://fuzzit.dev/) for automated fuzzing. Proposed in #2670.

Under this setup Travis runs fuzzing on every build. It runs a fuzz regression test locally of past crashes and submits to Fuzzit for a full fuzzing run. The build ends as soon as the fuzzing run is in the queue. Fuzzit emails when it finds crashes.

This tries to fuzz the suggested targets plus some other identified parsers. Targets are:
* `control-api-http` - HTTP requests to the control API server.
* `control-api-tcp` - Binary requests to the control API server.
* `parse-config` - Fuzz the config parser.
* `parse-reference` - Fuzz the Docker image reference parser.

There's a JDWP specification parser in `pkg/skaffold/debug` that seems suitable for fuzzing. It's tough to get at because it's a private function. If you think it's worth fuzzing exposing it would make it possible.

A `skaffold` org is preconfigured on Fuzzit. If whoever will be administering [signs in](https://fuzzit.dev/) to create an account, I can get you added to the org.

Thank you for considering.

### CODE REVIEW

**Comment by bookmoons** [comment]
@googlebot signed it

**Comment by bookmoons** [comment]
@dominikh Hi, I built on your good work for this PR. The googlebot is asking for consent to have your commits merged. Would you mind looking at it?

**Comment by bookmoons** [comment]
I see there's a strange error in the build. A type error even though the types are identical.

```
/home/travis/gopath/src/skaffold/pkg/skaffold/docker/auth.go:69:39: cannot use cf (variable of type *configfile.ConfigFile) as *configfile.ConfigFile value in argument to gcp.AutoConfigureGCRCredentialHelper
```

Not sure what that's about, it works locally. Will be looking into this.

**Comment by dominikh** [comment]
@googlebot I consent.

**Comment by bookmoons** [comment]
Thanks @dominikh.

**Comment by bookmoons** [comment]
Applied the Go modules approach from https://github.com/dvyukov/go-fuzz/issues/195#issuecomment-523526736 to get this working. Thanks @mvdan for the pattern.

This is ready for review.

**Comment by balopat** [comment]
This looks good but I'm hesitant to add 8 more minutes to our feedback loop. Can you please change it to a job instead of a stage so at least it can run in parallel with the other jobs?

**Comment by bookmoons** [comment]
Will do, thanks for looking at it.

**Comment by bookmoons** [comment]
Rebased this and converted the fuzz stages to jobs. I'll check back to see how the build goes.

If you'd like to [sign in](https://fuzzit.dev/) to Fuzzit to make an account I can add you to the org. Then final setup is like this:
* In Fuzzit, switch to the skaffold org with the dropdown at the top.
* In settings grab an API key.
* In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.

**Comment by dgageot** [comment]
@balopat do you think we should merge this (when it's rebased)?

**Comment by balopat** [comment]
I'm not convinced. One thing is the slowness of the test, the other is that most of the test code seems to be HTTP specific instead of Skaffold's test code. It feels like this kind of code should live in a fuzz-http library or similar...I'm not sure I want to maintain this.

**Comment by dgageot** [comment]
@balopat I agree. I'm sorry @bookmoons but I think maintaining that would cost us more that it brings.

**Comment by balopat** [comment]
Sounds good. Apologies for dragging this out this long. Closing.

**Pull request closed without merging**
