### PR TITLE
Update build_deps versions to latest

### PR DESCRIPTION
**Pull request by briandealwis**
- image based on ubuntu 18.04
- helm to 3.3.4
- kubectl 1.16.15
- kustomize to 3.8.5
- container-structure-test to 1.9.1
- kind to 0.9.0
- k3d to 3.1.3
- gcloud to 314.0.0
- bazel to 3.6.0
- docker to 19.03.13
- openjdk 11
- golang 1.15

### CODE REVIEW

**Review by MarlonGamez — APPROVED** [review]
Seems good to me 👍🏼

**Comment by nkubala** [comment]
i'm a bit worried about the kubectl version getting bumped 5 minor versions....this could potentially break users with old k8s versions on their cluster.

maybe we should do this incrementally? or as @briandealwis mentioned offline, maybe let Cloud SDK do the kubectl installation for us since we're already installing it anyway?

**Comment by briandealwis** [comment]
Abandoning installing kubectl via gcloud: 46MB x 6 versions = 276MB :-(

**Comment by briandealwis** [comment]
Updated to track kubectl 1.16 to match the current default for the Cloud SDK.

**Review by nkubala — APPROVED** [review]

**Pull request merged**
