### PR TITLE
Allow for remote kustomize bases

### LINKED ISSUE #2082: Unable to use kustomize deploy with kustomize base coming from remote git repository
### Expected behavior

I should be able to run `skaffold -p airflow-dev  and get my deployment to work (in this case deploying airflow. Which is fully working when I do not use a git repo for the kustomize base).

### Actual behavior

I run `skaffold dev -p airflow-dev -v debug` and this error (not i have masked the actual domain and org as its an internal enterprise repo)

```
...
DEBU[0000] setting Docker user agent to skaffold-v0.28.0
INFO[0000] no config entry found for kube-context minikube
DEBU[0000] push value not present, defaulting to false because localCluster is true
FATA[0000] watching files for deployer: listing files: listing files: open local-dev/config/k8s-config/my-development/git@github.enterprise.com:ORG/local-development.git/base/config/k8s-config/kustomization.yaml: no such file or directory
```
### Information

- Skaffold version: version: v0.28.0
- Kustomize Version: `Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}`
- Operating system: MacOS 10.4 - using hombrew for all tools
- Kubernetes environnment: minikube v1.0.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config

profiles:
- name: airflow-dev
  deploy:
    kustomize:
      path: local-dev/config/k8s-config/airflow-development

- name: pod-dev
  deploy:
    kustomize:
      path: local-dev/config/k8s-config/pod-development
```

Contents of kustomize.yaml

```yaml
commonLabels:
    run_envrionrment: local-airflow-dev

bases:
  - git@github.enterprise.com:ORG/local-development.git/base/config/k8s-config/kustomization.yaml:

patches:
  - deployment-airflow-local-enviornment-settings.yaml
```
### Steps to reproduce the behavior

1. run: `skaffold dev -p airflow-dev -v debug`

### PR DESCRIPTION
**Pull request by jmcclell**
Fixes #2082 

Kustomize will error if it can't find a base dependency, so it's safe for
Skaffold to assume that any base file that does not exist locally is intended
to be a remote path that can be ignored since Skaffold can't monitor remote
paths for changes.

### CODE REVIEW

**Comment by jmcclell** [comment]
I've signed the CLA.

**Comment by jmcclell** [comment]
@balopat Sorry, I don't follow. Can you elaborate on "existing base case?" Thanks!

**Comment by jmcclell** [comment]
Added additional requested test case.

**Comment by matti** [comment]
but weren't bases just removed from kustomize?

**Comment by matti** [comment]
like they are replaced with ordered resources

**Comment by jmcclell** [comment]
@matti is apparently correct! I am not sure if remote resources are still supported, but this code will need to be modified to support that in the new version. Another issue can be opened for that, but here's the relevant documentation for the change: https://github.com/kubernetes-sigs/kustomize/blob/dc433e12fb7063c57fec74e3ee0a24587c8ca84b/docs/v2.1.0.md#field-changes--deprecations

**Comment by dgageot** [comment]
Could you open another issue. That would be awesome!

**Pull request merged**
