### PR TITLE
fix bug on deploying helm when sync is used

### PR DESCRIPTION
**Pull request by yoshwata**
## Explanation
When sync is set, the `skaffold deploy` command do not work for [this line](https://github.com/GoogleContainerTools/skaffold/blob/d89f07af7ceca9e21b050c43b46776a23b316188/pkg/skaffold/deploy/helm.go#L437). This code makes a string like `myimage:myimage`, and that never exists.

As the result, deployed pod's image can't be pulled, and `ImagePullBackOff` occurs.

I think there is no need to join tags for build result if there is no build( like `skaffold deploy`).

## Issue
https://github.com/GoogleContainerTools/skaffold/issues/2631

### CODE REVIEW

**Comment by tejal29** [comment]
Hi @yoshwata, Thank you for your contribution. Can you add more context or a debug logs of when you see this error?

You mentioned
> When sync is set, the `deploy` command do not work for

Are you changing a "sync-able" file ? Usually, sync should not trigger a build and deploy.

**Comment by yoshwata** [comment]
@tejal29 Thanks you for comments. I add about `ImagePullBackOff` that is the problem I'd like to solve. 

> Are you changing a "sync-able" file ? Usually, sync should not trigger a build and deploy.

Do you saying about `skaffold dev` command on this context? I'd like to fix about `skaffold deploy` command and I do not change any files when I do `skaffold deploy`

**Comment by yoshwata** [comment]
Hi @tejal29. I add logs and details more at [issue](https://github.com/GoogleContainerTools/skaffold/issues/2631).

**Comment by nkubala** [comment]
hey @yoshwata can you rebase?

**Comment by yoshwata** [comment]
The issue is closed, so I close this pr too.

**Pull request closed without merging**
