### PR TITLE
Implements setting environment variable in kaniko pod #3227

### PR DESCRIPTION
**Pull request by ErmakovDmitriy**
Relates to setting environment variable in kaniko pod #3227

Should merge after : https://github.com/GoogleContainerTools/skaffold/pull/3284

**Description**

Implements a possibility to configure custom environment variables using name-value, name-ConfigMap and name-Secret pairs.

**User facing changes**

Adds to pull request #3284 a posiibility to set EnvVars as described below

```yaml
build:
  cluster:
    envVars:
      - name: MY_ENV_VAR
        value: MY_ENV_VAR_VALUE
      - name: MY_ENV_VAR_2
        secret:
          name: kubernetes-secret-name
          key: secret-key
      - name: MY_ENV_VAR_3
        configMap:
          name: kubernetes-config-map
          key: config-map-data
```

**Before**

No possibility to set custom Env Vars

**After**

User can use key-value pairs, Secrets or ConfigMaps as a source for Env Vars.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Mentions any output changes.
- [ ] Adds documentation as needed: user docs, YAML reference, CLI reference.
- [ ] Adds integration tests if needed.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit test added.
- [ ] User facing changes look good.

**Release Notes**

- Skaffold config adds build#cluster#envVars section.

### CODE REVIEW

**Comment by dgageot** [comment]
Hi @ErmakovDmitriy I'm afraid kaniko code has changed a lot since then. Could you try to rebase your PR? If you can't, let me know, I might be able to continue your work

**Comment by ErmakovDmitriy** [comment]
Hi @dgageot 
I will try to do it at the weekend because I'm quite busy this week.

The same about pull #3284

**Comment by ErmakovDmitriy** [comment]
Hi @dgageot 
I made some changes to use Kubernetes API V1 packages for Volumes and VolumeMounts.
Unfortunately, I get Travis Integration test failure.

Here is the link to test https://travis-ci.com/GoogleContainerTools/skaffold/jobs/277179064

If I am not mistaken, all the failed tests are related to jib:

```
=== Failed Tests ===

integration/TestExpectedBuildFailures/jib_is_too_old

integration/TestExpectedBuildFailures

integration/TestDebug/kubectl

integration/TestDebug/kustomize

integration/TestDebug

integration/TestDiagnose/jib

integration/TestDiagnose/jib-multimodule

integration/TestDiagnose

integration/TestRun/jib

integration/TestRun
```

for instance:

```
time="2020-01-18T07:51:09Z" level=info msg="build output: Generating tags...\n - skaffold-jib -> gcr.io/k8s-skaffold/skaffold-jib:v1.2.0-445-g4c5f16d\nChecking cache...\n - skaffold-jib: time=\"2020-01-18T07:51:09Z\" level=warning msg=\"error checking cache, caching may not work as expected: getting hash for artifact skaffold-jib: getting dependencies for skaffold-jib: getting jib-maven dependencies: initial Jib dependency refresh failed: failed to get Jib dependencies: Running [/skaffold/integration/testdata/jib/mvnw jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 -Djib.maven-plugin-version=1.3.0 --non-recursive jib:_skaffold-files-v2 --quiet]\\n - stdout: \\n - stderr: Exception in thread \\\"main\\\" java.io.IOException: Server returned HTTP response code: 403 for URL: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.1/apache-maven-3.6.1-bin.zip\\n\\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)\\n\\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)\\n\\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)\\n\\tat org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)\\n\\tat org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)\\n\\tat org.apache.maven.wrapper.Installer.createDist(Installer.java:64)\\n\\tat org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)\\n\\tat org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)\\n: exit status 1\"\nError checking cache. Rebuilding.\nFound [kind-kind] context, using local docker daemon.\nBuilding [skaffold-jib]...\nException in thread \"main\" java.io.IOException: Server returned HTTP response code: 403 for URL: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.1/apache-maven-3.6.1-bin.zip\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)\n\tat org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)\n\tat org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)\n\tat org.apache.maven.wrapper.Installer.createDist(Installer.java:64)\n\tat org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)\n\tat org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)\ntime=\"2020-01-18T07:51:09Z\" level=fatal msg=\"build failed: building [skaffold-jib]: build artifact: maven build failed: exit status 1\"\n"

--- FAIL: TestExpectedBuildFailures (1.94s)

    --- FAIL: TestExpectedBuildFailures/jib_is_too_old (1.94s)

        build_test.go:140: build failed but for wrong reason
```

Could you take a look at the Travis Test log because I do not understand how my changes are related to the failed tests?

**Comment by dgageot** [comment]
@ErmakovDmitriy No worries, it's not related. There's an issue with the site we download Maven from. So all the Jib related tests are flakey today.

**Pull request merged**
