### PR TITLE
fix(lookupRemote): fixed lookup.go lookupRemote to compare remote and cached digests

### PR DESCRIPTION
**Pull request by idsulik**
Fixes: #9248 

**Description**
It is used to lookup remote images by tag and overwrite a cached item even if the digests are different, now it compares the digests

### CODE REVIEW

**Review by ericzzzzzzz — APPROVED** [review]

**Comment by bhack** [comment]
Do you plan a patch release?

**Comment by ericzzzzzzz** [comment]
#9301 to patch on 2.10

**Comment by noorul** [comment]
I still see this issue in 2.10.1

**Comment by idsulik** [comment]
Yes, sorry, I fixed it here https://github.com/GoogleContainerTools/skaffold/pull/9306 , waiting for merge

**Pull request merged**
