### PR TITLE
Integration tests tweaks

### PR DESCRIPTION
**Pull request by briandealwis**
We're seeing a number of integration test failures in `TestDevPortForwardDeletePod`, `TestDebugEventsRPC_StatusCheck`, and `TestDebugEventsRPC_NoStatusCheck`.

This PR:
  - runs these tests with `skaffold -vdebug` to get more fulsome error logs from Skaffold
  - changes the Jib-based debug tests to use the `gcr.io/google-appengine/openjdk:8` to avoid hitting Docker Hub
  - fixes a mispelling

### CODE REVIEW

**Comment by gsquared94** [comment]
I tried to look at the integration test failures. I think it's primarily caused by the `k3d` cluster `image load` command. I found some related issue (https://github.com/rancher/k3d/issues/119) where repeatedly loading images causes some cluster instability. From the failure logs, the image load times-out whereas locally it takes 0.5s on my machine.

**Comment by briandealwis** [comment]
I wonder if Kind suffers from the same thing.

Oh!  I wonder if it's possible that the cluster is running out of resources.

**Comment by briandealwis** [comment]
([`kind integration partition 0`](https://api.travis-ci.com/v3/job/469254454/log.txt)) failed with Docker Hub error trying to pull `alpine`:
```
=== RUN   TestDevPortForwardDeletePod
time="2021-01-06T18:14:20Z" level=info msg="[skaffold build --default-repo gcr.io/k8s-skaffold]"
    helper.go:229: skaffold build: exit status 1, Generating tags...
         - leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:261b337
         - leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:261b337
         - base -> gcr.io/k8s-skaffold/base:261b337
        Checking cache...
         - leeroy-web: Not found. Building
         - leeroy-app: Not found. Building
         - base: Not found. Building
        Found [kind-kind] context, using local docker daemon.
        Building [base]...
        Sending build context to Docker daemon  2.048kB
        Step 1/3 : FROM alpine:3.10
        3.10: Pulling from library/alpine
        21c83c524219: Pulling fs layer
        21c83c524219: Retrying in 5 seconds
        21c83c524219: Retrying in 4 seconds
        21c83c524219: Retrying in 3 seconds
        21c83c524219: Retrying in 2 seconds
        21c83c524219: Retrying in 1 second
        21c83c524219: Retrying in 10 seconds
        21c83c524219: Retrying in 9 seconds
        21c83c524219: Retrying in 8 seconds
        21c83c524219: Retrying in 7 seconds
        21c83c524219: Retrying in 6 seconds
        21c83c524219: Retrying in 5 seconds
        21c83c524219: Retrying in 4 seconds
        21c83c524219: Retrying in 3 seconds
        21c83c524219: Retrying in 2 seconds
        21c83c524219: Retrying in 1 second
        21c83c524219: Retrying in 15 seconds
        21c83c524219: Retrying in 14 seconds
        21c83c524219: Retrying in 13 seconds
        21c83c524219: Retrying in 12 seconds
        21c83c524219: Retrying in 11 seconds
        21c83c524219: Retrying in 10 seconds
        21c83c524219: Retrying in 9 seconds
        21c83c524219: Retrying in 8 seconds
        21c83c524219: Retrying in 7 seconds
        21c83c524219: Retrying in 6 seconds
        21c83c524219: Retrying in 5 seconds
        21c83c524219: Retrying in 4 seconds
        21c83c524219: Retrying in 3 seconds
        21c83c524219: Retrying in 2 seconds
        21c83c524219: Retrying in 1 second
        21c83c524219: Retrying in 20 seconds
        21c83c524219: Retrying in 19 seconds
        21c83c524219: Retrying in 18 seconds
        21c83c524219: Retrying in 17 seconds
        21c83c524219: Retrying in 16 seconds
        21c83c524219: Retrying in 15 seconds
        21c83c524219: Retrying in 14 seconds
        21c83c524219: Retrying in 13 seconds
        21c83c524219: Retrying in 12 seconds
        21c83c524219: Retrying in 11 seconds
        21c83c524219: Retrying in 10 seconds
        21c83c524219: Retrying in 9 seconds
        21c83c524219: Retrying in 8 seconds
        21c83c524219: Retrying in 7 seconds
        21c83c524219: Retrying in 6 seconds
        21c83c524219: Retrying in 5 seconds
        21c83c524219: Retrying in 4 seconds
        21c83c524219: Retrying in 3 seconds
        21c83c524219: Retrying in 2 seconds
        21c83c524219: Retrying in 1 second
        3.10: Pulling from library/alpine
    panic.go:617: WARNING: Could not open the configuration file: [/root/.config/gcloud/configurations/config_default].
        ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
        Please run:
        
          $ gcloud auth login
        
        to obtain new credentials.
        
        If you have already logged in with a different account:
        
            $ gcloud config set account ACCOUNT
        
        to select an already authenticated account to use.
        unable to stream build output: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Please fix the Dockerfile and try again..
```

**Comment by briandealwis** [comment]
[`kind integration partition 1`](https://api.travis-ci.com/v3/job/469254455/log.txt) failing with `toomanyrequests` too:
```
=== RUN   TestDebug/helm
time="2021-01-06T18:25:56Z" level=info msg="[skaffold build --default-repo gcr.io/k8s-skaffold]"
    helper.go:229: skaffold build: exit status 1, Generating tags...
         - skaffold-helm -> gcr.io/k8s-skaffold/skaffold-helm:261b337
        Checking cache...
         - skaffold-helm: Not found. Building
        Found [kind-kind] context, using local docker daemon.
        Building [skaffold-helm]...
        Sending build context to Docker daemon  3.072kB
        Step 1/8 : FROM golang:1.12.9-alpine3.10 as builder
        1.12.9-alpine3.10: Pulling from library/golang
        9d48c3bd43c5: Already exists
        7f94eaf8af20: Pulling fs layer
        9fe9984849c1: Pulling fs layer
        cf0db633a67d: Pulling fs layer
        0f7136d71739: Pulling fs layer
        0f7136d71739: Waiting
        cf0db633a67d: Retrying in 5 seconds
        9fe9984849c1: Verifying Checksum
        9fe9984849c1: Download complete
        7f94eaf8af20: Download complete
        0f7136d71739: Retrying in 5 seconds
        7f94eaf8af20: Pull complete
        9fe9984849c1: Pull complete
        cf0db633a67d: Retrying in 4 seconds
        0f7136d71739: Retrying in 4 seconds
        cf0db633a67d: Retrying in 3 seconds
        0f7136d71739: Retrying in 3 seconds
        cf0db633a67d: Retrying in 2 seconds
        0f7136d71739: Retrying in 2 seconds
        cf0db633a67d: Retrying in 1 second
        0f7136d71739: Retrying in 1 second
        cf0db633a67d: Retrying in 10 seconds
        0f7136d71739: Retrying in 10 seconds
        cf0db633a67d: Retrying in 9 seconds
        0f7136d71739: Retrying in 9 seconds
        cf0db633a67d: Retrying in 8 seconds
        0f7136d71739: Retrying in 8 seconds
        cf0db633a67d: Retrying in 7 seconds
        0f7136d71739: Retrying in 7 seconds
        cf0db633a67d: Retrying in 6 seconds
        0f7136d71739: Retrying in 6 seconds
        cf0db633a67d: Retrying in 5 seconds
        0f7136d71739: Retrying in 5 seconds
        cf0db633a67d: Retrying in 4 seconds
        0f7136d71739: Retrying in 4 seconds
        cf0db633a67d: Retrying in 3 seconds
        0f7136d71739: Retrying in 3 seconds
        cf0db633a67d: Retrying in 2 seconds
        0f7136d71739: Retrying in 2 seconds
        cf0db633a67d: Retrying in 1 second
        0f7136d71739: Retrying in 1 second
        cf0db633a67d: Retrying in 15 seconds
        0f7136d71739: Retrying in 15 seconds
        cf0db633a67d: Retrying in 14 seconds
        0f7136d71739: Retrying in 14 seconds
        cf0db633a67d: Retrying in 13 seconds
        0f7136d71739: Retrying in 13 seconds
        cf0db633a67d: Retrying in 12 seconds
        0f7136d71739: Retrying in 12 seconds
        cf0db633a67d: Retrying in 11 seconds
        0f7136d71739: Retrying in 11 seconds
        cf0db633a67d: Retrying in 10 seconds
        0f7136d71739: Retrying in 10 seconds
        cf0db633a67d: Retrying in 9 seconds
        0f7136d71739: Retrying in 9 seconds
        cf0db633a67d: Retrying in 8 seconds
        0f7136d71739: Retrying in 8 seconds
        cf0db633a67d: Retrying in 7 seconds
        0f7136d71739: Retrying in 7 seconds
        cf0db633a67d: Retrying in 6 seconds
        0f7136d71739: Retrying in 6 seconds
        cf0db633a67d: Retrying in 5 seconds
        0f7136d71739: Retrying in 5 seconds
        cf0db633a67d: Retrying in 4 seconds
        0f7136d71739: Retrying in 4 seconds
        cf0db633a67d: Retrying in 3 seconds
        0f7136d71739: Retrying in 3 seconds
        cf0db633a67d: Retrying in 2 seconds
        0f7136d71739: Retrying in 2 seconds
        cf0db633a67d: Retrying in 1 second
        0f7136d71739: Retrying in 1 second
        cf0db633a67d: Retrying in 20 seconds
        0f7136d71739: Retrying in 20 seconds
        cf0db633a67d: Retrying in 19 seconds
        0f7136d71739: Retrying in 19 seconds
        cf0db633a67d: Retrying in 18 seconds
        0f7136d71739: Retrying in 18 seconds
        cf0db633a67d: Retrying in 17 seconds
        0f7136d71739: Retrying in 17 seconds
        cf0db633a67d: Retrying in 16 seconds
        0f7136d71739: Retrying in 16 seconds
        cf0db633a67d: Retrying in 15 seconds
        0f7136d71739: Retrying in 15 seconds
        cf0db633a67d: Retrying in 14 seconds
        0f7136d71739: Retrying in 14 seconds
        cf0db633a67d: Retrying in 13 seconds
        0f7136d71739: Retrying in 13 seconds
        cf0db633a67d: Retrying in 12 seconds
        0f7136d71739: Retrying in 12 seconds
        cf0db633a67d: Retrying in 11 seconds
        0f7136d71739: Retrying in 11 seconds
        cf0db633a67d: Retrying in 10 seconds
        0f7136d71739: Retrying in 10 seconds
        cf0db633a67d: Retrying in 9 seconds
        0f7136d71739: Retrying in 9 seconds
        cf0db633a67d: Retrying in 8 seconds
        0f7136d71739: Retrying in 8 seconds
        cf0db633a67d: Retrying in 7 seconds
        0f7136d71739: Retrying in 7 seconds
        cf0db633a67d: Retrying in 6 seconds
        0f7136d71739: Retrying in 6 seconds
        cf0db633a67d: Retrying in 5 seconds
        0f7136d71739: Retrying in 5 seconds
        cf0db633a67d: Retrying in 4 seconds
        0f7136d71739: Retrying in 4 seconds
        cf0db633a67d: Retrying in 3 seconds
        0f7136d71739: Retrying in 3 seconds
        cf0db633a67d: Retrying in 2 seconds
        0f7136d71739: Retrying in 2 seconds
        cf0db633a67d: Retrying in 1 second
        0f7136d71739: Retrying in 1 second
    panic.go:617: WARNING: Could not open the configuration file: [/root/.config/gcloud/configurations/config_default].
        ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
        Please run:
        
          $ gcloud auth login
        
        to obtain new credentials.
        
        If you have already logged in with a different account:
        
            $ gcloud config set account ACCOUNT
        
        to select an already authenticated account to use.
        unable to stream build output: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Please fix the Dockerfile and try again..
```

**Comment by briandealwis** [comment]
Travis has its own registry mirror (not accessible outside of Travis), and `alpine:3.10` is there:
```
$ echo 'Is alpine:3.10 in registry-1.travis-ci.com:'; curl -I https://registry-1.travis-ci.com/v2/library/alpine/manifests/3.10
Is alpine:3.10 in registry-1.travis-ci.com:
HTTP/1.1 200 OK
Content-Length: 2783
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:c03ac4171c45d0e2ee535ae9ebecceac177b9c2dbc7d761b22c5740b5ae1d995
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:c03ac4171c45d0e2ee535ae9ebecceac177b9c2dbc7d761b22c5740b5ae1d995"
X-Content-Type-Options: nosniff
Date: Wed, 06 Jan 2021 18:53:44 GMT
```

Hmm, I wonder why our `docker` build isn't finding the image though.

**Comment by briandealwis** [comment]
So re: k3d and kind: maybe we should be using minikube for our integration tests, and just a few tests for k3d and kind.

**Comment by briandealwis** [comment]
I suspect that we're hitting MTU issues (my new working hypothesis: unexplained problems are due to mtu size mismatch).

What's odd is that [Travis does set the MTU to 1460 in `/etc/docker/daemon.json` and restarts the daemon service](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/appliances/set_docker_mtu_and_registry_mirrors.rb), but it doesn't seem to be reflected in the `docker0` interface (https://api.travis-ci.com/v3/job/469531857/log.txt):
```
  [0Ktravis_time:start:118a573f
  [0Ktravis_fold:start:docker_mtu_and_registry_mirrors
  [0Ktravis_fold:end:docker_mtu_and_registry_mirrors
 
 [0Ktravis_time:end:118a573f:start=1610031756059735104,finish=1610031758612403908,duration=2552668804,event=set_docker_mtu_and_registry_mirrors
...
travis_fold:start:before_install.1
[0Ktravis_time:start:0a738fe3
[0K$ echo -e "\033[0;34m# Docker engine config file \033[0m"; sudo cat /etc/docker/daemon.json
[0;34m# Docker engine config file [0m
{"registry-mirrors": ["https://registry-1.travis-ci.com"], "mtu": 1460}
travis_time:end:0a738fe3:start=1610031784551263119,finish=1610031784559164712,duration=7901593,event=before_install
...
[0Ktravis_fold:start:before_install.4
[0Ktravis_time:start:0717c519
[0K$ echo 'Interface MTUs:'; grep . /sys/class/net/*/mtu
Interface MTUs:
/sys/class/net/docker0/mtu:1500
/sys/class/net/ens4/mtu:1460
/sys/class/net/lo/mtu:65536
travis_time:end:0717c519:start=1610031785883201495,finish=1610031785887331110,duration=4129615,event=before_install
[0Ktravis_fold:end:before_install.4

```

**Comment by briandealwis** [comment]
Ah, [k3d apparently creates its own network](https://github.com/rancher/k3d/issues/165) which will use the default MTU 1500.  Pieces are falling into place.

**Comment by briandealwis** [comment]
The image loading problem seems far more mundane: our `util.RunCmdOut()` creates pipes for stdout and stderr, and we read all of stdout and then all of stderr.

https://github.com/GoogleContainerTools/skaffold/blob/d439550b465f70a5310db20f6c3f0f0bb8e56068/pkg/skaffold/util/cmd.go#L83-L97

Pipes apply backpressure so if we have too much output on stderr then we could block here.  But `k3d image import` outputs to stdout, but on the off-chance that there it could block if there was nothing listening to stderr, I changed `RunCmdOut()` to instead write to a byte buffers… and it still fails periodically.  So I then hacked the code to just write directly to `os.Stdout` + `os.Stderr` and it's fine. 

And the timeout seems to be because `k3d image import` is pulling an image… though it's only about 9MB.

```
 > Loading images into k3d cluster nodes...
 >  - gcr.io/k8s-skaffold/skaffold-jib:c53ab5231ba663e58769bddb5cb033baa301593adae27f0332d5a42043856360 -> INFO[0000] Loading images into 'k3s-default'            
> INFO[0000] Starting k3d-tools node...                   
> INFO[0000] Pulling image 'docker.io/rancher/k3d-tools:v3.1.3' 
> 
```

**Comment by briandealwis** [comment]
Setting up registry-mirrors on k3d is failing.  I've tried explicitly adding registry-1.docker.io, but that doesn't seem to fix it:
```
mirrors:
  docker.io:
    endpoint:
      - "https://mirror.gcr.io/"
```

This needs more investigation.

**Comment by briandealwis** [comment]
Closing in favour of #5221

**Pull request closed without merging**
