### PR TITLE
fix: Allow apply of manifests without file name restrictions (#6871)

### PR DESCRIPTION
**Pull request by smaftoul**
Fixes: #6871

**Description**

We don't check anymore if the extension of files are yaml or json.

**User facing changes (remove if N/A)**

Before:

You could only `skaffold apply file.{json,yml,yaml}`

After:

Yo can `skaffold  apply file` , with any filename but `skaffold.yaml.out`. 

**Follow-up Work**

I think allowing any filename but `skaffold.yaml.out` is not the intended behaviour, but I don't know if it's reasonable.
Doing so is because tests creates files with this filename and not matching this filename as a kubernetes manifest allows all tests to pass.
Maybe updating testdata is a better option.
Also, there is maybe a test missing for the use case ?

### CODE REVIEW

**Comment by smaftoul** [comment]
Jsut signed the CLA !

**Comment by briandealwis** [comment]
Thanks @smaftoul for taking a stab at this!  The underlying problem is that `schema.IsSkaffoldConfig()` uses the same file-name based logic.  If we remove that call to `HasKubernetesFileExtension()` then everything should be good.
https://github.com/GoogleContainerTools/skaffold/blob/24180d9082499b63591da1aef7ecffc24491463f/pkg/skaffold/schema/versions.go#L186-L196

**Comment by smaftoul** [comment]
@briandealwis Thanks for the clever explanation !

I've removed the test on the filename and removed the extension check in `IsSkaffoldConfig`, all tests are passing !

Should I squash my commit that fixes IsKubernetesManifest into one commit ?

Now that I have fixed this the function [IsKubernetesManifest](https://github.com/GoogleContainerTools/skaffold/pull/6914/files#diff-84007c22cafe6dc78f08318fd7c63e21242d54de5a87a4e83f98afef498c731bR56) looks a lot like [IsSkaffoldConfig](https://github.com/GoogleContainerTools/skaffold/blob/4410f505a210996db983c1a2058161988fad9c47/pkg/skaffold/schema/versions.go#L186-L191), should this be improved ? In another PR ?

Does this PR needs to add a test to show it works on non yaml / json files ?

**Review by briandealwis — APPROVED** [review]
We're good to go here: we squash on commit.  Thanks for your help!

**Comment by smaftoul** [comment]
@briandealwis I don't really understand why the integration tests [cannot find this `testdata/init/hello/deployment.yaml`](https://github.com/GoogleContainerTools/skaffold/runs/4386395723?check_suite_focus=true#step:14:1492 ).
Any idea ?
`make test` executes fine locally, but I'm not sure it executes integration tests.

**Comment by tejal29** [comment]
> @briandealwis I don't really understand why the integration tests [cannot find this `testdata/init/hello/deployment.yaml`](https://github.com/GoogleContainerTools/skaffold/runs/4386395723?check_suite_focus=true#step:14:1492). Any idea ? `make test` executes fine locally, but I'm not sure it executes integration tests.

@smaftoul looks like the integration test is failing `skaffold init --generate-manifests` is failing. 

Please refer to the docs here https://github.com/GoogleContainerTools/skaffold/blob/main/DEVELOPMENT.md#integration-tests to run integration tests. 
Let us know if you have any issues.

**Comment by smaftoul** [comment]
```
$ INTEGRATION_TEST_ARGS="-run=TestInit/" make integration-in-kind  
[...]
=== RUN   TestInitManifestGeneration
=== RUN   TestInitManifestGeneration/hello
time="2021-12-17T12:28:16Z" level=info msg="Namespace: skaffoldxqgvj"
time="2021-12-17T12:28:16Z" level=info msg="Running [skaffold init -f skaffold.yaml.out --force --generate-manifests] in testdata/init/hello"
time="2021-12-17T12:28:16Z" level=info msg="Ran [skaffold init -f skaffold.yaml.out --force --generate-manifests] in 305.6102ms"
time="2021-12-17T12:28:16Z" level=info msg="Running [skaffold run --namespace skaffoldxqgvj -f skaffold.yaml.out --default-repo gcr.io/k8s-skaffold] in testdata/init/hello"
time="2021-12-17T12:28:25Z" level=info msg="Ran [skaffold run --namespace skaffoldxqgvj -f skaffold.yaml.out --default-repo gcr.io/k8s-skaffold] in 9.233 seconds"
--- PASS: TestInitManifestGeneration (9.58s)
    --- PASS: TestInitManifestGeneration/hello (9.58s)

[...]

=== Slow Tests ===
11.64s	TestInitCompose/compose
11.64s	TestInitCompose
9.58s	TestInitManifestGeneration/hello
9.58s	TestInitManifestGeneration
7.84s	TestInitKustomize/kustomize_init
7.84s	TestInitKustomize
3.89s	TestInitWithCLIArtifactAndManifestGeneration/init_with_cli_artifact_and_manifests
3.89s	TestInitWithCLIArtifactAndManifestGeneration
3.75s	TestInitWithCLIArtifact/init_with_cli_artifact
3.75s	TestInitWithCLIArtifact
0.33s	TestInitFailures/no_builder
0.33s	TestInitFailures
Deleting cluster "kind" ...

$ echo $?
0
```

@tejal29 I fail to reproduce the error running local integration tests in kind. Any idea what I am doing wrong ?

**Review by SSGoku369 — COMMENTED** [review]
kok

**Comment by SSGoku369** [comment]
ok

**Comment by MarlonGamez** [comment]
hey @smaftoul , could you try rebasing this and pushing to get these integration tests to rerun ? I'll look into this issue and see what we can do

**Comment by smaftoul** [comment]
@MarlonGamez as you can see, I rebased the PR and pushed, but the test didn't ran again. I guess the PR needs to be added the `kokoro:run` label.

**Comment by smaftoul** [comment]
@MarlonGamez thanks for re-running the tests !  The integration tests still fails with the same error and still works locally.
Any idea what's going on ?

**Comment by smaftoul** [comment]
@MarlonGamez Thanks, with `git status` I didn't notice I had this `testdata/init/hello/deployment.yaml` already existing from previous run, `git status --ignored` showed me it, I removed it and could reproduce the issue.

Now, that I can reproduce the issue, I have not much idea why this `deployment.yaml` doesn't exist. Also, I have hard time reproducing manually the issue to understand the test, as the tests removes the kind cluster it created and I cannot re-run the same commands.

Any idea of next steps to understand what is going on ?

**Comment by MarlonGamez** [comment]
hey @smaftoul , thanks for being patient with this. This failure is pretty baffling, I can't think of what's going wrong. I'll clone this and see if I can reproduce this to see what we can do

**Comment by MarlonGamez** [comment]
hey @smaftoul, sorry I haven't had much time to get to this, but I poked around the code a bit and I think I've figured out what the issue is. I can take over this PR from here and try to get it into a working state

**Comment by smaftoul** [comment]
@MarlonGamez thank you very much !
Any hint how could I have debugged that ?

**Comment by MarlonGamez** [comment]
@smaftoul I looked for code paths that were using the modified functions and found that the only other thing that could be affected was the code related to `skaffold init` that looked for files. I also have more context on how `skaffold init` works since I've done a decent amount of work on it, and unfortunately this error seems like it would be pretty hard to figure out what was happening without that context

**Comment by smaftoul** [comment]
Thanks for the explanantion ;)

**Pull request merged**
