### PR TITLE
Cross compile Skaffold, with CGO=1, using xgo

### LINKED ISSUE #1936: Automate the CGO=1 binary release

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #1936

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by balopat** [comment]
retriggered kokoro...

**Comment by dgageot** [comment]
I have no idea why it works on my machine but not on cloud build... I spent an hour trying to understand. xgo runs containers so on Cloud Build, it's Docker in Docker. Maybe that's the source of the issue. I'll have to try again

**Comment by dgageot** [comment]
Turns out it's a docker in docker issue. I'll see if I can find a solution.

**Comment by dgageot** [comment]
@nkubala @balopat I might have got it sorted out. Could you please try again?

**Comment by balopat** [comment]
This is very exciting, thank you for experimenting with it!

**Pull request merged**
