### PR TITLE
Add tests for helm deployment with `packaged' option

### PR DESCRIPTION
**Pull request by hypnoglow**
Following #682 

Also added `testdata/foo` helm chart (created using `helm create foo`) for further testing.

### CODE REVIEW

**Comment by hypnoglow** [comment]
I think CI linter issues are unrelated to this PR.

**Comment by dlorenc** [comment]
@hypnoglow can you rebase? the CI issues should be fixed at HEAD.

**Comment by hypnoglow** [comment]
@dlorenc done 👌

**Comment by dgageot** [comment]
@hypnoglow I had to update the branch to merge it. Can you just confirm you are ok with that?

**Pull request merged**
