### PR TITLE
docs: use dropdown menu for selecting version

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes: #6442 
This PR replaces the huge list of versions with a dropdown menu.
## Before:
image

## After:
image

### CODE REVIEW

**Comment by ahmetb** [comment]
@gsquared94 I would approach this cautiously.
I don't think search engines will click to that dropdown and wait for JS to execute, so any sub-page that is not directly linked from an `<a href` will no longer be indexed.

Is that desirable?

**Comment by gsquared94** [comment]
> @gsquared94 I would approach this cautiously.
> I don't think search engines will click to that dropdown and wait for JS to execute, so any sub-page that is not directly linked from an `<a href` will no longer be indexed.
> 
> Is that desirable?

@ahmetb  I can't say that I even considered this. I'm not too sure about what the benefits are of the different version pages being indexed. 
I definitely want to change this to a dropdown menu but must admit that I'm not very good with frontend. Is there a better way for achieving this?

**Comment by ahmetb** [comment]
1. I note that we already use some sort of JS loading this skaffod.yaml page itself as well as those different pages. 

    For example, this [cache](https://webcache.googleusercontent.com/search?q=cache:i4JxLMYZ2Q4J:https://skaffold.dev/docs/references/yaml/+&cd=1&hl=en&ct=clnk&gl=us) does have no content of skaffold.yaml fields indexed (hence they cannot be used as search keywords). 

    > image


2. But with this change, you'll also lose some results from https://www.google.com/search?q=%22skaffold.yaml%22+%22version+of+the+configuration%22 as these separate pages will not be recognized by the search bots and also since they are not in /sitemap.xml

    > image

I'd say this is not making the situation worse, so go for it.

**Review by aaron-prindle — APPROVED** [review]
LGTM

**Pull request merged**
