### PR TITLE
Added ability to sync files despite .dockerignore

### PR DESCRIPTION
**Pull request by petr-buchin**
Fixes: #3401

**Description**
This PR allows to specify manual rules for "docker-ignored" paths in order for them to be synced to container during Skaffold `dev`-mode.
Paths from manual sync rules will be synced to containers **if and only if** they are absolutely equal with some path in `.dockerignore` file - this ensures that user explicitly wants to enable sync for this file/directory.
For example user can specify manual rule as follows:

```yaml
sync:
  - src: 'src/dummy/*'
    dest: '/some/dest/dir/src/dummy'
    strip: 'src/dummy'
```

This rule will apply **only** if `.dockerignore` file has exactly the same path pattern:

```
src/dummy/*
```

**At the moment PR does not include tests, but I will be happy to add some if you'll accept the basic idea behind this PR.**

### CODE REVIEW

**Comment by petr-buchin** [comment]
@googlebot I signed it!

**Comment by tejal29** [comment]
@petr-buchin We discussed this in today's meeting and the team feel, "A manual sync rule should override `.dockerignore`.  A developer has shown their intent to sync this file and skaffold should not apply any filters. "

Would you be for implementing this approach instead of this PR?

**Comment by petr-buchin** [comment]
@tejal29 thanks for an answer!
Sure I may implement this approach, but I have two more comments on that:

1. I believe that many people specify to sync entire project dir. For such use cases `.dockerignore` will be ignored entirely, and this will not be intentional from developer side. On the other hand - current solution really shows intent to sync ignored file/dir - since for that you need explicitly create manual sync rule where `src` is equal to `.dockerignore` line.

2. Disabling any filters for all manual sync rules will be a BC break, and I believe you may receive a lot of new issues about that new behavior.

Having said that, do you confirm that you want to disable `.dockerignore` filters entirely for manual sync rules, even when rule's `src` is an entire project dir? 
If you do, I'll start to implement this.

**Comment by tejal29** [comment]
Thanks @petr-buchin for getting back. 
My comments inline. 

> * I believe that many people specify to sync entire project dir. For such use cases `.dockerignore` will be ignored entirely, and this may not be intentional from developer side. On the other hand - current solution really shows intent to sync ignored file/dir - since for that you need explicitly create manual sync rule where `src` is equal to `.dockerignore` line.

TO understand correctly, you are mentioning a users have in their `skaffold.yaml` already defined, 
```sync:
    manual;
    -  src: src/
        dest: app/
```
And they have `.dockerignore`, file as
```
src/secrets/**
```
In this case, users are relying on the `dockerignore` to ignore the `src/secrets` and we should preserve that behavior.

I was thinking, if we have a manual sync rule which exactly matches` dockerignore` then the manual sync rule should supersede.
```
sync:
    manual;
    -  src: dist/linux/**
        dest: bin/
``` 
and `dockerignore`
```
dist/**
```
In above case, if you dist folder is as below,  then only `dist/linux/app` should be synced.
```
- dist
 | - linux
       - app
 | - windows
      - app.exe 
```

Does this make sense?

> * Disabling any filters for all manual sync rules will be a BC break, and I believe you may receive a lot of new issues about that new behavior.

Yes. i think you are right not this. The new feature behavior would be added in release notes and filesync definition. https://skaffold.dev/docs/pipeline-stages/filesync/


Having said that, do you confirm that you want to disable .dockerignore filters entirely for manual sync rules, even when rule's src is an entire project dir?
If you do, I'll start to implement this.

**Comment by petr-buchin** [comment]
Hi @tejal29, 
Thanks for a detailed response!

Although I did not understand the last part of you response, - `Having said that, do you confirm that you want to disable...` - my words without a comment on that, - I think I understand what you are proposing. 

To sum this up:

1. If user tries to sync some top-level project dir, like in your example:

```
manual;
    - src: src/
      dest: app/
```
...and there are some subdirectories of that dir in  `.dockerignore`, - for example `src/secrets/**`, - then this subdirectories will be ignored, as before. In order to sync this ignored dir `src/secrets/**`, user will have to create another manual sync rule, which explicitly enables sync for that ignored dir, for example:

```
manual
  # ...
  - src: src/secrets/**
    dest: some/destination
```

_This use-case describes behavior of sync, when_ **manual sync rule is wider** _than_ `.dockerignore` _rule_.

2. As you pointed out - if a manual rule `src` is a subset of some `.dockerignore` rule, we should ignore all files and dirs, specified in `.dockerignore` rule, **except those that specified in manual sync rule**, e.g. if user has `.dockerignore` rule as follows:

```
dist/**
```

and manual rule is

```
manual:
  - src: dist/linux/**
    dest: bin/
```

then we should sync only `dist/linux/**` an ignore all other files and dirs inside `dist`.

_This use-case describes behavior of sync, when_ **.dockerignore rule is wider** _than_ manual sync _rule_.

This would require some `glob`-matching.

I'll try to implement this.

**Comment by briandealwis** [comment]
Hi @petr-buchin — just wondered if you'd had a chance to look at this again.  No rush.

**Comment by petr-buchin** [comment]
Hi @briandealwis!
I'll try to get to this on weekend.

**Comment by tejal29** [comment]
@petr-buchin Sorry for the late response. You nailed both the use cases!
Looking forward for this!

**Comment by petr-buchin** [comment]
@tejal29 lately I've tried to implement solution we agreed on, but I got stack. In order for solution above to work, code should be able to answer the question "which of this glob patterns is more specific?". 

There are two problems with that:

1. Currently code uses "matcher" to tell whether some path matches one or more rules in `.dockerignore`. Now we need to match paths from sync rules also. If path matches `.dockerignore` patterns and paths from sync rules, we need to find, what pattern is the most specific one? If the most specific pattern is specified in sync rules - we should sync file/directory. Otherwise, if the most specific pattern is from `.dockerignore` - path should be ignored. The problem is that path can match multiple patterns from `.dockerignore` and sync rules. Therefore, we need to find all patterns that match given path, and then sort them from the most general to specific. This means that we cannot use `matcher`'s method `Matches` or new matcher needs to be created for each pattern.

2. I don't know a fast and reliable way to tell, which of two glob patterns is more specific. At first I thought about such an algorithm: for each of patterns, check whether it matches a parent dir of a given path. If it does, continue until we find top-most path that this pattern matches. After that we can check, which of the patterns has the smallest "top-most matched path" - this is our "most specific pattern". But this solution will not work, since pattern can include file extension, like `some-dir/some-other-dir/**/*.png`, therefore any directory will not match. 

Do you have some vision on how to compare patterns?

**Comment by gsquared94** [comment]
Haven't looked into the implementation but the problem seems quite involved.
Say your sync rules say:`a/*`, `a/b/c/*` and dockerignore file has `a/b/*`. Does that mean sync everything in `dir a` except `dir b` but also everything in `dir c`?

**Comment by gsquared94** [comment]
One possible algorithm off the top of my head:
Maintain a `list []*List` where `list[0], list[1],..` are non overlapping patterns and `list[0][0]->list[0][1],..` are sorted overlapping patterns from most generic to most specific. To decide for a given filepath f binary search on the first matching `*List`. If the matched `list[i][j]` pattern is of type `allow` then sync f else ignore. 

To build said list, iterate over all pattern entries in the dockerignore file and sync rules and try to binary search each within `list[i]`. Insert pattern in the corresponding index within `list[i]` and mark it as `allow` if it's from the sync patterns set, otherwise mark it as `ignore`.  If it doesn't match then search on next `list[i+1]`.

**Comment by gsquared94** [comment]
Each pattern behaves both as pattern and match string. You can keep a `regexMap map[string]*Regexp` for each pattern encountered to avoid recomputing.

**Comment by petr-buchin** [comment]
@gsquared94 @tejal29 @balopat basically I understand, how to deal with a given filepath `f` if we already have sorted list of patterns from most generic to most specific. For me the hardest problem is to decide, which of two given patterns is more specific. 

Lets say we have patterns `a/**/b/c/*` and `a/b/**/*`. 
Which of these is more specific? 

From one point of view the second pattern is more specific, since it matches all files inside `a/b`, not `a`. But the first pattern matches only specific `b/c` paths. So which of these is more specific?

Another example: patterns `a/b/**/*.go` and `a/b/c/**/*`. Which of these is more specific? Does file extension pattern make one of patterns more specific, than another?

 I think it's possible to come up with more complex examples.

That's the first source of problem.

The second part is: let's say we solved logical questions above. But how to implement algorithm, which will answer the question "Which of two patterns is more specific?" without rewriting `glob` engine in Go? :)
I think solution to this problem could be written using either regexp or some incremental approach (like testing, whether one of patterns matches parrent dir of current given matched path. This will not work with patterns that include file extensions, though.) But in my point of view any of these approaches will be very complex.

Do you have any ideas?

**Comment by petr-buchin** [comment]
Having said that - I think that current implementation, where you could sync despite `.dockerignore` rule just by copying this pattern to manual sync rule, is much easier to understand for users, and is straightforward to implement (which is shown in this PR). However, I don't have a voice here, therefore for now I will be using own fork, until we come up with some plan of how to implement your vision of this feature.

**Comment by petr-buchin** [comment]
Hi @dgageot @briandealwis @balopat @tejal29 @nkubala !
Sorry for tagging you all, I just wondered if you have a chance to look at my comments and discuss that.

Thanks in advance!

**Comment by gsquared94** [comment]
@petr-buchin sorry for the lack of response on this. @nkubala WDYT? I feel like @petr-buchin's approach is straightforward and predictable.

**Comment by gsquared94** [comment]
Changing to draft PR as it's stayed open longer than our internal configured policy.

**Comment by nkubala** [comment]
just catching up on this, sorry to be so late to the party :) 

I understand where the original concern with @petr-buchin's approach is coming from, but I think it's reasonable from a UX perspective. in practice, I'd imagine that it's hard to run into this use case in the first place without **trying** to, and I think @petr-buchin's original approach is more in line with how users will expect this to behave. plus, the complexity of trying to implement this in a totally "correct" way is making this problem technically infeasible.

at the end of the day, users have to be explicit about their intent to sync to hit this use case, so it's pretty low risk. @petr-buchin I'm fine with your original approach, if you'd like to get this PR into shape (with tests please 😄 ) I'll give it a review!

**Comment by tejal29** [comment]
Sorry @petr-buchin I see what you mean now. the way things are implemented right now, 
1. `GetBuildDependencies` returns a list all dependencies with dockerfile ignore rules. The same list is to used to determine build and sync rules.

I was wondering if it made sense to change `docker.GetBuildDependencies` to respect manual sync rules. Something along these lines?

```

// GetDependencies finds the sources dependencies for the given docker artifact filtering out manual sync rules.
// All paths are relative to the workspace.
func GetDependencies(ctx context.Context, a *latest.Artifact, insecureRegistries map[string]bool) ([]string, error) {
	absDockerfilePath, err := NormalizeDockerfilePath(a.workspace, a.DockerArtifact.dockerfilePath)
	if err != nil {
		return nil, fmt.Errorf("normalizing dockerfile path: %w", err)
	}

	// If the Dockerfile doesn't exist, we can't compute the dependencies.
	// But since we know the Dockerfile is a dependency, let's return a list
	// with only that file. It makes errors down the line more actionable
	// than returning an error now.
	if _, err := os.Stat(absDockerfilePath); os.IsNotExist(err) {
		return []string{dockerfilePath}, nil
	}

	fts, err := readCopyCmdsFromDockerfile(false, absDockerfilePath, a,workspace,  a.DockerArtifact.buildArgs, insecureRegistries)
	if err != nil {
		return nil, err
	}

	dockerIgnoreexcludes, err := readDockerignore(a.workspace, absDockerfilePath)
	if err != nil {
		return nil, fmt.Errorf("reading .dockerignore: %w", err)
	}

       // go through a.Sync.Manual rules and filter all excludes. 
       excludes, err := filterSyncManualRules(excludes, a.Sync)
       
	deps := make([]string, 0, len(fts))
	for _, ft := range fts {
		deps = append(deps, ft.from)
	}

	files, err := WalkWorkspace(a.workspace, excludes, deps)
	if err != nil {
		return nil, fmt.Errorf("walking workspace: %w", err)
	}

	// Always add dockerfile even if it's .dockerignored. The daemon will need it anyways.
	if !filepath.IsAbs(dockerfilePath) {
		files[dockerfilePath] = true
	} else {
		files[absDockerfilePath] = true
	}

	// Ignore .dockerignore
	delete(files, ".dockerignore")

	var dependencies []string
	for file := range files {
		dependencies = append(dependencies, file)
	}
	sort.Strings(dependencies)

	return dependencies, nil
}


func filterManualSyncRules(dockerIgnoreExcludes []string, s latest.Sync) ([]string, err) {
		excludes := []string{}
	if a.Sync == nil || a.Sync.Manual == nil {
		return dockerIgnoreExcludes, nil
	}
	syncPatterns := []string{}
	for _, s := range a.Sync.Manual {
		syncPatterns = append(syncPatterns, s.Src)
	}
	for _, e := range(dockerIgnoreExcludes) {
			matcher, err := fileutils.NewPatternMatcher(syncPatterns)
			if err != nil {
				return nil, fmt.Errorf("invalid exclude patterns: %w", err)
			}
			synced, err := matcher.Matches(e)
			if err != nil {
				return nil, fmt.Errorf("invalid exclude patterns: %w", err)
			}
			if !synced {
				excludes = append(excludes, e)
			}
	}
}

```

**Comment by tejal29** [comment]
@petr-buchin Please let us know if you can help you in getting this in.
Looking forward for your contribution.

**Comment by petr-buchin** [comment]
@tejal29 hi, I'll try to get to this on weekend. Thanks!

**Comment by tejal29** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
