### PR TITLE
Manually specify files and artifacts to watch

### PR DESCRIPTION
**Pull request by dgageot**
Allow the users to not watch some artifacts and also to override the list of files to watch.

wdyt?

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by r2d4** [comment]
Fixes #20

**Comment by dgageot** [comment]
@balopat Do you think this should be merged for the beta?

**Comment by nkubala** [comment]
@dgageot can you rebase? I think this should go in for this week's release.

**Comment by dgageot** [comment]
@nkubala I have a rebased version that slightly fails because of #1332

**Comment by dgageot** [comment]
Will take a look at it tomorrow

**Comment by nkubala** [comment]
ref https://github.com/GoogleContainerTools/skaffold/issues/825

**Comment by dgageot** [comment]
Let's close this one for now

**Comment by davidfernandezm** [comment]
Was this ever part of skaffold? I would need to add specific files to watch on a `jib` build, but I don't currently find the option in skaffold (v1.9.1)

**Pull request closed without merging**
