### PR TITLE
Add an example for helm chart with multiple images

### PR DESCRIPTION
**Pull request by filipenf**
Shows how to override multiple images in a helm template

**Description**
Documentation-only changes: Add a snippet showing how to override multiple images from skaffold-built artifacts. I was testing with this and thought an example in the doc would be useful. Thoughts?

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Thanks for the submission @filipenf!  Currently you have updated:
`docs/content/en/docs/pipeline-stages/deployers/helm.md`

We have recently forked our docs into a `docs` and a `docs-v2` folder.  Can you also update the
docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
file with this change as well?

Additionally our repo has a unit test to enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).  Can you ammend your commit message to add a prefix - `docs:` eg:
`docs: Add an example for helm chart with multiple images`

**Comment by filipenf** [comment]
@aaron-prindle thanks for the info, I just checked the helm.md in the v2 path you mentioned and I noticed that it is missing a few of the sections from the original file. Would you also like me to match those or should I just add the new bits?

**Comment by aaron-prindle** [comment]
@filipenf just the new bits thanks! I believe the other differences are inherent to Skaffold v1 vs v2

**Comment by filipenf** [comment]
@aaron-prindle I added just the new bits and updated the commit message, however I noticed that the whole `## Image Configuration` section is missing in the v2 doc. Is that expected?

**Comment by aaron-prindle** [comment]
@filipenf ah, I see now.  Yes, if you wouldn't mind adding that section as well here that would be great.  Thanks for extra analysis here!

**Review by aaron-prindle — APPROVED** [review]
LGTM!  Thanks!

**Comment by iosifnicolae2** [comment]
When using schema v3 `artifactOverrides` does not exist, instead I've used `setValueTemplates` as follow:
```yaml
manifests:
  helm:
    releases:
    - setValueTemplates:
        firstContainerImage.repo: '{{.IMAGE_REPO}}'
        firstContainerImage.tag: '{{.IMAGE_TAG}}'
        secondContainerImage.repo: '{{.IMAGE_REPO2}}'
        secondContainerImage.tag: '{{.IMAGE_TAG2}}'
        ...
```

**Pull request merged**
