### PR TITLE
Minor doc updates

### PR DESCRIPTION
**Pull request by chanseokoh**

### CODE REVIEW

**Comment by chanseokoh** [comment]
Test is broken due to #1924.

**Comment by balopat** [comment]
Thanks for asking the right question @nkubala, I was too fast to approve.
Actually it is not true either - our release and integration tests are also based on go 1.11 - so we should change that first `deploy/skaffold/Dockerfile`

**Comment by chanseokoh** [comment]
Perhaps my go installation had some problem, which made me to think upgrading to 1.12 resolved the issue. I reverted the 1.1.2 requirement.

**Comment by chanseokoh** [comment]
I merged with master, and tests should pass.

**Pull request merged**
