### PR TITLE
WIP: add please build

### PR DESCRIPTION
**Pull request by namtzigla**
This is an attempt to implement [please](https://github.com/thought-machine/please) builder system into skaffold.
Because please is very similar with bazel I'm using the the same approach as bazel builder implementation.

This is waiting for couple of PR on pleasings repo(thought-machine/pleasings#21 and thought-machine/pleasings#22) to be merged and it needs some tests added.

### CODE REVIEW

**Comment by namtzigla** [comment]
I signed it!

**Comment by balopat** [comment]
Hi @namtzigla, thank you for opening this PR! We are building a plugin system for builders: #1551 - it will be probably ready in a month or so - the please.build builder sounds like a perfect candidate for a community plugin. The code you're writing now is going to be largely reusable - in the end a similar `Builder` interface needs to be implemented in go. However until then it doesn't make sense for us to take this contribution as is in the skaffold repo. Thank you for your understanding!

**Comment by namtzigla** [comment]
Hi @balopat,

In regards of closing #1551 and what you described in #1988 I was wondering is there a chance for the please plugin to be integrated into skaffold ? 

thanks.

**Comment by priyawadhwa** [comment]
Hey @namtzigla -- we've decided to go ahead with a more lightweight plan for custom builders, the new plan is described in #2009.

Once this is done, you should be able to plug in a custom build script into the skaffold.yaml & use whatever builder you want! If you have a chance, feel free to take a look at that issue or the WIP PR #1999 and leave any questions you may have.

**Comment by namtzigla** [comment]
due to latest developments I'm going to close this

**Comment by priyawadhwa** [comment]
Hey @namtzigla -- the initial custom builder implementation is out now, if you're still interested in using please.build with skaffold! Here's an [example](https://github.com/GoogleContainerTools/skaffold/tree/master/integration/testdata/custom) using a custom build script and associated [docs](https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally). If you end up trying it out, please open an issue if you run into any trouble, and let us know if it works for you!

**Pull request closed without merging**
