### PR TITLE
Remove ACR builder

### LINKED ISSUE #1283: [Proposal] Introduce v1beta1 config + remove ACR builder
I propose removing the ACR builder. 

**Reason**: The ACR builder currently doesn't have integration tests, as we don't have the infrastructure to support it yet. Our current thinking around non-Google cloud builder integrations (e.g #1207) is that we will enable the community to contribute them through "a plugin model". This "plugin model" is still unclear - first candidate was the Knative Build CRD (#851) however there are a lot of changes anticipated in that area, so the path is not completely clear yet. 

`v1beta1`: This will introduce a breaking change and we'll need to introduce a new version. As we are planning to go beta soon, this would be a great opportunity to introduce `v1beta1`.

### PR DESCRIPTION
**Pull request by balopat**
~Should only be merged after: #1305.~

Fixes #1283.

### CODE REVIEW

**Comment by ehotinger** [comment]
@balopat @dgageot could one of you cc me when the plugin model is complete so we can add this back in? Or if you need ideas wrt the plugin model?

**Comment by SteveLasker** [comment]
I was happy to see ACR Tasks supported, but surprised to see if removed. Shouldn't the extension model have been figured out before removing a capability? We're happy to help support this so this is truly a cross cloud solution.

**Comment by nkubala** [comment]
> Shouldn't the extension model have been figured out before removing a capability?

@SteveLasker possibly, but our thinking was that we wanted to avoid setting the precedent and leading contributors to send us more new builders, which we'd have to reject even though this one was already accepted.

the builder plugin model has been implemented in skaffold for a few releases now, so we're happy to accept contributions for new builders as plugins! we'll have some guidelines for contributing coming pretty soon, but feel free to start poking around in the code before that :)

**Comment by balopat** [comment]
@SteveLasker - thank you for your comment! 

In terms of the ACR tasks - we did not have the capacity, or the infrastructure to support it with a clear conscience ourselves - thank you for offering to support it - this sounds like an interesting collaboration. I wonder what you had in mind for that?  

At this point, I see the plugin model to be of a more future and cleaner direction than reverting this change back into the codebase.  

We are very actively working on the plugin model and it is impacting the builder structure heavily - I would say that it is not in a shape yet to contribute to - I would estimate another couple of weeks before it gets into a good state.

**Comment by SteveLasker** [comment]
Fair enough. As the plug-in model evolves, we're happy to support the scenario.

**Pull request merged**
