### PR TITLE
Ko builder support for insecure registries

### PR DESCRIPTION
**Pull request by halvards**
**Description**
This change adds support for insecure registries to the ko builder.

**Tracking:** #6041

### CODE REVIEW

**Review by aaron-prindle — APPROVED** [review]
LGTM

**Comment by MarlonGamez** [comment]
@halvards  This looks good to me, think it just need to be rebased and I'll approve and merge it 👍🏼

**Comment by halvards** [comment]
Thanks @aaron-prindle and @MarlonGamez! I just rebased, and I'll look for the checks passing.

**Comment by halvards** [comment]
Rebased. The kokoro build times out.

**Pull request merged**
