### PR TITLE
Automatically watch helm subcharts when skipBuildDependencies is enabled

### LINKED ISSUE #1347: Doesn't detect changes to subcharts
Skaffold seems to not detect changes to subcharts.  I've created an umbrella chart, and am using subcharts for various sites & services.  In 'dev' mode, changing the contents of a subchart in "charts" ought be detected & deployed.

### Expected behavior

Modifying a subchart in "charts" should trigger a redeploy.

### Actual behavior

Seemingly, nothing.

### Information

- Skaffold version: v0.18.0
- Operating system: MacOS 10.14.1

### PR DESCRIPTION
**Pull request by pscarey**
Fixes #1347 

Previously, the Helm deployer was set to ignore chart dependencies, so updating a sub chart didn't trigger a re-deploy in when running `skaffold dev`. This pull request removes that restriction, so that chart dependencies are included in the watch list.

### CODE REVIEW

**Comment by pscarey** [comment]
Thanks for raising that issue. 

I ran the existing go tests with only these changes, but am current successfully using #1368 in conjunction with this on our actual helm charts (as #1368 is required to run our charts).

Would you be happy if I paused this until we've completed the merge of #1368, then only allowed automatic watching of subcharts when the Helm `skipDependencyBuild` option is enabled? I will also document this caveat.

**Comment by pscarey** [comment]
The 'helm dep build' command modifies files in the charts directory of the main helm chart. By default any files in that directory are excluded from the watch list, but if skipBuildDependencies is enabled those files are now automatically included.

**Comment by nkubala** [comment]
I think this will work now that #1368 is in, @pscarey can you rebase please?

**Comment by pscarey** [comment]
@nkubala Have updated.

**Comment by pscarey** [comment]
@nkubala Hope the description is clear. Please add the `docs-modifications` label. Thanks.

**Pull request merged**
