### PR TITLE
add `build-dependencies` metric

### PR DESCRIPTION
**Pull request by gsquared94**
Related: #5329

### CODE REVIEW

**Review by IsaacPD — APPROVED** [review]
This all looks good to me. Could you in this PR or another please run `make generate-telemetry-json` to update the documentation to detail that we are collecting this info now?

**Comment by gsquared94** [comment]
> This all looks good to me. Could you in this PR or another please run `make generate-telemetry-json` to update the documentation to detail that we are collecting this info now?

`make generate-telemetry-json` is broken on `master`:
```
go run hack/struct-json/main.go -- pkg/skaffold/instrumentation/meter.go docs/content/en/docs/resources/telemetry/metrics.json
panic: field "errHandler" needs comment (all public fields require comments)

goroutine 1 [running]:
main.newDefinition(0xc000017120, 0xa, 0x1199140, 0xc000179100, 0x0, 0x0, 0xc00019d770)
        /Users/gaghosh/Code/Work/fork/skaffold/hack/struct-json/main.go:90 +0x9d7
main.generate(0xc000020180, 0x25, 0x2, 0xc000020180, 0x25, 0x116cd6b, 0x11)
        /Users/gaghosh/Code/Work/fork/skaffold/hack/struct-json/main.go:140 +0x1ab
main.generateJSON(0x1166cfc, 0x1, 0x7ffeefbff80c, 0x25, 0x7ffeefbff832, 0x35, 0x0, 0x0, 0xc00006e058)
        /Users/gaghosh/Code/Work/fork/skaffold/hack/struct-json/main.go:59 +0xa8
main.main()
        /Users/gaghosh/Code/Work/fork/skaffold/hack/struct-json/main.go:53 +0xb3
exit status 2
make: *** [generate-telemetry-json] Error 1
```

**Comment by IsaacPD** [comment]
Oh I forgot a comment 😅, that's fine then. It should be fixed after #5324

**Comment by gsquared94** [comment]
`debug/buildpacks` integration test flaking, merging anyways.

**Pull request merged**
