### PR TITLE
Add a pop of color to terminal output

### LINKED ISSUE #835: Colorize skaffold output vs. piped output
Imagine the bolded lines being colorized

**Starting build...**
**Building [gcr.io/k8s-skaffold/leeroy-web]...**
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM golang:1.10.1-alpine3.7 as builder
 ---> 52d894fca6d4
Step 2/6 : COPY web.go .
 ---> Using cache
 ---> a2f24d7c8473
Step 3/6 : RUN go build -o /web .
 ---> Using cache
 ---> bccc7a1c55a9
Step 4/6 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 5/6 : CMD ["./web"]
 ---> Using cache
 ---> 4594ba11faff
Step 6/6 : COPY --from=builder /web .
 ---> Using cache
 ---> 0c3334a419ab
Successfully built 0c3334a419ab
Successfully tagged 87851671d9c0322b1e2ae520ac185db1:latest
Successfully tagged gcr.io/k8s-skaffold/leeroy-web:v0.10.0-15-g9be665d0
The push refers to repository [gcr.io/k8s-skaffold/leeroy-web]
0939c7023aea: Preparing
cd7100a72410: Preparing
0939c7023aea: Layer already exists
cd7100a72410: Layer already exists
v0.10.0-15-g9be665d0: digest: sha256:b282f3080f95da7e3d07cf8c8b8a04fa0757f443e39e685b1afb0136635432d3 size: 739
**Building [gcr.io/k8s-skaffold/leeroy-app]...**
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM golang:1.10.1-alpine3.7 as builder
 ---> 52d894fca6d4
Step 2/6 : COPY app.go .
 ---> Using cache
 ---> 567cbfbce599
Step 3/6 : RUN go build -o /app .
 ---> Using cache
 ---> c81ce05f8516
Step 4/6 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 5/6 : CMD ["./app"]
 ---> Using cache
 ---> b9637259e7db
Step 6/6 : COPY --from=builder /app .
 ---> Using cache
 ---> b59a8f9b007f
Successfully built b59a8f9b007f
Successfully tagged 3a33a2a3607960cf6853fd8fb18e362f:latest
Successfully tagged gcr.io/k8s-skaffold/leeroy-app:v0.10.0-15-g9be665d0
The push refers to repository [gcr.io/k8s-skaffold/leeroy-app]
7916d9ca309a: Preparing
cd7100a72410: Preparing
cd7100a72410: Layer already exists
7916d9ca309a: Pushed
v0.10.0-15-g9be665d0: digest: sha256:1ff255d77a95bf46a22b16300539de4dbe33fc1329d9e6518db6392cfbb3297f size: 739
**Build complete in 16.503200338s**
**Starting deploy...**
**Watching for changes...**

### PR DESCRIPTION
**Pull request by bobcatfish**
This commit breaks up the Skaffold terminal output with a pop of color!

Skaffold draws a distinction between log output, which goes to stdout,
and output from Skaffold to the user, which goes to stdout and is
interleaved with output from the tools Skaffold users (e.g. docker for
building). This commit changes the output from Skaffold to the user to
be Blue!

The escape codes to make the text blue (or other colors, in the case of
the kube pod-specific logging) will only be output if stdout is a
terminal. If output is being redirected to a file for example, the
escape codes will not be included.

This change makes use of the exciting `colors.go` logic but splits it
into the picker (specifically for mapping images to colors consistently)
from the logic to add escape codes.

Possible alternatives/improvements:
* Pass the formatter object around directly instead of `io.Writer`. One
  big downside to this is it would make it harder for callers to control
  the color of the output (right now it can be arbitrarily changed
  anywhere, e.g. `fix.go` outputs both blue text and plain text)
* Split the formatting from the output.

Fixes #835 

Some example output:
image

### CODE REVIEW

**Comment by bobcatfish** [comment]
lol yeah that's a real failure, thanks integration test XD

image

**Comment by bobcatfish** [comment]
image
 wut

**Comment by dgageot** [comment]
@bobcatfish I'm wondering, it the code wouldn't be much simpler if we'd colorize the docker build output and the kubctl output.

**Comment by bobcatfish** [comment]
Okay so @dgageot and @r2d4 I think https://github.com/GoogleContainerTools/skaffold/pull/857 is a better solution to this. I also tried out wrapping `io.Writer` in https://github.com/GoogleContainerTools/skaffold/pull/856 but I think that was worse.

**Pull request closed without merging**
