### PR TITLE
Add support for urls in deploy.kubectl.manifests

### PR DESCRIPTION
**Pull request by r2d4**
```
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - https://raw.githubusercontent.com/GoogleContainerTools/skaffold/master/examples/getting-started/k8s-pod.yaml
```

### CODE REVIEW

**Comment by r2d4** [comment]
```
--- FAIL: TestRun/bazel_example (5.85s)
    	run_test.go:183: skaffold: Starting build...
    		Building [gcr.io/k8s-skaffold/skaffold-bazel]...
    		Extracting Bazel installation...
    		Starting local Bazel server and connecting to it...
    		INFO: Invocation ID: 34c478e4-4ab3-444d-8651-f0d140f2f027
    		Loading:
    		Loading: 0 packages loaded
    		ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
    		Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
    		ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
    		Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
    		INFO: Elapsed time: 5.746s
    		INFO: 0 processes.
    		FAILED: Build did NOT complete successfully (0 packages loaded)
    		FAILED: Build did NOT complete successfully (0 packages loaded)
    		 Running [skaffold run --namespace skaffoldcntht]: stdout Starting build...
    		Building [gcr.io/k8s-skaffold/skaffold-bazel]...
    		Extracting Bazel installation...
    		Starting local Bazel server and connecting to it...
    		INFO: Invocation ID: 34c478e4-4ab3-444d-8651-f0d140f2f027
    		Loading:
    		Loading: 0 packages loaded
    		ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
    		Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
    		ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
    		Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
    		INFO: Elapsed time: 5.746s
    		INFO: 0 processes.
    		FAILED: Build did NOT complete successfully (0 packages loaded)
    		FAILED: Build did NOT complete successfully (0 packages loaded)
    		, stderr: time="2018-12-20T19:37:37Z" level=fatal msg="build step: building [gcr.io/k8s-skaffold/skaffold-bazel]: build artifact: running command: exit status 1"
    		, err: exit status 1: exit status 1
```

**Comment by balopat** [comment]
> fixes #1408

fixes #1407.

**Comment by balopat** [comment]
Thank you for this @r2d4 :) 

@ahmadnurus this overlaps with your implementation - but one thing I prefer about this approach is 
 that it keeps the config change minimal. Do you mind closing https://github.com/GoogleContainerTools/skaffold/issues/1353?

**Comment by balopat** [comment]
I'm not sure I understand why the bazel example fails in kokoro only on this PR, but I'm looking.

**Comment by ahmadnurus** [comment]
@balopat I don't know if you prefer with mininal config change. I can change my PR if you review my PR earlier. but it' ok to close my PR for this.

**Comment by balopat** [comment]
Thanks @ahmadnurus, sorry for the inconvenience!

**Comment by balopat** [comment]
@r2d4 would you mind approving https://github.com/GoogleContainerTools/skaffold/pull/1416? :D It's super odd but I cannot reproduce this bazel failure on any other PRs - including a complete clone of this PR, locally on docker (cleaned from bazel cache, docker images, etc.). It must be a peculiar kokoro thing.

**Comment by ahmadnurus** [comment]
np @balopat , tell me if any issue that i can take!

**Pull request merged**
