### PR TITLE
Upgrade Jib to 1.8.0

### PR DESCRIPTION
**Pull request by kkowalski**
**Description**

Upgrade Jib to 1.8.0

**User facing changes**

N/A

**Before**

N/A

**After**

N/A

**Next PRs.**

N/A

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Adds documentation as needed: user docs, YAML reference, CLI reference.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit test added.
- [ ] User facing changes look good.

**Release Notes**

```
- Upgrade Jib to 1.8.0
```

### CODE REVIEW

**Comment by TadCordle** [comment]
Has GCB upgraded gradle yet? https://github.com/GoogleContainerTools/skaffold/pull/3260#issuecomment-557237148

**Comment by kkowalski** [comment]
@balopat Sure, should we keep this pr open for now ?

**Comment by chanseokoh** [comment]
The integration test is failing because GCB uses Gradle 4.6 while Jib requires 4.9. (And the next Jib release will require 5.1.)

```
            An exception occurred applying plugin request [id: 'com.google.cloud.tools.jib', version: '1.8.0']
            > Failed to apply plugin [id 'com.google.cloud.tools.jib']
               > Detected Gradle 4.6, but jib requires Gradle 4.9 or higher. You can upgrade by running 'gradle wrapper --gradle-version=4.9'.
```

**Comment by balopat** [comment]
> @balopat Sure, should we keep this pr open for now ?

We can keep it open & blocked as an active place for the jib upgrade to check for updates.

**Comment by chanseokoh** [comment]
GCB is purging the old Gradle 4.6 cache. @kkowalski could you update Jib version to 2.0.0?

**Comment by dgageot** [comment]
Closing in favour of https://github.com/GoogleContainerTools/skaffold/pull/3707

**Pull request closed without merging**
