### PR TITLE
Add Kaniko builder to GCB

### LINKED ISSUE #2377: Support kaniko builder in googleCloudBuild
### Expected behavior

Set gcr.io/kaniko-project/executor:latest as the builder image in cloud build

### Actual behavior

Status: Downloaded newer image for gcr.io/kaniko-project/executor:latest
Error: unknown flag: --tag

### Information

- Skaffold version: version...

v0.32.0

- Operating system: ...

OSX Mojave

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/ptone-kf/auth-client
  googleCloudBuild:
    timeout: 600s
    dockerImage: gcr.io/kaniko-project/executor:latest
deploy:
  kubectl:
    flags:
      global:
        - --namespace id-namespace
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

Run with a builder config as in the yaml above

### PR DESCRIPTION
**Pull request by cedrickring**
Closes #2377 

Example `skaffold.yaml`:

```
apiVersion: skaffold/v1beta13
kind: Config
build:
  googleCloudBuild:
    projectId: k8s-skaffold 
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    kaniko:
      cache: {}
```

### CODE REVIEW

**Comment by tejal29** [comment]
Current Reviewer Status:
The code changes look good. 

1. Started a build again here https://sponge.corp.google.com/invocation?id=d09d731d-bada-433d-93a3-52f3d2b11a1a&searchFor=

Things Missing:
1. Integration test
2. Try it out.


@cedrickring Can you add an integration test in something called "Google Cloud Build with kaniko" 
https://github.com/GoogleContainerTools/skaffold/blob/master/integration/run_test.go#L69

Please add an example in https://github.com/GoogleContainerTools/skaffold/tree/master/integration/examples/gcb-kaniko
similar to https://github.com/GoogleContainerTools/skaffold/tree/master/integration/examples/google-cloud-build with different image and pod name.

Thank you!

**Comment by cedrickring** [comment]
@tejal29 I added an example to `integration/examples` and `examples`. Is this correct? Otherwise `hack/check-samples.sh` fails.

**Comment by tejal29** [comment]
@cedrickring yes you need to add to both.

**Comment by tejal29** [comment]
Ran this manually
```
(add-kaniko-for-gcb)$ make
(add-kaniko-for-gcb)$ cd integration/examples/gcb-kaniko/
@gcb-kaniko (add-kaniko-for-gcb)$ ../../../out/skaffold build
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:v0.37.1-177-g8a371679
Tags generated in 28.574027ms
Checking cache...
 - gcr.io/k8s-skaffold/skaffold-example: Not found. Building
Cache check complete in 4.59181ms
Starting build...
Building [gcr.io/k8s-skaffold/skaffold-example]...
Pushing code to gs://k8s-skaffold_cloudbuild/source/k8s-skaffold-f2f175e634b8497d842730309c84554f.tar.gz
Logs are available at 
https://console.cloud.google.com/m/cloudstorage/b/k8s-skaffold_cloudbuild/o/log-b34b99c9-1ce6-43e9-95bf-d7a641743925.txt
starting build "b34b99c9-1ce6-43e9-95bf-d7a641743925"

FETCHSOURCE
Fetching storage object: gs://k8s-skaffold_cloudbuild/source/k8s-skaffold-f2f175e634b8497d842730309c84554f.tar.gz#1568050742451236
Copying gs://k8s-skaffold_cloudbuild/source/k8s-skaffold-f2f175e634b8497d842730309c84554f.tar.gz#1568050742451236...
/ [1 files][  347.0 B/  347.0 B]                                                
Operation completed over 1 objects/347.0 B.                                      
BUILD
Pulling image: gcr.io/kaniko-project/executor
Using default tag: latest
latest: Pulling from kaniko-project/executor
Digest: sha256:584a8d90679211d9b09465d778990ec15965cf78f57f197e973d57d14b08eb81
Status: Downloaded newer image for gcr.io/kaniko-project/executor:latest
gcr.io/kaniko-project/executor:latest
INFO[0000] Resolved base name golang:1.12.9-alpine3.10 to golang:1.12.9-alpine3.10 
INFO[0000] Resolved base name alpine:3.10 to alpine:3.10 
INFO[0000] Resolved base name golang:1.12.9-alpine3.10 to golang:1.12.9-alpine3.10 
INFO[0000] Resolved base name alpine:3.10 to alpine:3.10 
INFO[0000] Downloading base image golang:1.12.9-alpine3.10 
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:39f9d94d45e404c98c3aa3c9b2406185f46ffddefeb45cdd9b778024626302fc: no such file or directory 
INFO[0001] Downloading base image golang:1.12.9-alpine3.10 
INFO[0002] Downloading base image alpine:3.10           
INFO[0002] Error while retrieving image from cache: getting file info: stat /cache/sha256:acd3ca9941a85e8ed16515bfc5328e4e2f8c128caa72959a58a127b7801ee01f: no such file or directory 
INFO[0002] Downloading base image alpine:3.10           
INFO[0003] Built cross stage deps: map[0:[/app]]        
INFO[0003] Downloading base image golang:1.12.9-alpine3.10 
INFO[0003] Error while retrieving image from cache: getting file info: stat /cache/sha256:39f9d94d45e404c98c3aa3c9b2406185f46ffddefeb45cdd9b778024626302fc: no such file or directory 
INFO[0003] Downloading base image golang:1.12.9-alpine3.10 
INFO[0004] Using files from context: [/workspace/main.go] 
INFO[0004] Checking for cached layer gcr.io/k8s-skaffold/skaffold-example/cache:f6c5f80a280b91011bfd0c2e8520b2bd91b2f92a09ae34b915b4d22c2be9e9a2... 
INFO[0004] No cached layer found for cmd RUN go build -o /app main.go 
INFO[0004] Unpacking rootfs as cmd RUN go build -o /app main.go requires it. 
INFO[0011] Taking snapshot of full filesystem...        
INFO[0018] Using files from context: [/workspace/main.go] 
INFO[0018] COPY main.go .                               
INFO[0018] Taking snapshot of files...                  
INFO[0018] RUN go build -o /app main.go                 
INFO[0018] cmd: /bin/sh                                 
INFO[0018] args: [-c go build -o /app main.go]          
INFO[0018] Taking snapshot of full filesystem...        
INFO[0020] Pushing layer gcr.io/k8s-skaffold/skaffold-example/cache:f6c5f80a280b91011bfd0c2e8520b2bd91b2f92a09ae34b915b4d22c2be9e9a2 to cache now 
INFO[0023] Saving file /app for later use.              
INFO[0023] Deleting filesystem...                       
INFO[0024] Downloading base image alpine:3.10           
INFO[0024] Error while retrieving image from cache: getting file info: stat /cache/sha256:acd3ca9941a85e8ed16515bfc5328e4e2f8c128caa72959a58a127b7801ee01f: no such file or directory 
INFO[0024] Downloading base image alpine:3.10           
INFO[0025] Skipping unpacking as no commands require it. 
INFO[0025] Taking snapshot of full filesystem...        
INFO[0025] CMD ["./app"]                                
INFO[0025] No files changed in this command, skipping snapshotting. 
INFO[0025] COPY --from=builder /app .                   
INFO[0025] Taking snapshot of files...                  
PUSH
DONE
Build complete in 42.131534803s
Starting test...
Test complete in 12.78µs
Tags used in deployment:
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:v0.37.1-177-g8a371679@sha256:32a7667318196640a8aad217a8714f32214157a70cbc2bf9cc449254967de405
There is a new version (0.37.1) of Skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64

```

**Comment by tejal29** [comment]
This Pr looks good and it ready to merge.
/cc @balopat this has a config change. Are we going to tackle this the old way? In that case we need to freeze the config.

**Comment by tejal29** [comment]
Verified if kaniko was removed from gcb config, the gcb build was using docker.

**Pull request merged**
