### PR TITLE
docs: First 24 inline .yaml code blocks moved

### PR DESCRIPTION
**Pull request by techchickk**
Fixes: #nnn 
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**

**User facing changes (remove if N/A)**

**Follow-up Work (remove if N/A)**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Awesome job here @techchickk!!

Also, can you edit the commit message from:
`First 24 inline .yaml code blocks moved`
to be 
`docs: First 24 inline .yaml code blocks moved`

We have a test `convetionalcommits` that requires this naming convention as we parse these messages looking for the "<category>: <txt>" format

**Comment by techchickk** [comment]
Updated the title, got rid of a yaml file that was just a file path. Some things that show up in search results for ```yaml in docs-v2 are not actually .yaml code blocks. Starting to learn the difference.

**Comment by MarlonGamez** [comment]
hey @techchickk, looks like there's a file conflict here. If that gets fixed up I think we should be good to merge this in!

**Comment by techchickk** [comment]
> hey @techchickk, looks like there's a file conflict here. If that gets fixed up I think we should be good to merge this in!

I am no longer at Google. I haven't worked on this in over a month. I realize that this is open-source, but now, I don't have access to the people.

**Comment by aaron-prindle** [comment]
@techchickk thanks for the update here, the Skaffold team misses getting to work with you 😞.  I think the work here is very close to done, let us know if you would like to get this over the finish line yourself or if one of the Skaffold team should take over ownership here, thanks.

**Comment by aaron-prindle** [comment]
Going to close this for now, feel free to reopen or resubmit if more work is planned.  Hope all is well!

**Pull request closed without merging**
