### PR TITLE
Applied namespace to Cleanup and getArgs

### LINKED ISSUE #3762: Fails to apply namespace to releases in Helm 3
### Expected behavior

When deploying to helm and using the `namespace` tag on the release, the `--namespace` argument should be passed to the upgrade (install), delete and get calls. 

### Actual behavior

The namespace is properly applied to the upgrade (install) command, but not during `Cleanup` or `getArgs`. I believe this problem was introduced with #3738 because helm3's releases themselves are namespace'd. 

### Information

- Skaffold version: v1.4.0-73-ga9c7b3a47-dirty (pulled from master)
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: example
deploy:
  helm:
    releases:
      - name: example
        chartPath: helm
        namespace: example

```

### Steps to reproduce the behavior

Example Repo (requires a namespace "example") 
[https://github.com/BlenderDude/skaffold-helm3-namespaces](https://github.com/BlenderDude/skaffold-helm3-namespaces)

1. Create a helm deploy release that is scoped to a namespace
2. Run `skaffold dev` once
3. Quit to trigger a cleanup, it will fail because it cannot find the release in the namespace
4. Re-run `skaffold dev` and it will fail upon installing because there is already a release, this exposes the fact that the helm getter is not accessing  a namespace scoped release

I have already made some changes to the Go code and will be posting them as a PR, but I may need some help as I am not too familiar with Go.

### PR DESCRIPTION
**Pull request by BlenderDude**
**Description**

Fixes #3762 

This PR changes how the namespace applied in the release in the `skaffold.yaml` file is sent to Helm 3. It currently does not look for helm releases in the defined namespace, this PR applies the `--namespace` parameter to the helm calls, but only for Helm 3.

**User facing changes**

With Helm 3 supporting fully namespace'd releases, it would be expected that setting the namespace in the Skaffold release would make it deploy there. Currently this is only the case for the deployment step. For cleanup and getting the current lists of deployments, it does not apply the namespace. 

**Before**

Skaffold would successfully push the first version of the Helm release successfully. When tearing down, it would fail because the `delete` command did not have the namespace sent to it with the `--namespace` argument. When running Skaffold again, the un-deleted release would still exist, but it would not pick up on it because the function that gets the current releases did not apply the namespace properly either.

**After**

The normal workflow for skaffold is properly executed. Skaffold accesses the current helm releases in the namespace defined in the `skaffold.yaml` file. If it does not exist, it deploys to the namespace, or upgrades if it does. When tearing down, it properly deletes the release from the namespace.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Mentions any output changes.
- [x] Adds documentation as needed: user docs, YAML reference, CLI reference.
- [x] Adds integration tests if needed.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit test added.
- [ ] User facing changes look good.

**Release Notes**

This was a bug noticed before support for helm 3 was published, so I'm not sure anything needs to be added here.

### CODE REVIEW

**Comment by BlenderDude** [comment]
@nkubala  Here is the PR for the Helm 3 namespace issue. Some pointers on where to figure out the unit/integration testing would be appreciated!

**Comment by nkubala** [comment]
@BlenderDude thanks for the PR! `pkg/skaffold/deploy/helm_test.go` is where the helm unit tests live - you can add new test cases there. you'll probably want to update `TestHelmDeploy` or `TestHelmCleanup` to make sure that the commands are being issued with the provided namespace. you can add a field to the test struct, `namespace`, and then change the test call to pass the namespace to `makeRunContext` if you want:

```golang
func makeRunContext(deploy latest.HelmDeploy, force bool, namespace string) *runcontext.RunContext {
	pipeline := latest.Pipeline{}
	pipeline.Deploy.DeployType.HelmDeploy = &deploy
	ns := testNamespace
	if namespace != "" {
	  ns = namespace
	}

	return &runcontext.RunContext{
		Cfg:         pipeline,
		KubeContext: testKubeContext,
		Opts: config.SkaffoldOptions{
			Namespace:  ns,
			KubeConfig: testKubeConfig,
			Force:      force,
		},
	}
}

```

don't worry about integration tests for now. we're only testing helm 2 at the moment, I'm gonna need to make a bigger change to add support for helm 3 as well.

**Comment by BlenderDude** [comment]
@nkubala Sounds good, I'll get those implemented.

**Comment by BlenderDude** [comment]
@nkubala I have gotten the tests merged in. I added a new deploy config which includes a namespace to test against. These tests should have everything covered!

**Pull request merged**
