### PR TITLE
cut v0.28.0

### LINKED ISSUE #2028: Release v0.28.0

### PR DESCRIPTION
**Pull request by balopat**
Fixes #2028

### CODE REVIEW

**Comment by priyawadhwa** [comment]
I just merged #2016 a couple hours ago which upgraded to v1beta10 -- are we actually meant to be at v1beta9?

**Comment by corneliusweig** [comment]
@balopat Could it be that there were two schema versions for this release? `v1beta9` and `v1beta10`

**Comment by corneliusweig** [comment]
@priyawadhwa I think it should be `v1beta9`.

**Comment by priyawadhwa** [comment]
I think I made a mistake and upgraded to v1beta10 when it wasn't necessary -- let me see if I can revert that change.

**Pull request merged**
