### PR TITLE
feat: set kpt inventory configs for render and deploy 

### PR DESCRIPTION
**Pull request by yuwenma**
Fixes: #6494 #6389

**Description**
Per offline agreement, the inventory is changed from a deployment step to be a global flags that can be configured by both render and deploy. This allows Cloud Deploy to manage the inventory-based deployment in the render step so the releases and rollouts can share the same inventory(kpt deployment relies on inventory, and the inventory need to keep the same when deploying the same manifests in different machines)

If both the inventory flags and the inventory configs in skaffold.yaml are given, the inventory in skaffold.yaml should win.

### CODE REVIEW

**Comment by MarlonGamez** [comment]
@yuwenma that github action config can be found in [`.github/workflows/integration-darwin`](https://github.com/GoogleContainerTools/skaffold/blob/main/.github/workflows/integration-darwin.yml)

**Comment by briandealwis** [comment]
Maybe try the test to explicitly run `go test -short -timeout=60s ./pkg/skaffold/... ./cmd/... ./hack/... ./pkg/webhook/...` and see if that succeeds?  Maybe there's some different kind of `l.Action`?
https://github.com/GoogleContainerTools/skaffold/blob/d6551374d275cd659c5f70a7a29ddeb694aadc0f/hack/tests/main.go#L81

**Comment by briandealwis** [comment]
Tests are failing due to a panic 😮 
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff7032d70a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff7032d70a
stack: frame={sp:0x7ffeefbfe5f8, fp:0x7ffeefbfe648} stack=[0x7ffeefb7f698,0x7ffeefbfe700)
0x00007ffeefbfe4f8:  0x01007ffeefbfe518  0x0000000000000004 
0x00007ffeefbfe508:  0x000000000000001f  0x00007fff7032d70a 
0x00007ffeefbfe518:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbfe528:  0x0000000004037b71 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe5c8 
0x00007ffeefbfe538:  0x0000000005a53176  0x00007ffeefbfe580 
0x00007ffeefbfe548:  0x0000000004037e28 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006e88800 
0x00007ffeefbfe558:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbfe568:  0x00007ffeefbfe5c8  0x0000000004037b71 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe578:  0x0000000006e88800  0x00007ffeefbfe5b8 
0x00007ffeefbfe588:  0x0000000004037db0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfe598 
0x00007ffeefbfe598:  0x0000000004037de0 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006e88800 
0x00007ffeefbfe5a8:  0x0000000004037b71 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe5c8 
0x00007ffeefbfe5b8:  0x00007ffeefbfe5e8  0x0000000004037b71 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe5c8:  0x00007ffeefbfe5d0  0x0000000004037ba0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbfe5d8:  0x0000000005a6e72d  0x000000000000002a 
0x00007ffeefbfe5e8:  0x00007ffeefbfe638  0x000000000404e036 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbfe5f8: <0x0000000005a6e72d  0x0000000006e88800 
0x00007ffeefbfe608:  0x00007ffeefbfe678  0x0000000004028aa6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbfe618:  0x000000c00066e548  0x00000000054c8619 <github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withFallbackConfig+0x0000000000000079> 
0x00007ffeefbfe628:  0x000000c0001031e0  0x00007fff963cfef0 
0x00007ffeefbfe638:  0x00007ffeefbfe680 !0x00007fff7032d70a 
0x00007ffeefbfe648: >0x00007ffeefbfe680  0x0000000006da4000 
0x00007ffeefbfe658:  0x0000000000000629  0x00000000047035c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbfe668:  0x000000000406d03f <runtime.syscall+0x000000000000001f>  0x000000c0006bee38 
0x00007ffeefbfe678:  0x000000000406c9ac <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0006bee08 
0x00007ffeefbfe688:  0x000000000406ae70 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbfe6c0 
0x00007ffeefbfe698:  0x000000000400fc2e <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000030 
0x00007ffeefbfe6a8:  0x0000000000000000  0x0000000006ec03e0 
0x00007ffeefbfe6b8:  0x0000000000003220  0x000000c0001031e0 
0x00007ffeefbfe6c8:  0x000000000406906b <runtime.morestack+0x000000000000008b>  0x0000000000000004 
0x00007ffeefbfe6d8:  0x0000000005da2888  0x0000000006e88800 
0x00007ffeefbfe6e8:  0x00007ffeefbfe730  0x0000000004068e85 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbfe6f8:  0x0000000004068e3d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x5a6e72d, 0x6e88800})
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff7032d70a
stack: frame={sp:0x7ffeefbfe5f8, fp:0x7ffeefbfe648} stack=[0x7ffeefb7f698,0x7ffeefbfe700)
0x00007ffeefbfe4f8:  0x01007ffeefbfe518  0x0000000000000004 
0x00007ffeefbfe508:  0x000000000000001f  0x00007fff7032d70a 
0x00007ffeefbfe518:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbfe528:  0x0000000004037b71 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe5c8 
0x00007ffeefbfe538:  0x0000000005a53176  0x00007ffeefbfe580 
0x00007ffeefbfe548:  0x0000000004037e28 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006e88800 
0x00007ffeefbfe558:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbfe568:  0x00007ffeefbfe5c8  0x0000000004037b71 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe578:  0x0000000006e88800  0x00007ffeefbfe5b8 
0x00007ffeefbfe588:  0x0000000004037db0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfe598 
0x00007ffeefbfe598:  0x0000000004037de0 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006e88800 
0x00007ffeefbfe5a8:  0x0000000004037b71 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe5c8 
0x00007ffeefbfe5b8:  0x00007ffeefbfe5e8  0x0000000004037b71 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe5c8:  0x00007ffeefbfe5d0  0x0000000004037ba0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbfe5d8:  0x0000000005a6e72d  0x000000000000002a 
0x00007ffeefbfe5e8:  0x00007ffeefbfe638  0x000000000404e036 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbfe5f8: <0x0000000005a6e72d  0x0000000006e88800 
0x00007ffeefbfe608:  0x00007ffeefbfe678  0x0000000004028aa6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbfe618:  0x000000c00066e548  0x00000000054c8619 <github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withFallbackConfig+0x0000000000000079> 
0x00007ffeefbfe628:  0x000000c0001031e0  0x00007fff963cfef0 
0x00007ffeefbfe638:  0x00007ffeefbfe680 !0x00007fff7032d70a 
0x00007ffeefbfe648: >0x00007ffeefbfe680  0x0000000006da4000 
0x00007ffeefbfe658:  0x0000000000000629  0x00000000047035c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbfe668:  0x000000000406d03f <runtime.syscall+0x000000000000001f>  0x000000c0006bee38 
0x00007ffeefbfe678:  0x000000000406c9ac <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0006bee08 
0x00007ffeefbfe688:  0x000000000406ae70 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbfe6c0 
0x00007ffeefbfe698:  0x000000000400fc2e <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000030 
0x00007ffeefbfe6a8:  0x0000000000000000  0x0000000006ec03e0 
0x00007ffeefbfe6b8:  0x0000000000003220  0x000000c0001031e0 
0x00007ffeefbfe6c8:  0x000000000406906b <runtime.morestack+0x000000000000008b>  0x0000000000000004 
0x00007ffeefbfe6d8:  0x0000000005da2888  0x0000000006e88800 
0x00007ffeefbfe6e8:  0x00007ffeefbfe730  0x0000000004068e85 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbfe6f8:  0x0000000004068e3d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 88 [syscall]:
syscall.syscall(0x47035c0, 0x2, 0x40487413, 0xc0006beec8)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/runtime/sys_darwin.go:22 +0x3b fp=0xc0006bee38 sp=0xc0006bee18 pc=0x406787b
syscall.syscall(0xf03fbf0, 0x8000, 0x4, 0xc0006bef10)
	<autogenerated>:1 +0x26 fp=0xc0006bee80 sp=0xc0006bee38 pc=0x406d846
golang.org/x/sys/unix.ioctl(0x4075c5e, 0x6bef20, 0x64)
	/Users/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20210228012217-479acdf4ea46/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc0006beeb0 sp=0xc0006bee80 pc=0x4703019
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20210228012217-479acdf4ea46/unix/ioctl.go:73
github.com/sirupsen/logrus.isTerminal(0x8)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/terminal_check_bsd.go:11 +0x50 fp=0xc0006bef20 sp=0xc0006beeb0 pc=0x470d2d0
github.com/sirupsen/logrus.checkIfTerminal({0x5dbc760, 0xc000010020})
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/terminal_check_notappengine.go:13 +0x75 fp=0xc0006bef38 sp=0xc0006bef20 pc=0x470d375
github.com/sirupsen/logrus.(*TextFormatter).init(0xc00009f140, 0xecde948)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/text_formatter.go:106 +0x34 fp=0xc0006befb8 sp=0xc0006bef38 pc=0x470d454
github.com/sirupsen/logrus.(*TextFormatter).Format.func1()
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/text_formatter.go:196 +0x25 fp=0xc0006befd8 sp=0xc0006befb8 pc=0x470eb05
sync.(*Once).doSlow(0x5dec420, 0xc000629368)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/sync/once.go:68 +0xd2 fp=0xc0006bf040 sp=0xc0006befd8 pc=0x4075792
sync.(*Once).Do(...)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/sync/once.go:59
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00009f140, 0xc0001fe150)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/text_formatter.go:196 +0xebe fp=0xc0006bf5b0 sp=0xc0006bf040 pc=0x470e4be
github.com/sirupsen/logrus.(*Entry).write(0xc0001fe150)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:279 +0x56 fp=0xc0006bf640 sp=0xc0006bf5b0 pc=0x47086f6
github.com/sirupsen/logrus.(*Entry).log(0xc0006bf708, 0x4, {0xc0007065f0, 0x4d})
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:251 +0x219 fp=0xc0006bf6b0 sp=0xc0006bf640 pc=0x47082f9
github.com/sirupsen/logrus.(*Entry).Log(0xc0001fe070, 0x4, {0xc0006bf708, 0x1, 0x1})
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f fp=0xc0006bf6e0 sp=0xc0006bf6b0 pc=0x470894f
github.com/sirupsen/logrus.(*Entry).Logf(0xc0001fe070, 0x4, {0x5a5a323, 0x6}, {0xc0006bf7c0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0x85 fp=0xc0006bf728 sp=0xc0006bf6e0 pc=0x4708ea5
github.com/sirupsen/logrus.(*Logger).Logf(0xc0001b7340, 0x4, {0x5a5a323, 0x22}, {0xc0006bf7c0, 0x1, 0x1})
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:151 +0x85 fp=0xc0006bf778 sp=0xc0006bf728 pc=0x470af05
github.com/sirupsen/logrus.(*Logger).Infof(...)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:165
github.com/sirupsen/logrus.Infof(...)
	/Users/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:199
github.com/GoogleContainerTools/skaffold/pkg/skaffold/util.ReadConfiguration({0xc000219a90, 0xd})
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/util/config.go:43 +0x179 fp=0xc0006bf7e0 sp=0xc0006bf778 pc=0x47ab079
github.com/GoogleContainerTools/skaffold/pkg/skaffold/schema.ParseConfig({0xc000219a90, 0x0})
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/schema/versions.go:189 +0x25 fp=0xc0006bf860 sp=0xc0006bf7e0 pc=0x5488cc5
github.com/GoogleContainerTools/skaffold/pkg/skaffold/schema.ParseConfigAndUpgrade({0xc000219a90, 0x2})
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/schema/versions.go:206 +0x25 fp=0xc0006bf8b0 sp=0xc0006bf860 pc=0x5488e25
github.com/GoogleContainerTools/skaffold/pkg/skaffold/parser.getConfigs({{0xc000219a90, 0xd}, {0x0, 0x0, 0x0}, {0x6eb90c0, 0x0, 0x0}, 0x0, 0x0}, ...)
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/parser/config.go:100 +0x49 fp=0xc0006bfe48 sp=0xc0006bf8b0 pc=0x548e109
github.com/GoogleContainerTools/skaffold/pkg/skaffold/parser.GetConfigSet({0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, ...})
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/parser/config.go:81 +0x2a5 fp=0xc0006c0548 sp=0xc0006bfe48 pc=0x548df85
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withFallbackConfig({_, _}, {0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x1, 0x0, ...}, ...)
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/runner.go:102 +0x79 fp=0xc0006c0eb0 sp=0xc0006c0548 pc=0x54c8619
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runContext({_, _}, {0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x1, 0x0, ...})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/runner.go:76 +0x7f fp=0xc0006c1410 sp=0xc0006c0eb0 pc=0x54c809f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.createNewRunner({_, _}, {0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x1, 0x0, ...})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/runner.go:61 +0x78 fp=0xc0006c16d8 sp=0xc0006c1410 pc=0x54c7e78
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner({0x5dfaab0, 0xc0000520a8}, {0x5dbc760, 0xc000010018}, 0xc0006c19e8)
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/runner.go:49 +0x9c fp=0xc0006c1968 sp=0xc0006c16d8 pc=0x54c7d3c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev({0x5dfaab0, 0xc0000520a8}, {0x5dbc760, 0xc000010018})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/dev.go:63 +0x1f3 fp=0xc0006c1a40 sp=0xc0006c1968 pc=0x54c2eb3
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDebug({0x5dfaab0, 0xc0000520a8}, {0x5dbc760, 0xc000010018})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/debug.go:53 +0xf8 fp=0xc0006c1a90 sp=0xc0006c1a40 pc=0x54c2bf8
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.NewCmdDebug.func1({0x5dfaab0, 0xc0000520a8}, {0x5dbc760, 0xc000010018})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/debug.go:46 +0x34 fp=0xc0006c1ac0 sp=0xc0006c1a90 pc=0x54d29b4
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00013d400, {0xc00072f4c0, 0x0, 0x4})
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/commands.go:129 +0x6a fp=0xc0006c1b18 sp=0xc0006c1ac0 pc=0x54c264a
github.com/spf13/cobra.(*Command).execute(0xc00013d400, {0xc00004e0b0, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e fp=0xc0006c1bd8 sp=0xc0006c1b18 pc=0x41f3f4e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013d400)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad fp=0xc0006c1c90 sp=0xc0006c1bd8 pc=0x41f45ad
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.TestNewCmdDebug.func1(0xc0007320e0)
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/debug_test.go:38 +0xb8 fp=0xc0006c1f48 sp=0xc0006c1c90 pc=0x54d3098
github.com/GoogleContainerTools/skaffold/testutil.Run.func1(0xc000711040)
	/Users/runner/work/skaffold/skaffold/testutil/util.go:235 +0x59 fp=0xc0006c1f70 sp=0xc0006c1f48 pc=0x54b1e59
testing.tRunner(0xc000711040, 0xc0003ff260)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x102 fp=0xc0006c1fc0 sp=0xc0006c1f70 pc=0x4111442
testing.(*T).Run·dwrap·21()
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x2a fp=0xc0006c1fe0 sp=0xc0006c1fc0 pc=0x411214a
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0006c1fe8 sp=0xc0006c1fe0 pc=0x406b161
created by testing.(*T).Run
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x35a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0005024e0, {0x5a2dd01, 0x9b8a5680a3}, 0x5c01570)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc0005024e0)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc0005024e0, 0xc00089fd18)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x102
testing.runTests(0xc000139b80, {0x6e68b00, 0x27, 0x27}, {0x408af6d, 0x5a2cbd1, 0x6e875e0})
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc000139b80)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1504 +0x51d
main.main()
	_testmain.go:119 +0x14b

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
	/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:417 +0xfb

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000510400)
	/Users/runner/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/Users/runner/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x92

goroutine 10 [chan receive]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.newHandler.func1()
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/event/v2/event.go:58 +0x48
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.newHandler
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/event/v2/event.go:56 +0xa7

goroutine 87 [chan receive]:
testing.(*T).Run(0xc000710ea0, {0x5a2dd01, 0x9b8aa14ed0}, 0xc0003ff260)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1307 +0x375
github.com/GoogleContainerTools/skaffold/testutil.Run(0xc000710ea0, {0x0, 0xc000071760}, 0x5c01568)
	/Users/runner/work/skaffold/skaffold/testutil/util.go:234 +0x93
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.TestNewCmdDebug(0xc000710680)
	/Users/runner/work/skaffold/skaffold/cmd/skaffold/app/cmd/debug_test.go:32 +0x25
testing.tRunner(0xc000710ea0, 0x5c01570)
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/Users/runner/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x35a

goroutine 12 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/Users/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/Users/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5

goroutine 13 [chan receive]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event.newHandler.func1()
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/event/event.go:59 +0x45
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/event.newHandler
	/Users/runner/work/skaffold/skaffold/pkg/skaffold/event/event.go:57 +0xa7

goroutine 14 [chan receive]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc00004e910)
	/Users/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_recursive.go:125 +0x4d
created by github.com/rjeczalik/notify.newRecursiveTree
	/Users/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_recursive.go:119 +0x15b

goroutine 15 [syscall, locked to thread]:
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:229 +0x45
github.com/rjeczalik/notify.init.1.func1()
	/Users/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/watcher_fsevents_cgo.go:72 +0x45
created by github.com/rjeczalik/notify.init.1
	/Users/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/watcher_fsevents_cgo.go:64 +0x33
FAIL	github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd	0.806s
```

**Comment by yuwenma** [comment]
Some updates:
1. The `make quicktest` or its equivelance `go test -short -timeout=60s ./pkg/skaffold/... ./cmd/... ./hack/... ./pkg/webhook/...`  pass in local (darwin, Go1.16)
2. I tried running on go1.14 which is what the PR integration test's environment. No panic, so I guess that's a flaky.

**Comment by yuwenma** [comment]
> Some updates:
> 
> 1. The `make quicktest` or its equivelance `go test -short -timeout=60s ./pkg/skaffold/... ./cmd/... ./hack/... ./pkg/webhook/...`  pass in local (darwin, Go1.16)
> 2. I tried running on go1.14 which is what the PR integration test's environment. No panic, so I guess that's a flaky.

(Not sure how this is setup) But by reading the integration test log, it looks like the test is actually  running against [/Users/runner/hostedtoolcache/go/1.17.2/x64](https://github.com/GoogleContainerTools/skaffold/runs/4122413747?check_suite_focus=true#step:6:5)

Tried running go1.17.10 locally and I got the same panic.

**Comment by yuwenma** [comment]
@briandealwis @nkubala Just FYI, here's the panic cause https://github.com/golang/go/issues/46763

**Comment by yuwenma** [comment]
Bumped the golang.org/x/sys and the tests pass in 1.17.10.

**Review by MarlonGamez — APPROVED** [review]
looks good to me 👍🏼 thanks for resolving the issues here

**Pull request merged**
