### PR TITLE
Validate changed examples with "local" builder

### PR DESCRIPTION
**Pull request by briandealwis**
Use Github Actions workflow for very loose validation of changes to our examples.

Example: https://github.com/GoogleContainerTools/skaffold/pull/6133/checks?check_run_id=3602112277

### CODE REVIEW

**Comment by briandealwis** [comment]
Blocked by #6134

**Comment by briandealwis** [comment]
Example: https://github.com/GoogleContainerTools/skaffold/pull/6133/checks?check_run_id=3601990260

**Review by gsquared94 — APPROVED** [review]
lgtm. Is there a sample run where any examples changed?

**Comment by briandealwis** [comment]
Yup: https://github.com/GoogleContainerTools/skaffold/pull/6133/checks?check_run_id=3602112277

**Comment by briandealwis** [comment]
Marking for triage/discuss: perhaps we should be building all of the examples to verify we haven't broken anything.

**Pull request merged**
