### PR TITLE
@ #1379 | Bug fix for Helm imageStrategy file sync

### PR DESCRIPTION
**Pull request by hoatle**
fix for #1379

### CODE REVIEW

**Comment by hoatle** [comment]
I signed it!

**Comment by dgageot** [comment]
Hi @hoatle! Do you need some help to finish this PR?

**Comment by hoatle** [comment]
Hi @balopat @dgageot,
I added the example of helm deployment with hot reload.
- Before the fix:

```
...
Deploy complete in 977.47843ms
Watching for changes every 1s...
Syncing 1 files for docker.io/hoatle/gcr_io_k8s-skaffold_skaffold-helm-hot-reload:v0.31.0-35-gfb352b22-dirty@sha256:97f09bbb1956c3036c09555bae229d61f5bb546145e205c8dcc3130db4cb1445
WARN[0028] Skipping deploy due to sync error: copying files: didn't sync any files 
Watching for changes every 1s...
```

- After the fix:

```
...
Deploy complete in 1.002408729s
Watching for changes every 1s...
Syncing 1 files for docker.io/hoatle/gcr_io_k8s-skaffold_skaffold-helm-hot-reload:v0.31.0-35-gfb352b22-dirty@sha256:1eaf3b3dfc86552be2cea541bd3983096a6ac074007c0a1252c34bc46e47848d
Watching for changes every 1s...
```

I hope that the example will help to clarify the problem.

**Comment by georgekarrv** [comment]
:+1: would love to have this in a release

**Comment by dgageot** [comment]
Hi @hoatle since you added a sample to the `examples` directory, you should also make sure that a copy of it is added to `integration/examples`. The version in `examples` should use the latest released version of the schema. The version in `integration/examples` should use the future schema version.

**Comment by dgageot** [comment]
@hoatle any chance you could update this PR?

**Comment by tejal29** [comment]
@hoatle, this got fixed in #1379

**Comment by tejal29** [comment]
closing due to inactivity. Also the code change was fixed in another PR

**Pull request closed without merging**
