### PR TITLE
Disable profiles with the command line

### LINKED ISSUE #3988: Explicit deactivation of profile via CLI argument
Is there a way to explicitly disable a profile that may have been automatically activated?

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #3988

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by pierreyves-lebrun** [comment]
How does that work?

Things like `skaffold dev -p db,-dev` or `skaffold dev -p db -p dev` fail.

**Comment by briandealwis** [comment]
You can use multiple `-p` arguments, and/or provide a comma-separated list.

I tried the Skaffold [`examples/profiles`](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/profiles) project.  I use a minikube cluster, so the normal build would automatically activate the `minikube-profile` and so Skaffold will build `skaffold-world`:
```console
$ skaffold build
Generating tags...
 - skaffold-hello -> skaffold-hello:v1.12.0-37-g6af3198f3
Checking cache...
 - skaffold-hello: Not found. Building
Found [minikube] context, using local docker daemon.
Building [skaffold-hello]...
```

I explicitly disable both the `staging-profile` (which was never active anyways) and the `minikube-profile`, then I see the `skaffold-world` project is built, as expected:
```console
$ skaffold build -p -staging-profile,-minikube-profile
Generating tags...
 - skaffold-world -> skaffold-world:v1.12.0-37-g6af3198f3
Checking cache...
 - skaffold-world: Not found. Building
Found [minikube] context, using local docker daemon.
Building [skaffold-world]...
```

And with separate `-p` arguments:
```console
$ skaffold build -p -minikube-profile -p -staging-profile 
Generating tags...
 - skaffold-world -> skaffold-world:v1.12.0-37-g6af3198f3
Checking cache...
 - skaffold-world: Not found. Building
Found [minikube] context, using local docker daemon.
Building [skaffold-world]...
```

**Comment by pierreyves-lebrun** [comment]
@briandealwis Thanks for confirming.

It seems profiles prefixed with `-` cause Skaffold to generate invalid manifests.

Below is the error I am getting when running things like`skaffold dev -p db,-dev`:
```
 - Error from server (Invalid): error when creating "STDIN": Service "db" is invalid: metadata.labels: Invalid value: "-dev": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
 - Error from server (Invalid): error when creating "STDIN": Deployment.apps "db" is invalid: [metadata.labels: Invalid value: "-dev": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.template.labels: Invalid value: "-dev": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
Cleaning up...
exiting dev mode because first deploy failed: kubectl error: kubectl apply: exit status 1
```

**Comment by briandealwis** [comment]
@pierreyves-lebrun could you please open a new issue, link to this issue, and include your `skaffold.yaml` so that we can reproduce?

**Pull request merged**
