### PR TITLE
Update the brew formula to 0.5.0

### PR DESCRIPTION
**Pull request by tuananh**
Update the brew formula to 0.5.0

### CODE REVIEW

**Comment by tuananh** [comment]
I signed it!

**Comment by dgageot** [comment]
Should be signed now

**Comment by tuananh** [comment]
I signed it!

**Comment by dgageot** [comment]
@tuananh Can you double check you did actually signed the CLA?

**Comment by tuananh** [comment]
@dgageot in my other PR, it's signed https://github.com/GoogleContainerTools/skaffold/pull/520

**Comment by dgageot** [comment]
Could you try to close it and open it again?

**Comment by dgageot** [comment]
Merged with https://github.com/GoogleContainerTools/skaffold/pull/522

**Pull request closed without merging**
