### PR TITLE
Bump golangci-lint to v1.19.1

### PR DESCRIPTION
**Pull request by corneliusweig**
**Description**

Bump golangci-lint to v0.19.1. I realized that in the previous PR I forgot to adjust the version and only fixed the issues from the new linter version :man_facepalming:. 

**User facing changes**

n/a

**Before**
n/a

**After**

n/a

**Next PRs.**

n/a

**Submitter Checklist**

n/a

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Mentions any output changes.
- [ ] Adds documentation as needed: user docs, YAML reference, CLI reference.
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a example to the `examples` dir](https://github.com/GoogleContainerTools/skaffold/tree/master/examples), please copy them to [`integration/examples`](https://github.com/GoogleContainerTools/skaffold/tree/master/integration/examples)
- Every new example added in [`integration/examples` dir](https://github.com/GoogleContainerTools/skaffold/tree/master/integration/examples), should be tested in [integration test](https://github.com/GoogleContainerTools/skaffold/tree/master/integration)

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit test added.
- [ ] User facing changes look good.

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Hey @corneliusweig, looks like tests failed because golangci-lint ran out of memory:

```
Installing GolangCI-Lint
golangci/golangci-lint info checking GitHub for tag 'v1.19.1'
golangci/golangci-lint info found version: 1.19.1 for v1.19.1/linux/amd64
golangci/golangci-lint info installed /home/travis/gopath/bin/golangci-lint
INFO [config_reader] Used config file hack/golangci.yml 
INFO [lintersdb] Active 20 linters: [bodyclose deadcode goconst gocritic goimports golint gosimple govet ineffassign interfacer maligned misspell staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck] 
INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused stylecheck] into metalinter megacheck 
INFO [loader] Go packages loading at mode 1023 (exports_file|files|name|types|types_info|compiled_files|imports|syntax|types_sizes|deps) took 5m19.577172535s 
INFO [loader] SSA repr building timing: packages building 607.769104ms, total 8.533377941s 
INFO Memory: 3026 samples, avg is 97.1MB, max is 2826.7MB 
INFO Execution took 6m0.984859028s                
INFO [runner] worker.2 took 38.160513962s with stages: golint: 25.465445897s, goimports: 7.793151868s, gocritic: 2.813798061s, unparam: 2.088080271s 
fatal error: runtime: out of memory
```

we could try tweaking the [GOGC](https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint) env variable as suggested in this [comment](https://github.com/golangci/golangci-lint/issues/483#issuecomment-485235916)?

**Comment by corneliusweig** [comment]
Thanks @priyawadhwa for investigating this!
I also noticed quite excessive memory usage when running this locally. Let's see how a setting of 50 works.

**Comment by priyawadhwa** [comment]
Looks like it's still failing, we probably have to go lower. It turns out that Minikube ran into the same issue, and sets [these variables](https://github.com/kubernetes/minikube/blob/master/Makefile#L54-L58) for the linter to work with their CI, so we could try some combination of these as well. 

According to the [travis docs](https://docs.travis-ci.com/user/reference/overview/) we should have 7.5 GB of memory, but looks like >8 is required a lot of the time based on [this thread](https://github.com/golangci/golangci-lint/issues/337) :(

**Comment by corneliusweig** [comment]
I've reduced the setting one step further. Apparently, v0.19 makes the memory footprint a lot worse. So if this doesn't work reliably now, I'll close this and wait for the next release. They are actively working to reduce the memory consumption again.

**Comment by priyawadhwa** [comment]
Different error this time!

```
./hack/linter.sh: line 35: GOLINT_JOBS: command not found
FAILED hack/linter.sh
```

it might need to be
```shell
GOLINT_JOBS=4
```
or something like that

**Comment by corneliusweig** [comment]
So I don't think it makes sense to upgrade to v0.19.x  at the moment, given the memory issues with that version. I'll try again with the next release.

**Pull request closed without merging**
