### PR TITLE
Experimental UI mode for `skaffold dev`

### PR DESCRIPTION
**Pull request by dgageot**
Please have a try and tell me what you think about it!

### CODE REVIEW

**Comment by dgageot** [comment]
@balopat I'll try to see how this can be improved. I was thinking we could merge this code if an experimental flag can be used to activate this UI. wdyt?

**Comment by balopat** [comment]
I'm okay having behind an experimental flag!

**Comment by dgageot** [comment]
@balopat should be good to review then

**Comment by tjerkw** [comment]
This feature is broken for me:

skaffold dev --experimental-gui
FATA[0034] exiting dev mode because first run failed: build failed: building [quay.io/tiqets/tiqetsweb-solr]: build artifact: running build: signal: broken pipe

I'm also expected a proper GUI. But this is just a text-interface :p

**Comment by josefkorbel** [comment]
I really like it to be honest, good work! Having problems only with scrolling (history loss) as mentioned before.

**Pull request merged**
