### PR TITLE
Update Jib plugin versions to 3.1.4

### PR DESCRIPTION
**Pull request by chanseokoh**
Jib plugins 3.1.4 released this week.

### CODE REVIEW

**Comment by chanseokoh** [comment]
@GoogleContainerTools/skaffold-team tests are passing, except one of the GitHub Actions tests. Can you re-run it?

**Comment by ahmetb** [comment]
@chanseokoh TestDebug/buildpacks flake for this was fixed in `main`, please rebase.

**Comment by chanseokoh** [comment]
Still flaky though.

**Comment by ahmetb** [comment]
TestRunPortForward is another flake being fixed as part of #6460.

**Pull request merged**
