### PR TITLE
Add verbosity flag to go tests on travis

### PR DESCRIPTION
**Pull request by loosebazooka**

### CODE REVIEW

**Comment by tejal29** [comment]
The flag only got applied to windows tests. Is there a reason for adding the `-v` flag ?

**Comment by loosebazooka** [comment]
AFAIK, the `-v` flag prints out the reason the test failed (rather than just saying the test failed), this is nice for people who cannot mimic the test environment easy (ex: I do not have a mac to test mac failures on).

**Comment by tejal29** [comment]
> AFAIK, the `-v` flag prints out the reason the test failed (rather than just saying the test failed), this is nice for people who cannot mimic the test environment easy (ex: I do not have a mac to test mac failures on).
> 
> It should apply to all test environments.

Ahh got it. Thanks!

**Comment by tejal29** [comment]
The linux job still does not have `-v` flag
https://travis-ci.com/GoogleContainerTools/skaffold/jobs/278134461#L236
Rest all (windows, OSX and integration test) have `-v` flag.

**Comment by tejal29** [comment]
Can you also add `-v` to coverage target used for linux profile.
https://github.com/GoogleContainerTools/skaffold/blob/master/Makefile#L111

**Comment by loosebazooka** [comment]
Do we want it on coverage right? I put it on https://github.com/GoogleContainerTools/skaffold/blob/master/Makefile#L106 instead.

**Comment by loosebazooka** [comment]
oh no you're right, needs to go on coverage.

**Pull request merged**
