### PR TITLE
[WIP] Single channel

### PR DESCRIPTION
**Pull request by balopat**
experiment

### CODE REVIEW

**Comment by tejal29** [comment]
i am going to take another stab and update what i have in mind.

**Comment by tejal29** [comment]
@balopat i added this commit https://github.com/GoogleContainerTools/skaffold/pull/2091/commits/99a4da97d3aac6173fa7ba32de7b69a262102e4e, 
Where the signature of Builder is different than what you have, 
1. The runner provides a channel to right too
2. The builder just sends artifacts to these channels as they are built
VS 
the current design where the Builder returns a single channel.

Thanks

**Comment by balopat** [comment]
I'm not sure I agree with this change @tejal29 - this creates 2 ways to return the same information: through the channel and as the return slice. I find that confusing.

**Comment by balopat** [comment]
After multiple days invested in this direction I still feel that it is not worthwhile to go down this direction: the complexity of adding go channels adds a lot of complexity and the design more error prone for subtle bugs. The current arguments for going towards this direction is the Event API redesign to centralize event management in the Runner. This in itself is a valuable idea but at this point the current design is simpler to reason about this new design with the go channels, plus if we want to extend the events sent by builders, e.g. progress bar events, we will have to send data through the go channels anyway that represents those events and convert them to events, or directly call the `event` package - at which point the complexity of "handling events from the builders" is going to be the same. 
I am open to introduce a streaming/reactive design in Skaffold on the long run if we have a strong enough argument/featureset for it. For this redesign I don't see that it is worthwhile. I am closing this and the related PRs.

**Pull request closed without merging**
