### PR TITLE
brew install skaffold

### PR DESCRIPTION
**Pull request by cedricvidal**
Proposing to add `brew install skaffold` installation method to README

### CODE REVIEW

**Comment by dgageot** [comment]
Hello @cedricvidal, thanks for the PR! I'm afraid you need to both rebase your code and sign the CLA before we can merge.

**Comment by cedricvidal** [comment]
You're welcome @dgageot , that's weird, I signed it already, I'll try again.

**Comment by cedricvidal** [comment]
ok ... lol, at exactly the same time I reply, the @googlebot acknowledges my CLA ^^

**Comment by cedricvidal** [comment]
@dgageot rebased

**Pull request merged**
