### PR TITLE
Use ParseTolerant to parse Helm version because of missing patch version

### PR DESCRIPTION
**Pull request by bdudelsack**
Fixes: #4711 

**Description**

Use semVer ParseTolerant version to parse the Helm binary version because it does not follow all semver rules.

### CODE REVIEW

**Comment by bdudelsack** [comment]
@googlebot I signed it!

**Comment by bdudelsack** [comment]
Added the tests for helm v3.3. 

The official binaries from helm do output the semver compliant version number, but custom built do not. For example Manjaro has a custom buit helm version in their repository which outputs not semver compliant version number.

**Comment by kudlatyamroth** [comment]
When we can expect release with this fix?

**Comment by briandealwis** [comment]
We're aiming to have a release on Wednesday.  You can use the ["bleeding edge" binaries](https://skaffold.dev/docs/install/) — we typically cut our releases from HEAD.

**Pull request merged**
