### PR TITLE
fix: add default value for status-check flag when no value is specified

### PR DESCRIPTION
**Pull request by MarlonGamez**
Fixes problem addressed here: https://github.com/GoogleContainerTools/skaffold/pull/7089/files#r845391034

`--status-check` can now be used without specifying `={true|false}`

### CODE REVIEW

**Review by briandealwis — COMMENTED** [review]
Can we add a test for this?

**Comment by MarlonGamez** [comment]
@briandealwis Yes, do you think we should add a test for all NoOptDefValue flags?

**Review by tejal29 — APPROVED** [review]

**Comment by briandealwis** [comment]
This flag broke downstream consumers, so it seems worthy of some tests to ensure it doesn't happen again.

**Comment by MarlonGamez** [comment]
@briandealwis I included a test in this PR to ensure that skaffold runs with these flags passed in with no value 👍🏼

**Comment by byCedric** [comment]
Can we please leave this now as is, thanks for adding tests to make sure this doesn't break again. But now our pipeline broke twice:
1. For the previous change that added `--status-check {true,false}` - PR #7089
2. For this change that broke `--status-check true` - https://github.com/expo/snack/runs/7411459432?check_suite_focus=true#step:9:11

**Pull request merged**
