### PR TITLE
Kaniko secret

### PR DESCRIPTION
**Pull request by prary**
kaniko pull secret should be optional
Resolving issue #2190

### CODE REVIEW

**Comment by prary** [comment]
This is how it should be right? 
```
func setupPullSecret() {
	if b.PullSecret == "" {
		return func() {}, nil
        }
        rest of the secret creation code
}
```

**Comment by dgageot** [comment]
@prary could you add a unit test for the new code?

**Comment by prary** [comment]
> @prary could you add a unit test for the new code?

Sure I will add

**Comment by tejal29** [comment]
@prary, Here is an example of creating a mock client and adding secrets

https://github.com/GoogleContainerTools/skaffold/blob/6ed64d6d7ee85aa5538c85eb9ba61df20bac5795/pkg/skaffold/deploy/status_check_test.go#L180
```
// Create Secrets	
		objs := make([]runtime.Object, len(test.secrets))
			for i, s := range test.secrets {
				objs[i] = dep
			}
// Create a fake client with Secrets added
			client := fakekubeclientset.NewSimpleClientset(objs...)
// Pass the fake client to the method using it

actual, err := getDeployments(client, "test", labeller, time.Duration(200)*time.Second)

```

**Comment by tejal29** [comment]
In your case, you need to mock the function call to `kubernetes.GetClientset()` to actually return the fakeclient.

**Comment by tejal29** [comment]
I think @dgageot covered this https://github.com/GoogleContainerTools/skaffold/pull/2321

**Pull request closed without merging**
