### PR TITLE
issue #5076 config related changes for new version

### PR DESCRIPTION
**Pull request by rpunia7**
Fixes: #5076  
**Related**: https://github.com/GoogleContainerTools/skaffold/pull/5078
**Merge before**: https://github.com/GoogleContainerTools/skaffold/pull/5078

**Description**

config related changes as L25 in below file has warning
[pkg/skaffold/schema/latest/config.go](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/latest/config.go#L25)
// !!! WARNING !!! This config version is already released, please DO NOT MODIFY the structs in this file.

### CODE REVIEW

**Comment by anshlykov** [comment]
Duplicate of #5071

**Comment by tejal29** [comment]
This is no longer needed @rpunia7 as We had a #5071 in the review pipeline which i just merged

**Comment by rpunia7** [comment]
> This is no longer needed @rpunia7 as We had a #5071 in the review pipeline which i just merged

thanks @tejal29 i'll get the latest code and update my other PR which is referencing this

**Comment by rpunia7** [comment]
> Duplicate of #5071

my bad I didn't realize this, thanks for the heads up @anshlykov

**Pull request closed without merging**
