### PR TITLE
Add 'skaffold render' to output templated k8s manifests without deploying

### LINKED ISSUE #1187: Ability to takeout the processed kubernetes YAML file
I think "skaffold build" command should allow doing something like:

```
skaffold build \
    --build-receipt out.json \
    --kubectl-manifests manifests.yaml
```

So I can actually decide whether I want to apply the `manifests.yaml` myself. Similarly, I can use `out.json` to parse out the built artifacts and store their names/tags for my own purposes.

Right now, "skaffold {build,run}" outputs aren't very usable. There should be a contract for those willing to parse output –or flags like this saving the results to a file.

This would solve #922 as well if the produced `--build-receipt` and `--kubectl-manifests` could be fed back into `skaffold deploy` command.

### PR DESCRIPTION
**Pull request by nkubala**
This adds a new command, `skaffold render`, which runs builds for all artifacts, tags the images, and then outputs the templated kubernetes manifests to the user rather than actually running the deploy. The manifests are written to stdout by default, but a `--output` flag can be passed to provide a filename for them to be written to. These manifests can be manually applied by the user if desired, or committed to a repository for use in CI/CD or GitOps workflows.

This also adds a flag, `--render-only` to `skaffold dev` and `skaffold run`, which will exhibit the same behavior as `skaffold render` (though in dev mode it will continuously print the templated manifests after each successful build).

By default, the logs and output for the builds are suppressed, but can be displayed using a `--loud` flag.

## Output Changes

```
➜  skaffold render
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v0.37.0-297-g28e6a784f
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kubectl
    skaffold.dev/docker-api-version: "1.39"
    skaffold.dev/run-id: 908b2b48-9ad6-43d9-8836-13fd17aac9c6
    skaffold.dev/tag-policy: git-commit
    skaffold.dev/tail: "true"
  name: getting-started
  namespace: default
spec:
  containers:
  - image: gcr.io/k8s-skaffold/skaffold-example:v0.37.0-297-g28e6a784f@sha256:ae2cf00b749df139b100fa5b671ec636ec75fa26950644ac9c7a6e077a8a0414
    name: getting-started
```

```
➜  skaffold run --render-only
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:v0.37.0-297-g28e6a784f
Tags generated in 32.207808ms
Checking cache...
 - gcr.io/k8s-skaffold/skaffold-example: Found
Cache check complete in 616.502154ms
Tags used in deployment:
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:v0.37.0-297-g28e6a784f@sha256:ae2cf00b749df139b100fa5b671ec636ec75fa26950644ac9c7a6e077a8a0414
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v0.37.0-297-g28e6a784f
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kubectl
    skaffold.dev/docker-api-version: "1.39"
    skaffold.dev/run-id: 48cd0950-bcce-4bc4-8e84-213a34d75a69
    skaffold.dev/tag-policy: git-commit
    skaffold.dev/tail: "true"
  name: getting-started
  namespace: default
spec:
  containers:
  - image: gcr.io/k8s-skaffold/skaffold-example:v0.37.0-297-g28e6a784f@sha256:ae2cf00b749df139b100fa5b671ec636ec75fa26950644ac9c7a6e077a8a0414
    name: getting-started
```

Fixes #1187 
Ref #1937

### CODE REVIEW

**Comment by tejal29** [comment]
Initial thoughts, from description.
I am not sure if we want to support `--render-only` in `dev` or `run` mode. 
Especially, if skaffold does not  `deploy` the app in `--render-only` mode, users can't really iterate over and develop.
Also, last i looked, i think we do display the rendered k8 manifests in debug mode.
Maybe we could switch to display rendered manifest  via `Render` method in debug mode.

**Comment by nkubala** [comment]
> I am not sure if we want to support --render-only in dev or run mode.
Especially, if skaffold does not deploy the app in --render-only mode, users can't really iterate over and develop.

Fair point about not doing the deployment (since I suppose users couldn't validate), but I think it's pretty clear what skaffold is doing when this flag is provided so users should probably know that their apps haven't been deployed and therefore verified. Maybe they want to intercept the k8s manifests and do some other transformations or something before deploying, this is just another route for them to retrieve the manifests rather than directly running `skaffold render`. WDYT?


> Also, last i looked, i think we do display the rendered k8 manifests in debug mode.
Maybe we could switch to display rendered manifest via Render method in debug mode.

Are you saying remove the functionality of rendering the manifests while in debug mode by default? Not sure I know what you mean by "render method in debug mode", `debug` is a totally separate command. I think we probably don't want to change the way debug works right now, I'll double check and make sure the rendered manifests are the same though.

**Comment by tejal29** [comment]
> > Also, last i looked, i think we do display the rendered k8 manifests in debug mode.
> > Maybe we could switch to display rendered manifest via Render method in debug mode.
> 
> Are you saying remove the functionality of rendering the manifests while in debug mode by default? Not sure I know what you mean by "render method in debug mode", `debug` is a totally separate command. I think we probably don't want to change the way debug works right now, I'll double check and make sure the rendered manifests are the same though.

Wrong terminology. I meant we displayed rendered k8 manifests with `-v=debug` debug logging mode. https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl.go#L103

**Comment by tejal29** [comment]
Re: 
> > I am not sure if we want to support --render-only in dev or run mode.
> > Especially, if skaffold does not deploy the app in --render-only mode, users can't really iterate over and develop.
> 
> Fair point about not doing the deployment (since I suppose users couldn't validate), but I think it's pretty clear what skaffold is doing when this flag is provided so users should probably know that their apps haven't been deployed and therefore verified. Maybe they want to intercept the k8s manifests and do some other transformations or something before deploying, this is just another route for them to retrieve the manifests rather than directly running `skaffold render`. WDYT?

Since no one has brought up this use-case of being able to render manifests in dev mode, can we tackle that later?
Its pretty hard for me to see why one would need it. We can talk more about this in person. 

Also, how about landing this feature in small increments and only add one thing at a time. 
Having a `deploy --render-only` or `run --render-only` is something users want for sure.  Maybe in this PR we add that. 
And then build it up from there?

**Comment by nkubala** [comment]
> I meant we displayed rendered k8 manifests with -v=debug debug logging mode.

ah good point. I'm going to remove the logging of the raw manifests (which happens when we read them), but I'll leave some of the more nuanced logging (manifests with tagged images, manifests with labels, etc.). since this is at `debug` level I think it's fine to leave.

> Having a deploy --render-only or run --render-only is something users want for sure. Maybe in this PR we add that.

to me this is actually the secondary feature of this PR - the main addition is the `skaffold render` command, which is essentially equivalent to `skaffold run --render-only`. I decided to add the flag just to give users an option, the functionality is the same.

it feels strange to me to just remove support for the `--render-only` flag for `dev` only but leave it for `deploy` and `run`, just because we don't know if users "want it". i would rather either add it for all commands where it makes sense, or just not add it at all. what do you think?

**Comment by nkubala** [comment]
going to close this one in favor of a few smaller PRs for easier review :+1:

**Pull request closed without merging**
