### PR TITLE
kaniko: pin image version to v0.1.0

### LINKED ISSUE #591: Pin Kaniko Image tag
https://github.com/GoogleContainerTools/skaffold/blob/2fb273da349176ccae5dfe4476e06e8da75d3838/pkg/skaffold/constants/constants.go#L41

### PR DESCRIPTION
**Pull request by r2d4**
fixes #591

### CODE REVIEW

**Comment by r2d4** [comment]
I manually verified this works

**Comment by jonjohnsonjr** [comment]
Thoughts re: pinning to a digest instead of a tag?

**Comment by dlorenc** [comment]
It's effectively the same for kaniko. We have effectively immutable tags.

**Comment by r2d4** [comment]
Done :)

**Comment by r2d4** [comment]
Ah thats clearer. Didn't know about that syntax.

**Comment by r2d4** [comment]
Updated

**Pull request merged**
