### PR TITLE
Schemas should emit type=object for object

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes: #5421

**Description**
This PR causes the JSON schema generator to mark struct-types as `"type":"object"` in the resulting JSON scheme.  These `type` statements act as constraints.  Without this type, these definitions can be anything: objects, strings, numbers, null, etc.

### CODE REVIEW

**Comment by briandealwis** [comment]
Marking as do-not-merge as I'm trying to test the LSP to ensure it doesn't break anything.

**Comment by aaron-prindle** [comment]
Seems that schema tests will need to be modified as well from Travis:
```
=== Failed Tests ===
/hack/schemas/TestGenerators
--- FAIL: TestGenerators (0.04s)
/hack/schemas/TestGenerators/inline
    main_test.go:73: string differ (-got, +want):   (
          	"""
          	... // 51 identical lines
          	      ],
          	      "additionalProperties": false,
        - 	      "type": "object",
          	      "description": "for testing the schema generator.",
          	      "x-intellij-html-description": "for testing the schema generator."
          	... // 4 identical lines
          	"""
          )
```

Additionally is there any concern around modifying old versions of the schema vs schemas going forward?  I don't think many users would be using/relying on incorrect definitions of objects but wanted to state it explicitly here.

**Comment by aaron-prindle** [comment]
Is there any concern around modifying old versions of the schema vs schemas going forward?  I don't think many users would be using/relying on incorrect definitions of objects but wanted to state it explicitly here.

**Comment by briandealwis** [comment]
I updated the schema files and rebuilt the LSP and it seems happy.

I don't think we need to be concerned about updating the past schemas: adding this field just constrains what could be used. The worst case is that invalid files will now be flagged as invalid where as they may have appeared to be valid previously. Skaffold would still have failed to load them.

**Review by aaron-prindle — APPROVED** [review]
LGTM

**Pull request merged**
