### PR TITLE
Add an mtime file watcher.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
This can help us work around the issues caused by inotify-style watchers.

**Comment by dlorenc** [comment]
TODO:

- [ ] Figure out the best way to configure which watcher to use
- [ ] Tests
- [ ] benchmarking

**Comment by dgageot** [comment]
@dlorenc @r2d4 I think we could get rid of the inotify watcher altogether because it won't go any further. Changing the list of dependencies based on file changes with inotify is too tricky

**Comment by dlorenc** [comment]
> @dlorenc @r2d4 I think we could get rid of the inotify watcher altogether because it won't go any further. Changing the list of dependencies based on file changes with inotify is too tricky

SGTM, how about an environment variable to switch between the two for now in-case there is a large perf hit for some workloads? We can switch the default to mtime in this PR but leave inotify until we stop hearing complaints about mtime.

**Comment by dlorenc** [comment]
An env var would be easier than a flag because we can remove it without breaking people that pass it on the cmd line.

**Comment by dlorenc** [comment]
Dropping the WIP, this should be ready for a look.

I prioritized ease-of-removal of fsnotify rather than doing a full refactor.

**Comment by dlorenc** [comment]
These tests are passing for me but failing in travis, i'll keep debugging:

```shell
--- PASS: TestWatch (5.03s)
    --- PASS: TestWatch/watch_unknown_file_mtime (0.00s)
    --- PASS: TestWatch/write_files_mtime (2.01s)
    --- PASS: TestWatch/ignore_file_mtime (2.00s)
    --- PASS: TestWatch/watch_unknown_file_fsnotify (0.00s)
    --- PASS: TestWatch/write_files_fsnotify (0.51s)
    --- PASS: TestWatch/ignore_file_fsnotify (0.51s)
```

**Comment by dlorenc** [comment]
Tests passing now.

**Comment by r2d4** [comment]
I think we should do some testing with minikube/d4d to make sure this works well. We still have the clock skew issues in minikube.

**Comment by dlorenc** [comment]
> I think we should do some testing with minikube/d4d to make sure this works well. We still have the clock skew issues in minikube.

The skew isn't important, we take an initial snapshot then just check to see if the values have changed at all from that.

What exactly do you mean by testing in d4d? Watch happens on the local machine, not in the build step itself.

**Comment by dlorenc** [comment]
@dgageot anything blocking this?

**Comment by dgageot** [comment]
Absolutely not! Let me merge it
LGTM

**Pull request merged**
