### PR TITLE
chore: updating google api and opentelemetry version

### PR DESCRIPTION
**Pull request by bskaplan**
**Description**

Update the Google Cloud API Client and OpenTelemetry to the latest versions.

**User facing changes (remove if N/A)**

The latest Cloud Run features will now be supported, notably built-in support for mounting gcsfuse and NFS volumes. See https://cloud.google.com/run/docs/configuring/services/cloud-storage-volume-mounts#yaml and https://cloud.google.com/run/docs/configuring/services/nfs-volume-mounts#yaml for example YAMLs.

### CODE REVIEW

**Review by ericzzzzzzz — APPROVED** [review]

**Comment by idsulik** [comment]
@bskaplan hi! why you added `fs/assets/credits_generated/github.com/hashicorp/hcl/go.mod`? Any go command changes this file now according to this https://github.com/golang/go/issues/34842.   
image

**Comment by bskaplan** [comment]
I didn't have any particular reason. I was updating the dependent modules, I guess that file got picked up when I updated them and I was mostly focused on making sure everything still worked with the updates. If that file isn't necessary, you can send another PR deleting it.

**Comment by idsulik** [comment]
@bskaplan have you deleted the line by yourself? because golang adds this line by itself whenever you use any go command.  
@ericzzzzzzz , what do you think about this https://github.com/GoogleContainerTools/skaffold/pull/9352#issuecomment-2053899682 ? should we delete the go.mod file or should we specify go version there?

**Comment by ericzzzzzzz** [comment]
Hi @idsulik, I think we may have to keep this file.  The file was auto-generated by `go-license`,  `go-license` is supposed to  just extract LICENSES from dependencies of skaffold without other files, but somehow it also includes this file.  We have license check in our ci which also compares the output from `go-license` run on our ci and the `generated_credits` folder from pr branch,  if there is discrepancy, ci will fail. Although it's a little annoying, it doesn't affect skaffold functionalities.

**Comment by idsulik** [comment]
@ericzzzzzzz Thank you for the details, added the go version here https://github.com/GoogleContainerTools/skaffold/pull/9390/files#diff-8939f41b03be02a3877b5d557f6b6adb21c33906b5c3093f6e7f626ed9f07044R3 , otherwise go cli updates it automatically and you see changed file, so you have to manually exclude it from commit

**Pull request merged**
