### PR TITLE
Go Modules

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by nkubala** [comment]
just tested the release build locally and it works for me, so looks like setting `GOMODULE11=on` in the makefile was enough to solve the xgo issue. @dgageot what more do you think needs to be done here?

**Comment by dgageot** [comment]
@nkubala I think we're good. I was wondering if we should vendor dependencies or re-download them on each build. I think vendoring is faster. Let me remove the `[WIP]` prefix!

**Comment by nkubala** [comment]
I'm not 100% sure but I think if we're keeping the vendored deps then we want to pass `-mod=vendor` to `go build`? otherwise won't it fetch the deps from `go.mod` and use those to build instead?

**Comment by dgageot** [comment]
@nkubala TIL. It's fixed now

**Comment by nkubala** [comment]
cool. and because of this we don't need to worry about downloading from a proxy right?

**Comment by dgageot** [comment]
Yes

Le lun. 29 juil. 2019 à 21:50, Nick Kubala <notifications@github.com> a
écrit :

**Comment by nkubala** [comment]
```
0.09s$ go build -mod=vendor -o out/skaffold.exe cmd/skaffold/skaffold.go
The command "go build -mod=vendor -o out/skaffold.exe cmd/skaffold/skaffold.go" exited with 1.

390.10s$ go test -short -timeout 60s ./...
build flag -mod=vendor only valid when using modules
```
not sure why this is happening, or why it only happened with the windows build...

**Pull request merged**
