### PR TITLE
Fix dockerfilePath in annotated-skaffold.yaml

### PR DESCRIPTION
**Pull request by oradwell**
`annotated-skaffold.yaml` seems to be out of date. Issue #387 seems to be created because of it.

It took me a while to figure it out too since there isn't any other documentation around the `dockerfilePath` configuration.

### CODE REVIEW

**Comment by oradwell** [comment]
I've signed the agreement

**Comment by oradwell** [comment]
I signed it!

**Comment by r2d4** [comment]
@oradwell Do you mind double checking the CLA? The bot hasn't seemed to register it. You'll need to make sure the commit author is set to the email you signed the CLA with.

**Comment by oradwell** [comment]
@r2d4 CLA was fine. I've re-committed the change which triggered the CLA check. thanks!

**Pull request merged**
