### PR TITLE
Fix bug in sync

### LINKED ISSUE #1668: Skaffold v0.23.0 + Windows 10 regression: didn't sync any files
### Expected behavior

Sync files when it changes

### Actual behavior

Did not sync files. Always shows "didn't sync any files"

### Information

- Skaffold version: v0.23.0
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
Any yamls I tried
```

### Steps to reproduce the behavior

1. Update to v0.23.0 from v0.22.0
2. Sync stops working

### PR DESCRIPTION
**Pull request by priyawadhwa**
This PR fixes a bug in sync, in which desinations for synced files were
being calculated incorrectly. For the hot-reload example, app.py was
being synced to /src/app.py instead of /app.py, so it appeared as if
sync wasn't actually working.

To fix this issue, I fixed a bug in the intersect function to make sure
destination calculation follows the Docker COPY command rules.

For example, we had a unit test as follows:

```
syncMap: **/**/*.js": "."
file: dir1/dir2/node.js
dst: /dir1/dir2/node.js
```
I _think_ the destination should actually be `/node.js` based on Docker COPY
command rules.

should fix #1668

### CODE REVIEW

**Comment by dgageot** [comment]
There seems to be an issue with `name.ParseReference(target, name.WeakValidation)`. It fails to parse `gcr.io/k8s-skaffold/test-file-sync:67738fe@sha256:13e30612be9aa5dae72fb06619ff0dabf80ca600e8f949da683abe73d2f0113b` even if it's a correct image reference.

cc @jonjohnsonjr

**Comment by priyawadhwa** [comment]
@dgageot  @balopat  I just pushed a workaround to remove the tag and use just the digest for getting the workingDir from the image until go-containerregistry can parse both.

**Comment by nkubala** [comment]
@priyawadhwa I think that's fine, can you check out the failing test in Kokoro though? doesn't look like a flake

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/issues/351

I kind of have a philosophical disagreement with that format of reference. I think it's misleading.

I'm happy to take a PR to fix it, I just don't have time to figure out the regex voodoo myself.

**Pull request merged**
