### PR TITLE
Add skeleton for jib integration

### PR DESCRIPTION
**Pull request by loosebazooka**
Mostly following the style of the bazel builder

- Not sure yet where to drop tests for Jib for (since there is no bazel equivalent):
  - runner.go
  - local.go
  - config.go

### CODE REVIEW

**Comment by dgageot** [comment]
So far, so good :-)

**Comment by loosebazooka** [comment]
So a couple of dev options?
1. Merge into a feature branch: jib-skaffold
2. Keep building like this with "unimplimented errors" until ready to go?

Any preference?

**Comment by dgageot** [comment]
I like option 2!

**Comment by loosebazooka** [comment]
@r2d4 @dgageot can you create a feature branch in this repo for us? `jib-skaffold`

**Comment by balopat** [comment]
added the feature branch and changed the PR to point to it. I really hope we don't have to keep the feature branch around long and that keeping in sync with master is going to be too painful :)

**Comment by balopat** [comment]
added PR for checking "in-syncness" of the feature branch: https://github.com/GoogleContainerTools/skaffold/pull/1063

**Pull request merged**
