### PR TITLE
Print Custom Builder command

### LINKED ISSUE #4340: Custom builder command-line is not shown
### Expected behavior

`skaffold xxx -v debug` usually shows the executed commands.

### Actual behavior

```console
$ skaffold build -v trace
[...]
Found [minikube] context, using local docker daemon.
Building [skaffold-custom-jib]...
DEBU[0000] Executing template &{envTemplate 0xc00012e100 0xc0007ffa00  } with environment map[BINPATH:/Users/bdealwis/bin BLOCKSIZE:1024 EDITOR:vi GIT_EDITOR:vim HOME:/Users/bdealwis LANG:en_CA.UTF-8 LESS:Remq LOGNAME:bdealwis PATH:/Users/bdealwis/bin/Darwin:/Users/bdealwis/bin:/Users/bdealwis/installs/bin:/Users/bdealwis/go/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin PWD:/Users/bdealwis/Projects/Skaffold/master/examples/jib SHELL:/bin/zsh SHLVL:1 USER:bdealwis VISUAL:vi] 
TRAC[0000] latest skaffold version: v1.11.0             
INFO[0000] update check failed: get latest and current Skaffold version: parsing current semver, skipping update check: parsing semver: Version string empty 
DEBU[0000] could not parse data                         
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.skaffold:hello-spring-boot >-------------------
```

I guess I can look at the `skaffold.yaml` and figure it out, but it would be useful to see the actual command-line.

### Information

- Skaffold version: head
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-custom-jib
    custom:
      buildCommand: ./mvnw package $(if [ $PUSH_IMAGE = true ]; then echo jib:build; else echo jib:dockerBuild; fi) -Djib.to.image=$IMAGE
      dependencies:
        paths:
        - src/**

```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #4340

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by briandealwis** [comment]
This wasn't merged

**Comment by tejal29** [comment]
> This wasn't merged

oops. not sure why i closed this.

**Comment by tejal29** [comment]
close, re-open to re-trigger tests.

**Comment by dgageot** [comment]
Don't know what's going on with travis. reopening a new PR

**Pull request closed without merging**
