### PR TITLE
chore(example): Add example to use Skaffold with Gitlab DevOps helm chart

### PR DESCRIPTION
**Pull request by vymarkov**
Add example to use Skaffold with [Gitlab DevOps helm chart](https://gitlab.com/gitlab-org/charts/auto-deploy-app)

**Description**

This is the example of usage Gitlab's DevOps chart and skaffold (docker registry secrets are out of scope of this PR)

It was tested by using **helm v2** and **helm v3**, **skaffold v1.8.0**.

### CODE REVIEW

**Comment by vymarkov** [comment]
@googlebot I signed it!

**Comment by vymarkov** [comment]
@googlebot I signed it!

**Comment by vymarkov** [comment]
@googlebot I signed it!

**Comment by gsquared94** [comment]
@vymarkov are you still working on this; do you need any help here?

**Comment by vymarkov** [comment]
> @vymarkov are you still working on this; do you need any help here?

thank you for attention :) working on the related MR on the GitLab repo, unfortunately, MR still in the code review stage

**Comment by nkubala** [comment]
@vymarkov would you mind linking the related PR on the Gitlab repo so we can track? this PR is getting a bit stale so any updates would be great.

**Comment by tejal29** [comment]
@vymarkov the following check is failing. 
```
RUN hack/check-samples.sh
Every code sample that is in ./examples should also be in ./integration/examples
The following are in examples but not in integration/examples:
gitlab-auto-devops-helm
FAILED hack/check-samples.sh
```
Can you please instead move this to `intergration/examples` directory. 
On next skaffold release, this will  be copied to `example` directory.

**Comment by nkubala** [comment]
@vymarkov any news here? I'd love to get this PR merged. let us know if there's anything we can do to help!

**Comment by nkubala** [comment]
hey @vymarkov, really sorry this one never got pushed through. i'm going to close it for now because it's gotta stale, and i'm not sure we can take this over ourselves.

however, i opened https://github.com/GoogleContainerTools/skaffold/issues/5031 to track adding a community maintained examples space so we don't block others on contributing things like this. there's real value in sharing real world skaffold setups with the community, and i don't want to discourage others from doing the same in the future.

sorry again for not pushing this one through, but thank you for inspiring us to make our community support better, even if we can't do anything about it immediately 🙏

**Pull request closed without merging**
