### PR TITLE
some fixes on documents

### PR DESCRIPTION
**Pull request by ssbostan**
for updating documents as well

### CODE REVIEW

**Comment by ssbostan** [comment]
@googlebot I signed it!

**Comment by MarlonGamez** [comment]
hey @ssbostan, thanks for these doc fixes! We're having some CI issues right now, but once we resolve them I think we can approve and merge this :)

**Comment by ssbostan** [comment]
Hey there @MarlonGamez, your welcome, i read all of documents and will be fix another issues too.

**Review by briandealwis — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
