### PR TITLE
Add Cloud Shell for simpler Quickstart

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes: #4813 

**Description**

Adds an <kbd>Open in Cloud Shell</kbd> option to the Skaffold Quickstart.  Required a minor reorganization to the page to flow better (IMHO).

### CODE REVIEW

**Comment by briandealwis** [comment]
I want to see if there's some better language for non-GCP customers to tell them how to create an account to use the Cloud Shell option.

**Comment by MarlonGamez** [comment]
> I want to see if there's some better language for non-GCP customers to tell them how to create an account to use the Cloud Shell option.

What kind of information do you think we should give to the user about this? Does the user have to do any setup on their account besides creating a google account?

**Comment by briandealwis** [comment]
PTAL @MarlonGamez — added a note that it requires a Google Account and links to the signup page.

**Review by MarlonGamez — APPROVED** [review]
Looks good!

**Pull request merged**
