### PR TITLE
support helm version 3 (and version 2)

### PR DESCRIPTION
**Pull request by ktarplee**
Addresses #2142

### CODE REVIEW

**Comment by ktarplee** [comment]
This is my first golang PR so any feedback on best practices would be appreciated.

**Comment by tejal29** [comment]
Thanks @ktarplee. You picked a issue which the team has plans to work on
/cc @nkubala. Last i know, we discussed creating a new Deployer Kind `Helm3` use `helm template` && `kubectl install <generated templates>`

I will let @nkubala lead the rest of the discussion.

**Comment by ktarplee** [comment]
@googlebot I signed it!

**Comment by tejal29** [comment]
As per the discussion, we are going to create a new `Helm3` Deployer. Can you create a new object which implements the `deploy.Deployer` interface ? Closing this PR.

**Comment by igoooor** [comment]
@tejal29 any idea when this will be available as helm 3 has now been released?

**Comment by tstromberg** [comment]
@ktarplee - thank you for this PR. Your work, and the community encouragement, gave us the confidence to execute on helm3 when we finally had the cycles to execute on it. What ended up getting merged is almost exactly the set of behaviors you proposed in this PR: though with some extra wiggle room to handle future cases like helm 3.1 introducing new flags as well.

I extend my sincere apology to you and the community that helm 3 support took so long to get merged.

We simply overestimated and misunderstood the amount of work it would take to get helm3 support in correctly. I believe we did you & the community a disservice by pushing back on this PR  without enough transparency and information to encourage a dissenting voice. I've discussed this with the other helm developers, and hope we will get this right in the future. We can do better.

Thank you for getting the helm 3 ball rolling. It couldn't have landed without you.

**Comment by ktarplee** [comment]
Thanks everyone for working on getting this support added to skaffold.  Well done!

**Pull request closed without merging**
