### PR TITLE
Use Maven wrapper for Jib example easier start.

### PR DESCRIPTION
**Pull request by ivanporty**
When working on coming IntelliJ IDE plugin demos, running Jib example is not as easy as it could be with a added Maven wrapper. Maven is required in `PATH` for example to work, but it may not be used at all (i.e. developer uses Gradle instead) or not used in CLI (internal IDE support for Maven). Maven wrapper will download and provide Maven automatically and Jib knows how to pick it up.

Also, this PR exposes container port for port forwarding in the container section, without it `skaffold` does not port-forward 8080 automatically.

### CODE REVIEW

**Comment by ivanporty** [comment]
Sure, good idea, I'll bump up the version.

**Comment by dgageot** [comment]
@ivanporty this is awesome. One issue, you have to also fix the same sample under `integration/examples`. I know this is painful...

**Comment by ivanporty** [comment]
Ah, good to know, let me make the changes there as well.

**Comment by ivanporty** [comment]
@dgageot the integration example is updated as well, let me know if something else is missing, thanks!

**Pull request merged**
