### PR TITLE
Basic support for using kubectl and helm together

### PR DESCRIPTION
**Pull request by ajbouh**
This is the minimal change needed to do deploys with both kubectl and helm.

If only one configuration is present, it falls back to existing logic. If both configurations are present, a new deployer is returned that runs both helm and kubectl in sequence.

It is naive in a number of ways:
- It does not determine which artifacts are used by which deployer, so a change in any artifact redeploys both kubectl and helm
- A failure in one deployer means it does not attempt to deploy the other
- No test coverage

Addresses https://github.com/GoogleContainerTools/skaffold/issues/528

### CODE REVIEW

**Comment by dlorenc** [comment]
@ajbouh Would you be able to sign the CLA?

**Comment by ajbouh** [comment]
Done

**Comment by dgageot** [comment]
@ajbouh Can you please rebase your code? Thanks a lot!

**Comment by dlorenc** [comment]
@ajbouh can you check that you signed the CLA with the right email address? The bot is still saying it's not signed.

**Comment by ajbouh** [comment]
Hmm, I have multiple email addresses in GitHub, but only signed with the
address that's referenced by the commit. Do you think that could be the
issue?

**Comment by dgageot** [comment]
@ajbouh yes, that can be the issue. Can you also rebase your code, please? Thanks!

**Comment by balopat** [comment]
@ajbouh ping, do you still have issues with the CLA/rebasing?

**Comment by ajbouh** [comment]
@balopat rebased. Also, looks like the cla bot doesn't recheck until you repush

**Pull request merged**
