### PR TITLE
Update and clean dependencies up

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by briandealwis** [comment]
I notice the bazel team document the commands they used when doing chores like this as it makes it clear if something out of the ordinary was required.

**Comment by dgageot** [comment]
@briandealwis The list of commands I have to run to make such update is embarrassing. It's basically me running "go get X" for each of our direct dependencies, but not for any of the k8s dependencies because we don't want the latest but also not `golang.org/x/sys` because it's buggy on windows. And after each go get, I run `go mod tidy`, `go mod vendor` and `make quicktest` to make sure I don't break things. Did I say I hate Go modules?

**Comment by dgageot** [comment]
The linter is failing because it's short on memory...

**Comment by nkubala** [comment]
I hate how painful this is. it would be really nice to have a `.modignore` file or something to ignore specific dependencies when running `go mod update`. I don't really know any real solution to this though...

**Comment by nkubala** [comment]
@dgageot it looks like the linter is actual failing, can you check the error

**Pull request merged**
