### PR TITLE
unhide status check and on by default. 

### LINKED ISSUE #3638: Unmark `--status-check` flag as hidden
Related to #3621 
One ask/improvement from skaffold survey was to wait for deployments to stabilize.

### PR DESCRIPTION
**Pull request by tejal29**
Relates to #3621 
Fixes #3638 
Should merge after #3658 , #3687

**User Facing Changes**

1. Add flag `--status-check` which waits for deployments to stabilize before next stage in `skaffold pipeline`
2. This flag's default value is `true`.  `skaffold dev`, `skaffold debug` and `skaffold dev` will now wait for deployments to stabilize. 

**Release Notes:**
```
Add flag `--status-check` which waits for deployments to stabilize before next stage in skaffold pipeline. (Default true). Disable using `--status-check=false`

```

### CODE REVIEW

**Comment by tejal29** [comment]
@balopat i cherry-picked a #3658  on this branch. Can you verify now?

Thanks in advance!
Tejal

**Comment by nkubala** [comment]
i'm good with this, but i'm not really sure about the default deadline - 10 minutes seems like a really long time. was there a specific reason for choosing 10? otherwise i'd say bump it down to something like 2 or even 1 minute as a default, if users want it longer they can specify.

**Comment by tejal29** [comment]
> i'm good with this, but i'm not really sure about the default deadline - 10 minutes seems like a really long time. was there a specific reason for choosing 10? otherwise i'd say bump it down to something like 2 or even 1 minute as a default, if users want it longer they can specify.

10 mins is the default [`progressDeadlineSeconds`](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds) for deployments when not set in the spec. 
We don't want to override that hence it is set to 10 minutes.

**Comment by tejal29** [comment]
> I agree that 10m wait time is a no-go **to be the default**.
> I just ran into this - when there is an error, we provide no help - just say that "deployments didn't stabilize", hang there for 10 minutes and then fail the dev loop :(
> 
> ```
> Waiting for deployments to stabilize
>  - default:deployment/avatar-generator Waiting for deployment spec update to be observed...
>  - default:deployment/avatar-generator Waiting for deployment "avatar-generator" rollout to finish: 0 out of 1 new replicas have been updated...
>  - default:deployment/avatar-generator Waiting for deployment "avatar-generator" rollout to finish: 0 of 1 updated replicas are available...
>  - default:deployment/avatar-generator failed. Error: received Ctrl-C or deployments could not stabilize within 10m0s: kubectl rollout status command interrupted.
> Cleaning up...
>  - deployment.apps "avatar-generator" deleted
>  - service "avatar-generator" deleted
> FATA[0606] exiting dev mode because first deploy failed: 1/1 deployment(s) failed 
>  dev2  ~/c/python-django-guestbook-1   *+…                                                                                                                                         11.8m 
> ```

Sounds good. See #3687

**Comment by tejal29** [comment]
@balopat Please take another look. #3687 now reduces the default to 2 mins  if
- no `skaffold.Deploy.statusCheckDeadlineSeconds` is defined
- none of the `deployments.Spec.ProgressDeadlineSeconds` is present.

**Pull request merged**
