### PR TITLE
README.md should point to annotated-skaffold.yaml

### PR DESCRIPTION
**Pull request by bryanlarsen**
annotated-skaffold.yaml appears to be the closest thing to detailed documentation this project has, so it'd be nice to point to it from the README.

### CODE REVIEW

**Comment by bryanlarsen** [comment]
@googlebot I signed it!

**Comment by dgageot** [comment]
@bryanlarsen Are you sure your signed the CLA with the email that is attached to your GitHub account?

**Comment by bryanlarsen** [comment]
My github account has three emails attached, the CLA was signed with the one marked "primary" and "visible".

**Comment by bryanlarsen** [comment]
My github account has three emails attached, the CLA was signed with the one marked "primary" and "visible".   Of course, this PR is trivial: you're welcome to view it as a documentation request rather than a PR if the CLA stuff doesn't get sorted out.

**Pull request merged**
