### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by joebowbeer**
**Description**
Do not specify the exact number of skaffold stages. The currently specified number does not agree with the diagram or subsequent table, and is likely to change.

I know. Nobody expects the Spanish Inquisition.

Amongst our stages are ...

### CODE REVIEW

**Comment by briandealwis** [comment]
Ha!  Thanks for noticing.  Definitely needs @nkubala's input because I'm not sure if we're counting the blue squares or all squares.

**Comment by joebowbeer** [comment]
@briandealwis there is also the table of **Skaffold Pipeline stages** at the bottom of the page, which has nine rows, but maybe Init shouldn't be counted.

**Comment by nkubala** [comment]
@joebowbeer lol nice catch :) to be honest our diagrams are getting stale and might need to be updated in the future. I wonder if we should just say `multi-stage workflow` so we don't have to keep updating that string?

**Comment by nkubala** [comment]
also worth mentioning that as a team we collectively agree our docs need lots of love - this is yet another item to add to the list of things to address

**Comment by joebowbeer** [comment]
@nkubala I applied your multi-stage suggestion.

**Review by gsquared94 — APPROVED** [review]

**Pull request merged**
