### PR TITLE
Support configuring default namespace for kubectl/kustomize deployers

### PR DESCRIPTION
**Pull request by AndiDog**
Fixes: #3172 
**Related**: n/a
**Merge before/after**: n/a

**Description**

Support configuring default namespace for kubectl/kustomize deployers. The Helm deployer luckily already had this (release namespace). In addition, all three deployers now allow templating for those fields, which makes sense e.g. for per-user environments with a namespace of `dev-{{.USER}}`.

With this change, users don't explicitly have to specify `-n targetnamespace` all the time, and instead declaratively configure – maybe even per profile – which namespace the application should be deployed to. Command line argument / environment variable still take precedence, as expected in most Unix-like tools.

### CODE REVIEW

**Comment by gsquared94** [comment]
unfortunately the script to generate new config is currently broken. Once that gets fixed and applied you should be able rebase to fix the tests. We'll just have to wait until then, sorry.

**Comment by gsquared94** [comment]
A new config version was created. Can you try to rebase on master.

**Comment by MarlonGamez** [comment]
Hi @AndiDog , it looks like this hasn't been touched for a bit, so I think this PR will need to be rebased. If you fix the conflicts and @ me, I'll try to review this asap

**Comment by AndiDog** [comment]
@MarlonGamez Rebased, and tests + new feature are working for me locally. Didn't run integration tests, so let's see what CI says.

**Comment by MarlonGamez** [comment]
Hey again, we actually released v2beta7 last week, so I think you'll have to rebase again make the changes to v2beta8. Really sorry that this is turning out to be such a hassle :(

**Comment by AndiDog** [comment]
@MarlonGamez Rebased again and recreated the JSON file. Hope it's building now.

**Review by MarlonGamez — APPROVED** [review]
Just did a final review to double check everything, and it looks good to me :) thanks again for being patient with the rebases and what not

**Pull request merged**
