### PR TITLE
Build skaffold-builder image from a pre-pushed base

### PR DESCRIPTION
**Pull request by dgageot**
This should be a fixed version of #3433. The images produces on Cloud Build should now contain the skaffold binary. See #3622. @balopat @tejal29 could you take a look and check that I didn't break thing again !? 

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by tejal29** [comment]
Thanks @dgageot for a quick turnaround!

**Comment by tejal29** [comment]
Manual testing logs
1. Ran the following command to test `deploy/cloudbuild.yaml`
```
 gcloud builds submit --config deploy/cloudbuild.yaml --substitutions=_RELEASE_BUCKET=tejal-test,COMMIT_SHA=$(git rev-parse HEAD) --project tejal-test
```
I am seeing the following error
```
Step #0: Removing intermediate container cdee9ff8c1dd
Step #0:  ---> 86a595459f7b
Step #0: Step 7/7 : RUN skaffold credits -d /THIRD_PARTY_NOTICES
Step #0:  ---> Running in 5ecd0a89a301
Step #0: 2020/02/03 18:30:39 Successfully exported third party notices to /THIRD_PARTY_NOTICES
Step #0: Removing intermediate container 5ecd0a89a301
Step #0:  ---> 2e34bd5332fd
Step #0: Successfully built 2e34bd5332fd
Step #0: Successfully tagged gcr.io/tejal-test/skaffold-builder:latest
Finished Step #0
Starting Step #1
Step #1: Already have image: gcr.io/tejal-test/skaffold-builder:latest
Step #1: hack/generate-statik.sh
Step #1: Collecting licenses
Step #1: Error: cannot register licenses from archive: open /usr/local/google/home/tejaldesai/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory
Step #1: Usage:
Step #1:   licenses save <package> [flags]
Step #1: 
Step #1: Flags:
Step #1:       --force              Delete the destination directory if it already exists.
Step #1:   -h, --help               help for save
Step #1:       --save_path string   Directory into which files should be saved that are required by license terms
Step #1: 
Step #1: Global Flags:
Step #1:       --alsologtostderr                  log to standard error as well as files
Step #1:       --confidence_threshold float       Minimum confidence required in order to positively identify a license. (default 0.9)
Step #1:       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
Step #1:       --log_dir string                   If non-empty, write log files in this directory
Step #1:       --logtostderr                      log to standard error instead of files
Step #1:       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
Step #1:   -v, --v Level                          log level for V logs
Step #1:       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
Step #1: 
Step #1: F0203 18:30:41.148749      32 main.go:43] cannot register licenses from archive: open /usr/local/google/home/tejaldesai/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory
Step #1: Makefile:246: recipe for target 'generate-statik' failed
Step #1: make: *** [generate-statik] Error 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/tejal-test/skaffold-builder:latest" failed: exit status 2
-----------------------------------------------------------------------------------------
```
I checkout your branch
```
tejaldesai@@skaffold (master)hub pr checkout 3631
tejaldesai@@skaffold (restore-skaffold-builder)$ git status
On branch restore-skaffold-builder
nothing to commit, working tree clean
tejaldesai@@skaffold (restore-skaffold-builder)$ 
```

Full build logs internal only https://paste.googleplex.com/5596099265953792

**Comment by dgageot** [comment]
My bad, I'll fix that tomorrow

**Comment by dgageot** [comment]
@tejal29 I can't reproduce your issue. It works fine for me.

**Comment by dgageot** [comment]
Don't know what's going on on Kokoro. Docker doesn't respond

**Comment by tejal29** [comment]
> Don't know what's going on on Kokoro. Docker doesn't respond

kaniko bad release. fixed it!

**Comment by tejal29** [comment]
from the build logs, looks like it looking for licenses in my local dir. Does that show up in your logs?
```
Step #1: Error: cannot register licenses from archive: open 

/usr/local/google/home/tejaldesai/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-
20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory
```

**Comment by dgageot** [comment]
@tejal29 I don't understand how it uses your login on Cloud Build...

**Comment by tejal29** [comment]
@dgageot i found out the issue. i had `skaffold-credits` and other files in my workdir which had references to files in my workspace. 
I cleaned it up and restarted the build. 
```
tejaldesai@@skaffold (restore-skaffold-builder)$ git clean -fdx
Removing .idea/
Removing bin/
Removing cmd/skaffold/app/cmd/statik/statik.go
Removing hack/bin/
Removing out/
Removing pkg/cad/
Removing pkg/skaffold/initializer/testdata/init/allcli/skaffold.yaml.out
Removing pkg/skaffold/initializer/testdata/init/hello/skaffold.yaml.out
Removing pkg/skaffold/initializer/testdata/init/ignore-tags/skaffold.yaml.out
Removing pkg/skaffold/initializer/testdata/init/microservices/skaffold.yaml.out
Removing skaffold-credits
tejaldesai@@skaffold (restore-skaffold-builder)$ 
```

**Comment by tejal29** [comment]
I verified this PR
```
git clean -fdx && gcloud builds submit --config deploy/cloudbuild.yaml --substitutions=_RELEASE_BUCKET=tejal-test,COMMIT_SHA=$(git rev-parse HEAD) --project tejal-test
...
ebc9b7b067f39306ea7b750d6e2624d2406c44a6: digest: sha256:fe7d1af983689454aa74061ba017a44859e510887ca43cac5bf4d27e26a402ff size: 4964
DONE
```

```
tejaldesai@@skaffold (restore-skaffold-builder)$ docker run gcr.io/tejal-test/skaffold@sha256:fe7d1af983689454aa74061ba017a44859e510887ca43cac5bf4d27e26a402ff skaffold version
v1.3.1-1-gebc9b7b-dirty
```

**Pull request merged**
