### PR TITLE
feat: update to buildpacks/pack v0.23.0

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes: #6948

### CODE REVIEW

**Review by SSGoku369 — COMMENTED** [review]
ok

**Comment by SSGoku369** [comment]
ok

**Comment by briandealwis** [comment]
TIL: `ioutil.ReadFile(filepath.Clean(""))` produces a different error from `ioutil.ReadFile("")` https://go.dev/play/p/qTSZOT-4Vk9

**Comment by briandealwis** [comment]
I wish we had a `/rebase` action.

**Comment by MarlonGamez** [comment]
Looks like it's still pulling the `latest` tagged imaged from gcr, think we'll have to rebuild and push ourselves? I'm not sure if there is a job somewhere that rebuilds that image or if it has always been manually done

**Comment by briandealwis** [comment]
Our GCB job does [build the `build_deps` image](https://github.com/GoogleContainerTools/skaffold/blob/bfb56aa31749e9a7364e95cc330a580211eebe57/deploy/cloudbuild.yaml#L5-L14) but it [doesn't list it in the images to be pushed](https://github.com/GoogleContainerTools/skaffold/blob/bfb56aa31749e9a7364e95cc330a580211eebe57/deploy/cloudbuild.yaml#L45-L47).

**Comment by briandealwis** [comment]
Filed #7038 to cause the `build_deps` image to be updated.

**Review by MarlonGamez — APPROVED** [review]

**Pull request merged**
