### PR TITLE
Improve skaffold help output 

### PR DESCRIPTION
**Pull request by medyagh**
Matches `kubectl help` style,  categorizes `skaffold help` output to categorize under: 

- Pipeline building blocks for CI/CD
- Getting started with a new project
- Utilities

Closes this https://github.com/GoogleContainerTools/skaffold/issues/1580

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Just some docs errors!

```
--- FAIL: TestPrintMan (0.06s)
    man_test.go:52: You have skaffold command changes but haven't generated the CLI reference docs. Please run ./hack/generate-man.sh and commit the results!
```

**Comment by dgageot** [comment]
@medyagh there's a test (TestMainHelp) that verifies a few words in the `skaffold help` output.

**Comment by balopat** [comment]
hehe, we missed that (I was pairing on this with Medya)

**Comment by dgageot** [comment]
ping @medyagh do you need any help to fix this PR?

**Comment by medyagh** [comment]
sorry for the delay, I am on it now

**Pull request merged**
