### PR TITLE
chore: upgrade k3d to latest bugfix-version

### PR DESCRIPTION
**Pull request by erikgb**
**Description**

This PR upgrades k3d to the latest bugfix-version: https://github.com/rancher/k3d/releases/tag/v5.0.3, that includes a fix for https://github.com/rancher/k3d/issues/801. To work around this issue is not trivial, so I would suggest to merge this and perform a bugfix-release of the Skaffold image as soon as possible.

### CODE REVIEW

**Comment by briandealwis** [comment]
Thanks @erikgb — you also need to run `make build_deps` and commit the results.  Sorry, this isn't documented.

**Comment by briandealwis** [comment]
@googlebot I consent

**Review by briandealwis — APPROVED** [review]
@MarlonGamez can you give this a look?

**Comment by erikgb** [comment]
@googlebot I consent

**Review by MarlonGamez — APPROVED** [review]
LGTM ✅

**Pull request merged**
