### PR TITLE
Release name template

### PR DESCRIPTION
**Pull request by afrittoli**
Add the ability to express the release name as a template.
This is based on https://github.com/GoogleContainerTools/skaffold/pull/601

### CODE REVIEW

**Comment by afrittoli** [comment]
@dgageot The linter is failing on the boilerplate check because I'm trying to attribute copyright to my employer for the code I added. Is this against the CLA? See https://github.com/GoogleContainerTools/skaffold/issues/600

**Comment by afrittoli** [comment]
I checked the corporate CLA and it in facts it includes "Grant of Copyright License" in point (2) of https://cla.developers.google.com/about/google-corporate. I reverted the copyright statements to Google, and replaced a couple of spaces for a tab, and now the linter is happy.

**Comment by dgageot** [comment]
LGTM

**Comment by rahulwa** [comment]
Can I have some example containing how to use it?
I see that [api](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v1alpha2/config.go#L131) is still same.

**Comment by rahulwa** [comment]
Nevermind, got it. 
Something like 
```yaml
  helm:
    releases:
      - name: "{{.APP_NAME}}-{{.APP_ENV}}"
```

**Pull request merged**
