### PR TITLE
Add Go 1.11 to Travis build matrix

### PR DESCRIPTION
**Pull request by emirb**

### CODE REVIEW

**Comment by emirb** [comment]
@googlebot I signed it! :-)

**Comment by nkubala** [comment]
Looks like the version of `golangci-lint` we're using (1.9.2) is broken with Go 1.11. I opened a [PR](https://github.com/GoogleContainerTools/skaffold/pull/1131) to upgrade the version, once that goes in do a rebase and Travis should pass.

**Comment by nkubala** [comment]
sorry, the PR I opened last week didn't actually seem to fix it :( I got it to pass for 1.11 but not 1.10, and the version we're on passes for 1.10 but not 1.11....not sure what's going on there

**Comment by balopat** [comment]
@emirb can you please rebase to master? That will pick up @nkubala's change and fix the linter issues.

**Comment by balopat** [comment]
I fixed this in #1281. Thank you for raising the awareness for this. I am closing this PR now.

**Pull request closed without merging**
