### PR TITLE
fix make file discrepancy for build_deps #4080

### PR DESCRIPTION
**Pull request by knvs97**
Fixes: #4080 
**Description**

Refactor build-deps to build_deps in Makefile

### CODE REVIEW

**Comment by knvs97** [comment]
@googlebot I signed it!

**Comment by balopat** [comment]
Thank you for the PR @knvs97!

**Comment by knvs97** [comment]
> Thank you for the PR @knvs97!

Hoping to be of help in making [skaffold](https://github.com/GoogleContainerTools/skaffold) better and bug free in the days to come.

**Comment by knvs97** [comment]
> @knvs97 Could you also fix the comment in `deploy/skaffold/Dockerfile`?

Hi @dgageot, 
    Made the change in the comment as requested.

**Pull request merged**
