### PR TITLE
Update Jib versions to 3.1.1

### PR DESCRIPTION
**Pull request by chanseokoh**
3.1.0 had a regression, unfortunately. :cry: We released 3.1.1 today.

### CODE REVIEW

**Comment by aaron-prindle** [comment]
There might have to be some additional code changes w/ the skaffold+jib integration for this update.  From our Travis tests - :
```
Error: refix 'jib' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/runner/.m2/repository), google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/)] -> [Help 1]\n[ERROR] \n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\n[ERROR] \n[ERROR] For more information about the errors and possible solutions, please read the following articles:\n[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException\n"
```
https://github.com/GoogleContainerTools/skaffold/pull/6007/checks?check_run_id=2797524771

**Review by aaron-prindle — COMMENTED** [review]
There might have to be some additional code changes w/ the skaffold+jib integration for this update.  From our Travis tests:
```
Error: refix 'jib' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/runner/.m2/repository), google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/)] -> [Help 1]\n[ERROR] \n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\n[ERROR] \n[ERROR] For more information about the errors and possible solutions, please read the following articles:\n[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException\n"
```
https://github.com/GoogleContainerTools/skaffold/pull/6007/checks?check_run_id=2797524771

These can be ran locally w/ `make integration-tests` assuming a working kubernetes endpoint

**Comment by chanseokoh** [comment]
Looks like an issue in Maven Central. From `search.maven.org`, I can check 3.1.1 is seen available but sporadically. I think this is a transient error or it's just that we need to wait for a few more hours. In any case, I'm sure re-running the tests tomorrow will succeed.

**Comment by chanseokoh** [comment]
The error is gone, as expected. Just so you know, I noticed the error message is truncated in the front, which confused me at first.
```
Error: refix 'jib' in the current project and in the plugin groups ...
```
It should have been
```
Error: [ERROR] No plugin found for prefix 'jib' in the current project and in the plugin groups ...
```

**Review by aaron-prindle — APPROVED** [review]
Awesome!  LGTM

**Pull request merged**
