### PR TITLE
Fix Helm flags not working via skaffold #7047 (#1)

### PR DESCRIPTION
**Pull request by nayang7**
Fixes: #7047  
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**

Update document

skaffold execute helm upgrade with flags

flags:
          upgrade:
            - '--history-max 3'
a space in the flag leads to an error

no errors and all works as expected with '=' to replace a space here
flags:
          upgrade:
            - '--history-max=3'

**User facing changes (remove if N/A)**

**Follow-up Work (remove if N/A)**

### CODE REVIEW

**Comment by tejal29** [comment]
Thank you @nayang7 for your PR. Can you please 
1) move this change to integration/examples/ folder?
The examples get copied over from the above folder. 
2) Please sign the Google CLA

Thanks
Tejal

**Comment by tejal29** [comment]
@nayang7 let us know if you need any more pointers?

**Comment by brianwarner** [comment]
Hi @tejal29, I'm with the Fidelity Investments OSPO. We're in the process of getting approvals to sign the CLA. Once that's done, we'll get @nayang7 added so the CLA check can clear.

**Comment by tejal29** [comment]
Thank you @brianwarner . Looking forward to work with your team. 

Don't hesitate to reach to us if you need anything.

**Comment by tejal29** [comment]
@nayang7  Thank you for your contribution. Please sign the CLA so we can accept this contribution.

**Comment by brianwarner** [comment]
Hi @tejal29, we've gotten the approvals to create a Google Group, and will hopefully have signed the corporate CLA next week.

**Comment by nayang7** [comment]
Will close this one since it didn't follow branch merge standard.

The new PR
https://github.com/GoogleContainerTools/skaffold/pull/7842

**Comment by tejal29** [comment]
sounds good. Closing this PR

**Pull request closed without merging**
