### PR TITLE
Upgrade linter to 1.10.2

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by nkubala** [comment]
hmm, are the CI errors happening because you upgraded the linter? one of these looks like a compilation error:

```
WARN [runner/megacheck] Can't run megacheck because of compilation errors in packages
[github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2]:
vendor/golang.org/x/net/http2/go111.go:23: invalid operation: trace (variable of type *clientTrace) has
no field or method Got1xxResponse and 3 more errors:
```

**Comment by dgageot** [comment]
@nkubala I have no idea why this is failing on Travis

**Comment by r2d4** [comment]
You need `-D typecheck` on the run command.

The script only installs golangci, but doesn't verify its running the same version

**Comment by dgageot** [comment]
@r2d4 I'm not sure I understand what you're saying. Why should this check be disabled?

**Pull request closed without merging**
