### PR TITLE
feat: add kaniko.imagePullSecret config option for pulling kaniko images from private registry

### PR DESCRIPTION
**Pull request by dherges**
Fixes: #9170 
**Related**:  n/a
**Merge before/after**:  n/a

**Description**

add a new config option `kaniko.imagePullSecret`

Do you reach out if there is anything missing?

### CODE REVIEW

**Comment by ericzzzzzzz** [comment]
Hi @dherges Thank you for the contribution , could you please have a separate pr just for the config schema change ? Thanks

**Comment by dherges** [comment]
> Hi @dherges Thank you for the contribution , could you please have a separate pr just for the config schema change ? Thanks

Do you mean the hack/new-version.sh + the 2 lines added to config.go?

**Comment by ericzzzzzzz** [comment]
> > Hi @dherges Thank you for the contribution , could you please have a separate pr just for the config schema change ? Thanks
> 
> Do you mean the hack/new-version.sh + the 2 lines added to config.go?
 There are two commits in this pr, you should split this pr into two pr, one for new config schema generation, another for the business logic change.  Please follow the guide here , https://github.com/GoogleContainerTools/skaffold/blob/main/DEVELOPMENT.md#making-a-config-change  , thanks.

**Comment by dherges** [comment]
> > > Hi @dherges Thank you for the contribution , could you please have a separate pr just for the config schema change ? Thanks
> > 
> > 
> > Do you mean the hack/new-version.sh + the 2 lines added to config.go?
> > There are two commits in this pr, you should split this pr into two pr, one for new config schema generation, another for the business logic change.  Please follow the guide here , https://github.com/GoogleContainerTools/skaffold/blob/main/DEVELOPMENT.md#making-a-config-change  , thanks.

I closed this.

For the config option: #9190

The implementation #9191

**Pull request closed without merging**
